// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFLocalUser
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial void PFLocalUserCloseHandle(IntPtr localUserHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserCreateHandleWithPersistedLocalId(IntPtr serviceConfigHandle, byte* persistedLocalId, IntPtr loginHandler, void* customContext, IntPtr* localUserHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserCreateHandleWithSteamUser(IntPtr serviceConfigHandle, void* customContext, IntPtr* localUserHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserCreateHandleWithXboxUser(IntPtr serviceConfigHandle, IntPtr user, void* customContext, IntPtr* localUserHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserDuplicateHandle(IntPtr localUserHandle, IntPtr* duplicatedHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserGetCustomContext(IntPtr localUserHandle, void** customContext);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserGetLocalId(IntPtr localUserHandle, nuint localIdSize, byte* localIdBuffer, nuint* localIdUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserGetLocalIdSize(IntPtr localUserHandle, nuint* localIdSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserGetServiceConfigHandle(IntPtr localUserHandle, IntPtr* serviceConfigHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserHandleCompare(IntPtr user1, IntPtr user2);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserLoginAsync(IntPtr localUserHandle, byte createAccount, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserLoginGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserLoginGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserTryGetEntityHandle(IntPtr localUserHandle, IntPtr* entityHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFLocalUserTryGetXUser(IntPtr localUserHandle, IntPtr* user);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern void PFLocalUserCloseHandle(IntPtr localUserHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserCreateHandleWithPersistedLocalId(IntPtr serviceConfigHandle, byte* persistedLocalId, IntPtr loginHandler, void* customContext, IntPtr* localUserHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserCreateHandleWithSteamUser(IntPtr serviceConfigHandle, void* customContext, IntPtr* localUserHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserCreateHandleWithXboxUser(IntPtr serviceConfigHandle, IntPtr user, void* customContext, IntPtr* localUserHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserDuplicateHandle(IntPtr localUserHandle, IntPtr* duplicatedHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserGetCustomContext(IntPtr localUserHandle, void** customContext);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserGetLocalId(IntPtr localUserHandle, nuint localIdSize, byte* localIdBuffer, nuint* localIdUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserGetLocalIdSize(IntPtr localUserHandle, nuint* localIdSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserGetServiceConfigHandle(IntPtr localUserHandle, IntPtr* serviceConfigHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserHandleCompare(IntPtr user1, IntPtr user2);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserLoginAsync(IntPtr localUserHandle, byte createAccount, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserLoginGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserLoginGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserTryGetEntityHandle(IntPtr localUserHandle, IntPtr* entityHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFLocalUserTryGetXUser(IntPtr localUserHandle, IntPtr* user);
}

#endif
