// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFCloudScript
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

internal enum PFCloudScriptCloudScriptRevisionOption : uint
{
    Live = 0,
    Latest = 1,
    Specific = 2,
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteCloudScriptRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* FunctionName;
    internal PFJsonObject FunctionParameter;
    internal byte* GeneratePlayStreamEvent;
    internal PFCloudScriptCloudScriptRevisionOption* RevisionSelection;
    internal int* SpecificRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptScriptExecutionError
{
    internal byte* Error;
    internal byte* Message;
    internal byte* StackTrace;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptLogStatement
{
    internal PFJsonObject Data;
    internal byte* Level;
    internal byte* Message;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteCloudScriptResult
{
    internal int APIRequestsIssued;
    internal PFCloudScriptScriptExecutionError* Error;
    internal double ExecutionTimeSeconds;
    internal byte* FunctionName;
    internal PFJsonObject FunctionResult;
    internal byte* FunctionResultTooLarge;
    internal int HttpRequestsIssued;
    internal PFCloudScriptLogStatement** Logs;
    internal uint LogsCount;
    internal byte* LogsTooLarge;
    internal uint MemoryConsumedBytes;
    internal double ProcessorTimeSeconds;
    internal int Revision;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteCloudScriptServerRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* FunctionName;
    internal PFJsonObject FunctionParameter;
    internal byte* GeneratePlayStreamEvent;
    internal byte* PlayFabId;
    internal PFCloudScriptCloudScriptRevisionOption* RevisionSelection;
    internal int* SpecificRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteEntityCloudScriptRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal byte* FunctionName;
    internal PFJsonObject FunctionParameter;
    internal byte* GeneratePlayStreamEvent;
    internal PFCloudScriptCloudScriptRevisionOption* RevisionSelection;
    internal int* SpecificRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteFunctionRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal byte* FunctionName;
    internal PFJsonObject FunctionParameter;
    internal byte* GeneratePlayStreamEvent;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptFunctionExecutionError
{
    internal byte* Error;
    internal byte* Message;
    internal byte* StackTrace;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptExecuteFunctionResult
{
    internal PFCloudScriptFunctionExecutionError* Error;
    internal int ExecutionTimeMilliseconds;
    internal byte* FunctionName;
    internal PFJsonObject FunctionResult;
    internal int* FunctionResultSize;
    internal byte* FunctionResultTooLarge;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptListFunctionsRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptEventHubFunctionModel
{
    internal byte* ConnectionString;
    internal byte* EventHubName;
    internal byte* FunctionName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptListEventHubFunctionsResult
{
    internal PFCloudScriptEventHubFunctionModel** Functions;
    internal uint FunctionsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFCloudScriptRegisterEventHubFunctionRequest
{
    internal byte* ConnectionString;
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* EventHubName;
    internal byte* FunctionName;
}
