// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFPlatformSpecific
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFPlatformSpecificServerAwardSteamAchievementAsync(IntPtr titleEntityHandle, PFPlatformSpecificAwardSteamAchievementRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFPlatformSpecificServerAwardSteamAchievementGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFPlatformSpecificAwardSteamAchievementResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFPlatformSpecificServerAwardSteamAchievementGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFPlatformSpecificServerAwardSteamAchievementAsync(IntPtr titleEntityHandle, PFPlatformSpecificAwardSteamAchievementRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFPlatformSpecificServerAwardSteamAchievementGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFPlatformSpecificAwardSteamAchievementResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFPlatformSpecificServerAwardSteamAchievementGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#endif
