// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFPushNotifications
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPushNotificationsAdvancedPushPlatformMsg
{
    internal byte* GCMDataOnly;
    internal byte* Json;
    internal PFPushNotificationPlatform Platform;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPushNotificationsPushNotificationPackage
{
    internal int Badge;
    internal byte* CustomData;
    internal byte* Icon;
    internal byte* Message;
    internal byte* Sound;
    internal byte* Title;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPushNotificationsSendPushNotificationRequest
{
    internal PFPushNotificationsAdvancedPushPlatformMsg** AdvancedPlatformDelivery;
    internal uint AdvancedPlatformDeliveryCount;
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* Message;
    internal PFPushNotificationsPushNotificationPackage* Package;
    internal byte* Recipient;
    internal byte* Subject;
    internal PFPushNotificationPlatform* TargetPlatforms;
    internal uint TargetPlatformsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPushNotificationsSendPushNotificationFromTemplateRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* PushNotificationTemplateId;
    internal byte* Recipient;
}
