// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFData
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataAbortFileUploadsAsync(IntPtr entityHandle, PFDataAbortFileUploadsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataAbortFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataAbortFileUploadsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataAbortFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataDeleteFilesAsync(IntPtr entityHandle, PFDataDeleteFilesRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataDeleteFilesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataDeleteFilesResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataDeleteFilesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataFinalizeFileUploadsAsync(IntPtr entityHandle, PFDataFinalizeFileUploadsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataFinalizeFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataFinalizeFileUploadsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataFinalizeFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetFilesAsync(IntPtr entityHandle, PFDataGetFilesRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetFilesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataGetFilesResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetFilesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetObjectsAsync(IntPtr entityHandle, PFDataGetObjectsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetObjectsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataGetObjectsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataGetObjectsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataInitiateFileUploadsAsync(IntPtr entityHandle, PFDataInitiateFileUploadsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataInitiateFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataInitiateFileUploadsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataInitiateFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataSetObjectsAsync(IntPtr entityHandle, PFDataSetObjectsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataSetObjectsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataSetObjectsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFDataSetObjectsGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataAbortFileUploadsAsync(IntPtr entityHandle, PFDataAbortFileUploadsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataAbortFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataAbortFileUploadsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataAbortFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataDeleteFilesAsync(IntPtr entityHandle, PFDataDeleteFilesRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataDeleteFilesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataDeleteFilesResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataDeleteFilesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataFinalizeFileUploadsAsync(IntPtr entityHandle, PFDataFinalizeFileUploadsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataFinalizeFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataFinalizeFileUploadsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataFinalizeFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetFilesAsync(IntPtr entityHandle, PFDataGetFilesRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetFilesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataGetFilesResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetFilesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetObjectsAsync(IntPtr entityHandle, PFDataGetObjectsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetObjectsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataGetObjectsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataGetObjectsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataInitiateFileUploadsAsync(IntPtr entityHandle, PFDataInitiateFileUploadsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataInitiateFileUploadsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataInitiateFileUploadsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataInitiateFileUploadsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataSetObjectsAsync(IntPtr entityHandle, PFDataSetObjectsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataSetObjectsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFDataSetObjectsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFDataSetObjectsGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#endif
