// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFAuthentication
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationAuthenticateGameServerWithCustomIdAsync(IntPtr entityHandle, PFAuthenticationAuthenticateCustomIdRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationAuthenticateGameServerWithCustomIdGetResult(XAsyncBlock* async, IntPtr* entityHandle, byte* newlyCreated);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationDeleteAsync(IntPtr entityHandle, PFAuthenticationDeleteRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationGetEntityAsync(IntPtr entityHandle, PFAuthenticationGetEntityRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationGetEntityGetResult(XAsyncBlock* async, IntPtr* entityHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationGetEntityWithSecretKeyAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationGetEntityRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationGetEntityWithSecretKeyGetResult(XAsyncBlock* async, IntPtr* entityHandle);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithBattleNetAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithBattleNetGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithBattleNetGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithCustomIDAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithCustomIDGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithCustomIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithOpenIdConnectAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithOpenIdConnectRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithOpenIdConnectGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithOpenIdConnectGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithSteamAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithSteamRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithSteamGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithSteamGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXUserAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithXUserRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXUserGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXUserGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXboxAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithXboxRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXboxGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationLoginWithXboxGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithBattleNetAsync(IntPtr entityHandle, PFAuthenticationLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithCustomIDAsync(IntPtr entityHandle, PFAuthenticationLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithOpenIdConnectAsync(IntPtr entityHandle, PFAuthenticationLoginWithOpenIdConnectRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithSteamAsync(IntPtr entityHandle, PFAuthenticationLoginWithSteamRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithXUserAsync(IntPtr entityHandle, PFAuthenticationLoginWithXUserRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationReLoginWithXboxAsync(IntPtr entityHandle, PFAuthenticationLoginWithXboxRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithAndroidDeviceIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithAndroidDeviceIDRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithAndroidDeviceIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithAndroidDeviceIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithBattleNetAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithBattleNetGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithBattleNetGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithCustomIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithCustomIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithCustomIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithIOSDeviceIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithIOSDeviceIDRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithIOSDeviceIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithIOSDeviceIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithPSNAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithPSNRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithPSNGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithPSNGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithServerCustomIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithServerCustomIdRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithServerCustomIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithServerCustomIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithSteamIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithSteamIdRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithSteamIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithSteamIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithXboxRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithXboxIdRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationServerLoginWithXboxIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationValidateEntityTokenAsync(IntPtr entityHandle, PFAuthenticationValidateEntityTokenRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationValidateEntityTokenGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFAuthenticationValidateEntityTokenResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabCoreLibrary)]
    internal static partial int PFAuthenticationValidateEntityTokenGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationAuthenticateGameServerWithCustomIdAsync(IntPtr entityHandle, PFAuthenticationAuthenticateCustomIdRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationAuthenticateGameServerWithCustomIdGetResult(XAsyncBlock* async, IntPtr* entityHandle, byte* newlyCreated);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationDeleteAsync(IntPtr entityHandle, PFAuthenticationDeleteRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationGetEntityAsync(IntPtr entityHandle, PFAuthenticationGetEntityRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationGetEntityGetResult(XAsyncBlock* async, IntPtr* entityHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationGetEntityWithSecretKeyAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationGetEntityRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationGetEntityWithSecretKeyGetResult(XAsyncBlock* async, IntPtr* entityHandle);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithBattleNetAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithBattleNetGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithBattleNetGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithCustomIDAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithCustomIDGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithCustomIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithOpenIdConnectAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithOpenIdConnectRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithOpenIdConnectGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithOpenIdConnectGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithSteamAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithSteamRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithSteamGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithSteamGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXUserAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithXUserRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXUserGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXUserGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXboxAsync(IntPtr serviceConfigHandle, PFAuthenticationLoginWithXboxRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXboxGetResult(XAsyncBlock* async, IntPtr* entityHandle, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationLoginWithXboxGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithBattleNetAsync(IntPtr entityHandle, PFAuthenticationLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithCustomIDAsync(IntPtr entityHandle, PFAuthenticationLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithOpenIdConnectAsync(IntPtr entityHandle, PFAuthenticationLoginWithOpenIdConnectRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithSteamAsync(IntPtr entityHandle, PFAuthenticationLoginWithSteamRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithXUserAsync(IntPtr entityHandle, PFAuthenticationLoginWithXUserRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationReLoginWithXboxAsync(IntPtr entityHandle, PFAuthenticationLoginWithXboxRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithAndroidDeviceIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithAndroidDeviceIDRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithAndroidDeviceIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithAndroidDeviceIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithBattleNetAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithBattleNetRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithBattleNetGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithBattleNetGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithCustomIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithCustomIDRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithCustomIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithCustomIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithIOSDeviceIDAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithIOSDeviceIDRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithIOSDeviceIDGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithIOSDeviceIDGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithPSNAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithPSNRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithPSNGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithPSNGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithServerCustomIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithServerCustomIdRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithServerCustomIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithServerCustomIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithSteamIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithSteamIdRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithSteamIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithSteamIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationServerLoginWithXboxRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxIdAsync(IntPtr serviceConfigHandle, byte* secretKey, PFAuthenticationLoginWithXboxIdRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxIdGetResult(XAsyncBlock* async, PFAuthenticationEntityTokenResponse** entityTokenResponse, nuint bufferSize, void* buffer, PFAuthenticationLoginResult** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationServerLoginWithXboxIdGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationValidateEntityTokenAsync(IntPtr entityHandle, PFAuthenticationValidateEntityTokenRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationValidateEntityTokenGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFAuthenticationValidateEntityTokenResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabCoreLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFAuthenticationValidateEntityTokenGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#endif
