// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFMultiplayer
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial byte* PFMultiplayerGetErrorMessage(int error);

    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial int PFMultiplayerInitialize(MultiplayerInitializationConfiguration* initializationConfiguration, IntPtr* handle);

    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial int PFMultiplayerSetEntityToken(IntPtr handle, PFEntityKey* entity, byte* entityToken);

    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial int PFMultiplayerSetMemoryCallbacks(IntPtr allocateMemoryCallback, IntPtr freeMemoryCallback);

    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial int PFMultiplayerSetThreadAffinityMask(PFMultiplayerThreadId threadId, ulong threadAffinityMask);

    [LibraryImport(PlayFabMultiplayerLibrary)]
    internal static partial int PFMultiplayerUninitialize(IntPtr handle);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern byte* PFMultiplayerGetErrorMessage(int error);

    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFMultiplayerInitialize(MultiplayerInitializationConfiguration* initializationConfiguration, IntPtr* handle);

    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFMultiplayerSetEntityToken(IntPtr handle, PFEntityKey* entity, byte* entityToken);

    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFMultiplayerSetMemoryCallbacks(IntPtr allocateMemoryCallback, IntPtr freeMemoryCallback);

    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFMultiplayerSetThreadAffinityMask(PFMultiplayerThreadId threadId, ulong threadAffinityMask);

    [DllImport(PlayFabMultiplayerLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFMultiplayerUninitialize(IntPtr handle);
}

#endif
