// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFGroups
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsAcceptGroupApplicationAsync(IntPtr entityHandle, PFGroupsAcceptGroupApplicationRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsAcceptGroupInvitationAsync(IntPtr entityHandle, PFGroupsAcceptGroupInvitationRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsAddMembersAsync(IntPtr entityHandle, PFGroupsAddMembersRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsApplyToGroupAsync(IntPtr entityHandle, PFGroupsApplyToGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsApplyToGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsApplyToGroupResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsApplyToGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsBlockEntityAsync(IntPtr entityHandle, PFGroupsBlockEntityRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsChangeMemberRoleAsync(IntPtr entityHandle, PFGroupsChangeMemberRoleRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateGroupAsync(IntPtr entityHandle, PFGroupsCreateGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsCreateGroupResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateRoleAsync(IntPtr entityHandle, PFGroupsCreateGroupRoleRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateRoleGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsCreateGroupRoleResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsCreateRoleGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsDeleteGroupAsync(IntPtr entityHandle, PFGroupsDeleteGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsDeleteRoleAsync(IntPtr entityHandle, PFGroupsDeleteRoleRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsGetGroupAsync(IntPtr entityHandle, PFGroupsGetGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsGetGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsGetGroupResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsGetGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsInviteToGroupAsync(IntPtr entityHandle, PFGroupsInviteToGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsInviteToGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsInviteToGroupResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsInviteToGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsIsMemberAsync(IntPtr entityHandle, PFGroupsIsMemberRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsIsMemberGetResult(XAsyncBlock* async, PFGroupsIsMemberResponse* result);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupApplicationsAsync(IntPtr entityHandle, PFGroupsListGroupApplicationsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupApplicationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupApplicationsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupApplicationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupBlocksAsync(IntPtr entityHandle, PFGroupsListGroupBlocksRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupBlocksGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupBlocksResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupBlocksGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupInvitationsAsync(IntPtr entityHandle, PFGroupsListGroupInvitationsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupInvitationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupInvitationsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupInvitationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupMembersAsync(IntPtr entityHandle, PFGroupsListGroupMembersRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupMembersGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupMembersResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListGroupMembersGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipAsync(IntPtr entityHandle, PFGroupsListMembershipRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListMembershipResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipOpportunitiesAsync(IntPtr entityHandle, PFGroupsListMembershipOpportunitiesRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipOpportunitiesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListMembershipOpportunitiesResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsListMembershipOpportunitiesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsRemoveGroupApplicationAsync(IntPtr entityHandle, PFGroupsRemoveGroupApplicationRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsRemoveGroupInvitationAsync(IntPtr entityHandle, PFGroupsRemoveGroupInvitationRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsRemoveMembersAsync(IntPtr entityHandle, PFGroupsRemoveMembersRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUnblockEntityAsync(IntPtr entityHandle, PFGroupsUnblockEntityRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateGroupAsync(IntPtr entityHandle, PFGroupsUpdateGroupRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsUpdateGroupResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateRoleAsync(IntPtr entityHandle, PFGroupsUpdateGroupRoleRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateRoleGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsUpdateGroupRoleResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFGroupsUpdateRoleGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsAcceptGroupApplicationAsync(IntPtr entityHandle, PFGroupsAcceptGroupApplicationRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsAcceptGroupInvitationAsync(IntPtr entityHandle, PFGroupsAcceptGroupInvitationRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsAddMembersAsync(IntPtr entityHandle, PFGroupsAddMembersRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsApplyToGroupAsync(IntPtr entityHandle, PFGroupsApplyToGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsApplyToGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsApplyToGroupResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsApplyToGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsBlockEntityAsync(IntPtr entityHandle, PFGroupsBlockEntityRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsChangeMemberRoleAsync(IntPtr entityHandle, PFGroupsChangeMemberRoleRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateGroupAsync(IntPtr entityHandle, PFGroupsCreateGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsCreateGroupResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateRoleAsync(IntPtr entityHandle, PFGroupsCreateGroupRoleRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateRoleGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsCreateGroupRoleResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsCreateRoleGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsDeleteGroupAsync(IntPtr entityHandle, PFGroupsDeleteGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsDeleteRoleAsync(IntPtr entityHandle, PFGroupsDeleteRoleRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsGetGroupAsync(IntPtr entityHandle, PFGroupsGetGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsGetGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsGetGroupResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsGetGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsInviteToGroupAsync(IntPtr entityHandle, PFGroupsInviteToGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsInviteToGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsInviteToGroupResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsInviteToGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsIsMemberAsync(IntPtr entityHandle, PFGroupsIsMemberRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsIsMemberGetResult(XAsyncBlock* async, PFGroupsIsMemberResponse* result);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupApplicationsAsync(IntPtr entityHandle, PFGroupsListGroupApplicationsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupApplicationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupApplicationsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupApplicationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupBlocksAsync(IntPtr entityHandle, PFGroupsListGroupBlocksRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupBlocksGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupBlocksResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupBlocksGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupInvitationsAsync(IntPtr entityHandle, PFGroupsListGroupInvitationsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupInvitationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupInvitationsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupInvitationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupMembersAsync(IntPtr entityHandle, PFGroupsListGroupMembersRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupMembersGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListGroupMembersResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListGroupMembersGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipAsync(IntPtr entityHandle, PFGroupsListMembershipRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListMembershipResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipOpportunitiesAsync(IntPtr entityHandle, PFGroupsListMembershipOpportunitiesRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipOpportunitiesGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsListMembershipOpportunitiesResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsListMembershipOpportunitiesGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsRemoveGroupApplicationAsync(IntPtr entityHandle, PFGroupsRemoveGroupApplicationRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsRemoveGroupInvitationAsync(IntPtr entityHandle, PFGroupsRemoveGroupInvitationRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsRemoveMembersAsync(IntPtr entityHandle, PFGroupsRemoveMembersRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUnblockEntityAsync(IntPtr entityHandle, PFGroupsUnblockEntityRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateGroupAsync(IntPtr entityHandle, PFGroupsUpdateGroupRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateGroupGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsUpdateGroupResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateGroupGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateRoleAsync(IntPtr entityHandle, PFGroupsUpdateGroupRoleRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateRoleGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFGroupsUpdateGroupRoleResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGroupsUpdateRoleGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#endif
