// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFSegments
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerSegmentsAsync(IntPtr entityHandle, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerSegmentsResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerTagsAsync(IntPtr entityHandle, PFSegmentsGetPlayerTagsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerTagsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerTagsResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsClientGetPlayerTagsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerAddPlayerTagAsync(IntPtr titleEntityHandle, PFSegmentsAddPlayerTagRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetAllSegmentsAsync(IntPtr titleEntityHandle, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetAllSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetAllSegmentsResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetAllSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerSegmentsAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayersSegmentsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerSegmentsResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerTagsAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayerTagsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerTagsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerTagsResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayerTagsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayersInSegmentAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayersInSegmentRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayersInSegmentGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayersInSegmentResult** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerGetPlayersInSegmentGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFSegmentsServerRemovePlayerTagAsync(IntPtr titleEntityHandle, PFSegmentsRemovePlayerTagRequest* request, XAsyncBlock* async);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerSegmentsAsync(IntPtr entityHandle, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerSegmentsResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerTagsAsync(IntPtr entityHandle, PFSegmentsGetPlayerTagsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerTagsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerTagsResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsClientGetPlayerTagsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerAddPlayerTagAsync(IntPtr titleEntityHandle, PFSegmentsAddPlayerTagRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetAllSegmentsAsync(IntPtr titleEntityHandle, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetAllSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetAllSegmentsResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetAllSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerSegmentsAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayersSegmentsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerSegmentsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerSegmentsResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerSegmentsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerTagsAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayerTagsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerTagsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayerTagsResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayerTagsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayersInSegmentAsync(IntPtr titleEntityHandle, PFSegmentsGetPlayersInSegmentRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayersInSegmentGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFSegmentsGetPlayersInSegmentResult** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerGetPlayersInSegmentGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFSegmentsServerRemovePlayerTagAsync(IntPtr titleEntityHandle, PFSegmentsRemovePlayerTagRequest* request, XAsyncBlock* async);
}

#endif
