// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFInventory
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryAddInventoryItemsAsync(IntPtr entityHandle, PFInventoryAddInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryAddInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryAddInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryAddInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryDeleteInventoryCollectionAsync(IntPtr entityHandle, PFInventoryDeleteInventoryCollectionRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryDeleteInventoryItemsAsync(IntPtr entityHandle, PFInventoryDeleteInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryDeleteInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryDeleteInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryDeleteInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteInventoryOperationsAsync(IntPtr entityHandle, PFInventoryExecuteInventoryOperationsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteInventoryOperationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryExecuteInventoryOperationsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteInventoryOperationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteTransferOperationsAsync(IntPtr entityHandle, PFInventoryExecuteTransferOperationsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteTransferOperationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryExecuteTransferOperationsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryExecuteTransferOperationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryCollectionIdsAsync(IntPtr entityHandle, PFInventoryGetInventoryCollectionIdsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryCollectionIdsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryCollectionIdsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryCollectionIdsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryItemsAsync(IntPtr entityHandle, PFInventoryGetInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryOperationStatusAsync(IntPtr entityHandle, PFInventoryGetInventoryOperationStatusRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryOperationStatusGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryOperationStatusResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetInventoryOperationStatusGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetTransactionHistoryAsync(IntPtr entityHandle, PFInventoryGetTransactionHistoryRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetTransactionHistoryGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetTransactionHistoryResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryGetTransactionHistoryGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryPurchaseInventoryItemsAsync(IntPtr entityHandle, PFInventoryPurchaseInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryPurchaseInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryPurchaseInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryPurchaseInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemAppleAppStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemAppleAppStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemAppleAppStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemAppleAppStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemAppleAppStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemGooglePlayInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemGooglePlayInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemGooglePlayInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemGooglePlayInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemGooglePlayInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemMicrosoftStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemMicrosoftStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemMicrosoftStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemMicrosoftStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemMicrosoftStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemNintendoEShopInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemNintendoEShopInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemNintendoEShopInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemNintendoEShopInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemNintendoEShopInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemPlayStationStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemPlayStationStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemPlayStationStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemPlayStationStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemPlayStationStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemSteamInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemSteamInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemSteamInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemSteamInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryRedeemSteamInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventorySubtractInventoryItemsAsync(IntPtr entityHandle, PFInventorySubtractInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventorySubtractInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventorySubtractInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventorySubtractInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryTransferInventoryItemsAsync(IntPtr entityHandle, PFInventoryTransferInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryTransferInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryTransferInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryTransferInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryUpdateInventoryItemsAsync(IntPtr entityHandle, PFInventoryUpdateInventoryItemsRequest* request, XAsyncBlock* async);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryUpdateInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryUpdateInventoryItemsResponse** result, nuint* bufferUsed);

    [LibraryImport(PlayFabServicesLibrary)]
    internal static partial int PFInventoryUpdateInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryAddInventoryItemsAsync(IntPtr entityHandle, PFInventoryAddInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryAddInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryAddInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryAddInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryDeleteInventoryCollectionAsync(IntPtr entityHandle, PFInventoryDeleteInventoryCollectionRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryDeleteInventoryItemsAsync(IntPtr entityHandle, PFInventoryDeleteInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryDeleteInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryDeleteInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryDeleteInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteInventoryOperationsAsync(IntPtr entityHandle, PFInventoryExecuteInventoryOperationsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteInventoryOperationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryExecuteInventoryOperationsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteInventoryOperationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteTransferOperationsAsync(IntPtr entityHandle, PFInventoryExecuteTransferOperationsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteTransferOperationsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryExecuteTransferOperationsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryExecuteTransferOperationsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryCollectionIdsAsync(IntPtr entityHandle, PFInventoryGetInventoryCollectionIdsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryCollectionIdsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryCollectionIdsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryCollectionIdsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryItemsAsync(IntPtr entityHandle, PFInventoryGetInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryOperationStatusAsync(IntPtr entityHandle, PFInventoryGetInventoryOperationStatusRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryOperationStatusGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetInventoryOperationStatusResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetInventoryOperationStatusGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetTransactionHistoryAsync(IntPtr entityHandle, PFInventoryGetTransactionHistoryRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetTransactionHistoryGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryGetTransactionHistoryResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryGetTransactionHistoryGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryPurchaseInventoryItemsAsync(IntPtr entityHandle, PFInventoryPurchaseInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryPurchaseInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryPurchaseInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryPurchaseInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemAppleAppStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemAppleAppStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemAppleAppStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemAppleAppStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemAppleAppStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemGooglePlayInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemGooglePlayInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemGooglePlayInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemGooglePlayInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemGooglePlayInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemMicrosoftStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemMicrosoftStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemMicrosoftStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemMicrosoftStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemMicrosoftStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemNintendoEShopInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemNintendoEShopInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemNintendoEShopInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemNintendoEShopInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemNintendoEShopInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemPlayStationStoreInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemPlayStationStoreInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemPlayStationStoreInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemPlayStationStoreInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemPlayStationStoreInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemSteamInventoryItemsAsync(IntPtr entityHandle, PFInventoryRedeemSteamInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemSteamInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryRedeemSteamInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryRedeemSteamInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventorySubtractInventoryItemsAsync(IntPtr entityHandle, PFInventorySubtractInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventorySubtractInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventorySubtractInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventorySubtractInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryTransferInventoryItemsAsync(IntPtr entityHandle, PFInventoryTransferInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryTransferInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryTransferInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryTransferInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryUpdateInventoryItemsAsync(IntPtr entityHandle, PFInventoryUpdateInventoryItemsRequest* request, XAsyncBlock* async);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryUpdateInventoryItemsGetResult(XAsyncBlock* async, nuint bufferSize, void* buffer, PFInventoryUpdateInventoryItemsResponse** result, nuint* bufferUsed);

    [DllImport(PlayFabServicesLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFInventoryUpdateInventoryItemsGetResultSize(XAsyncBlock* async, nuint* bufferSize);
}

#endif
