// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFGameSaveFiles
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

#if NET7_0_OR_GREATER

internal static unsafe partial class NativePlayFab
{
    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesAddUserWithUiAsync(IntPtr localUserHandle, PFGameSaveFilesAddUserOptions options, XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesAddUserWithUiResult(XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesGetFolder(IntPtr localUserHandle, nuint saveRootFolderSize, byte* saveRootFolderBuffer, nuint* saveRootFolderUsed);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesGetFolderSize(IntPtr localUserHandle, nuint* saveRootFolderSize);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesGetRemainingQuota(IntPtr localUserHandle, long* remainingQuota);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesInitialize(PFGameSaveInitArgs* args);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesIsConnectedToCloud(IntPtr localUserHandle, byte* isConnectedToCloud);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesResetCloudAsync(IntPtr localUserHandle, XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesResetCloudResult(XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesSetActiveDeviceChangedCallback(IntPtr callbackQueue, IntPtr callback, void* context);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesSetSaveDescriptionAsync(IntPtr localUserHandle, byte* shortSaveDescription, XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesSetSaveDescriptionResult(XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesUninitializeAsync(XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesUninitializeResult(XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesUploadWithUiAsync(IntPtr localUserHandle, PFGameSaveFilesUploadOption option, XAsyncBlock* async);

    [LibraryImport(PlayFabGameSaveLibrary)]
    internal static partial int PFGameSaveFilesUploadWithUiResult(XAsyncBlock* async);
}

#else

internal static unsafe partial class NativePlayFab
{
    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesAddUserWithUiAsync(IntPtr localUserHandle, PFGameSaveFilesAddUserOptions options, XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesAddUserWithUiResult(XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesGetFolder(IntPtr localUserHandle, nuint saveRootFolderSize, byte* saveRootFolderBuffer, nuint* saveRootFolderUsed);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesGetFolderSize(IntPtr localUserHandle, nuint* saveRootFolderSize);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesGetRemainingQuota(IntPtr localUserHandle, long* remainingQuota);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesInitialize(PFGameSaveInitArgs* args);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesIsConnectedToCloud(IntPtr localUserHandle, byte* isConnectedToCloud);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesResetCloudAsync(IntPtr localUserHandle, XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesResetCloudResult(XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesSetActiveDeviceChangedCallback(IntPtr callbackQueue, IntPtr callback, void* context);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesSetSaveDescriptionAsync(IntPtr localUserHandle, byte* shortSaveDescription, XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesSetSaveDescriptionResult(XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesUninitializeAsync(XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesUninitializeResult(XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesUploadWithUiAsync(IntPtr localUserHandle, PFGameSaveFilesUploadOption option, XAsyncBlock* async);

    [DllImport(PlayFabGameSaveLibrary, CallingConvention = CallingConvention.StdCall, ExactSpelling = true)]
    internal static extern int PFGameSaveFilesUploadWithUiResult(XAsyncBlock* async);
}

#endif
