// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFPlatformSpecific
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificAndroidDevicePushNotificationRegistrationRequest
{
    internal byte* ConfirmationMessage;
    internal byte* DeviceToken;
    internal byte* SendPushNotificationConfirmation;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificRefreshPSNAuthTokenRequest
{
    internal byte* AuthCode;
    internal int* IssuerId;
    internal byte* RedirectUri;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificRegisterForIOSPushNotificationRequest
{
    internal byte* ConfirmationMessage;
    internal byte* DeviceToken;
    internal byte* SendPushNotificationConfirmation;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificAwardSteamAchievementItem
{
    internal byte* AchievementName;
    internal byte* PlayFabId;
    internal byte Result;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificAwardSteamAchievementRequest
{
    internal PFPlatformSpecificAwardSteamAchievementItem** Achievements;
    internal uint AchievementsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFPlatformSpecificAwardSteamAchievementResult
{
    internal PFPlatformSpecificAwardSteamAchievementItem** AchievementResults;
    internal uint AchievementResultsCount;
}
