// <auto-generated>
//   Generated by eng/playfab/emit_native.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFGroups
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace GDK.Net.Interop;

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsAcceptGroupApplicationRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsAcceptGroupInvitationRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsAddMembersRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
    internal PFEntityKey** Members;
    internal uint MembersCount;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsApplyToGroupRequest
{
    internal byte* AutoAcceptOutstandingInvite;
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsEntityWithLineage
{
    internal PFEntityKey* Key;
    internal PFEntityKeyDictionaryEntry* Lineage;
    internal uint LineageCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsApplyToGroupResponse
{
    internal PFGroupsEntityWithLineage* Entity;
    internal long Expires;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsBlockEntityRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsChangeMemberRoleRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal byte* DestinationRoleId;
    internal PFEntityKey* Group;
    internal PFEntityKey** Members;
    internal uint MembersCount;
    internal byte* OriginRoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsCreateGroupRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal byte* GroupName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsCreateGroupResponse
{
    internal byte* AdminRoleId;
    internal long Created;
    internal PFEntityKey* Group;
    internal byte* GroupName;
    internal byte* MemberRoleId;
    internal int ProfileVersion;
    internal PFStringDictionaryEntry* Roles;
    internal uint RolesCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsCreateGroupRoleRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
    internal byte* RoleId;
    internal byte* RoleName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsCreateGroupRoleResponse
{
    internal int ProfileVersion;
    internal byte* RoleId;
    internal byte* RoleName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsDeleteGroupRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsDeleteRoleRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGetGroupRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
    internal byte* GroupName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGetGroupResponse
{
    internal byte* AdminRoleId;
    internal long Created;
    internal PFEntityKey* Group;
    internal byte* GroupName;
    internal byte* MemberRoleId;
    internal int ProfileVersion;
    internal PFStringDictionaryEntry* Roles;
    internal uint RolesCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsInviteToGroupRequest
{
    internal byte* AutoAcceptOutstandingApplication;
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsInviteToGroupResponse
{
    internal long Expires;
    internal PFEntityKey* Group;
    internal PFGroupsEntityWithLineage* InvitedByEntity;
    internal PFGroupsEntityWithLineage* InvitedEntity;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsIsMemberRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsIsMemberResponse
{
    internal byte IsMember;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupApplicationsRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGroupApplication
{
    internal PFGroupsEntityWithLineage* Entity;
    internal long Expires;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupApplicationsResponse
{
    internal PFGroupsGroupApplication** Applications;
    internal uint ApplicationsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupBlocksRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGroupBlock
{
    internal PFGroupsEntityWithLineage* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupBlocksResponse
{
    internal PFGroupsGroupBlock** BlockedEntities;
    internal uint BlockedEntitiesCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupInvitationsRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGroupInvitation
{
    internal long Expires;
    internal PFEntityKey* Group;
    internal PFGroupsEntityWithLineage* InvitedByEntity;
    internal PFGroupsEntityWithLineage* InvitedEntity;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupInvitationsResponse
{
    internal PFGroupsGroupInvitation** Invitations;
    internal uint InvitationsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupMembersRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsEntityMemberRole
{
    internal PFGroupsEntityWithLineage** Members;
    internal uint MembersCount;
    internal byte* RoleId;
    internal byte* RoleName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListGroupMembersResponse
{
    internal PFGroupsEntityMemberRole** Members;
    internal uint MembersCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListMembershipRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGroupRole
{
    internal byte* RoleId;
    internal byte* RoleName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsGroupWithRoles
{
    internal PFEntityKey* Group;
    internal byte* GroupName;
    internal int ProfileVersion;
    internal PFGroupsGroupRole** Roles;
    internal uint RolesCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListMembershipResponse
{
    internal PFGroupsGroupWithRoles** Groups;
    internal uint GroupsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListMembershipOpportunitiesRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsListMembershipOpportunitiesResponse
{
    internal PFGroupsGroupApplication** Applications;
    internal uint ApplicationsCount;
    internal PFGroupsGroupInvitation** Invitations;
    internal uint InvitationsCount;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsRemoveGroupApplicationRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsRemoveGroupInvitationRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsRemoveMembersRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Group;
    internal PFEntityKey** Members;
    internal uint MembersCount;
    internal byte* RoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsUnblockEntityRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal PFEntityKey* Entity;
    internal PFEntityKey* Group;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsUpdateGroupRequest
{
    internal byte* AdminRoleId;
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal int* ExpectedProfileVersion;
    internal PFEntityKey* Group;
    internal byte* GroupName;
    internal byte* MemberRoleId;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsUpdateGroupResponse
{
    internal byte* OperationReason;
    internal int ProfileVersion;
    internal PFOperationTypes* SetResult;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsUpdateGroupRoleRequest
{
    internal PFStringDictionaryEntry* CustomTags;
    internal uint CustomTagsCount;
    internal int* ExpectedProfileVersion;
    internal PFEntityKey* Group;
    internal byte* RoleId;
    internal byte* RoleName;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct PFGroupsUpdateGroupRoleResponse
{
    internal byte* OperationReason;
    internal int ProfileVersion;
    internal PFOperationTypes* SetResult;
}
