using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using Xunit;

namespace GDK.Net.Tests;

/// <summary>
/// Drift check for the committed API reference under <c>docs/api/</c>.
/// </summary>
/// <remarks>
/// <para>
/// The reference is generated by docfx (<c>eng/generate-docs.ps1</c>) and committed, so it rots
/// the moment a public type is added or removed without regenerating. This test catches exactly
/// that, by comparing the assembly's exported types against the generated pages.
/// </para>
/// <para>
/// It deliberately does *not* shell out to docfx. Running the generator inside the unit test suite
/// would add minutes to every run and would fail on a machine where the local tool has not been
/// restored. Page-level correspondence is the part that actually drifts; the content is a pure
/// function of the doc comments, which the compiler already enforces through
/// <c>GenerateDocumentationFile</c> plus <c>TreatWarningsAsErrors</c>.
/// </para>
/// </remarks>
public class ApiReferenceDriftTests
{
    /// <summary>
    /// docfx emits one page per type, one per namespace, and a table of contents. The index is
    /// written by <c>eng/generate-docs.ps1</c> rather than docfx.
    /// </summary>
    private const string IndexPage = "README";

    private static DirectoryInfo? FindApiDirectory()
    {
        for (DirectoryInfo? directory = new(AppContext.BaseDirectory);
             directory is not null;
             directory = directory.Parent)
        {
            if (!File.Exists(Path.Combine(directory.FullName, "GDK.Net.slnx")))
            {
                continue;
            }

            var api = new DirectoryInfo(Path.Combine(directory.FullName, "docs", "api"));
            return api.Exists ? api : null;
        }

        return null;
    }

    [Fact]
    public void EveryPublicTypeHasAGeneratedPage()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            // Not running from a source tree (for example a packaged run). Nothing to check.
            return;
        }

        HashSet<string> pages = api.GetFiles("*.md")
            .Select(file => Path.GetFileNameWithoutExtension(file.Name))
            .ToHashSet(StringComparer.Ordinal);

        string[] undocumented = typeof(GameRuntime).Assembly
            .GetExportedTypes()
            .Select(type => type.FullName!.Replace('+', '.'))
            .Distinct(StringComparer.Ordinal)
            .Where(name => !pages.Contains(name))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            undocumented.Length == 0,
            $"docs/api is missing {undocumented.Length} page(s). Run: pwsh eng/generate-docs.ps1{Environment.NewLine}"
            + string.Join(Environment.NewLine, undocumented.Take(25)));
    }

    [Fact]
    public void NoGeneratedPageSurvivesItsType()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        Type[] exported = typeof(GameRuntime).Assembly.GetExportedTypes();

        HashSet<string> expected = exported
            .Select(type => type.FullName!.Replace('+', '.'))
            .ToHashSet(StringComparer.Ordinal);

        foreach (string? @namespace in exported.Select(type => type.Namespace))
        {
            if (!string.IsNullOrEmpty(@namespace))
            {
                expected.Add(@namespace);
            }
        }

        expected.Add(IndexPage);

        string[] stale = api.GetFiles("*.md")
            .Select(file => Path.GetFileNameWithoutExtension(file.Name))
            .Where(page => !expected.Contains(page))
            .OrderBy(page => page, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            stale.Length == 0,
            $"docs/api has {stale.Length} page(s) for types that no longer exist. "
            + $"Run: pwsh eng/generate-docs.ps1{Environment.NewLine}"
            + string.Join(Environment.NewLine, stale.Take(25)));
    }

    /// <summary>
    /// Page-level correspondence alone would not notice a method added to an existing type, which
    /// is the more common edit. docfx is configured with <c>memberLayout: samePage</c>, so every
    /// public member is rendered onto its declaring type's page; this asserts each one is there.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Accessors, operators and constructors are skipped: docfx renders them under the property,
    /// event or type name rather than their metadata name, so matching on the name would be either
    /// vacuous or wrong.
    /// </para>
    /// <para>
    /// This is name-level, not signature-level: a new *overload* of an already documented method
    /// will not trip it, because the existing anchor still matches. <c>generate-docs.ps1 -Check</c>
    /// compares the generated files byte for byte and does catch that; this test exists to give the
    /// fast, tool-free signal in the ordinary test run.
    /// </para>
    /// </remarks>
    [Fact]
    public void EveryPublicMemberAppearsOnItsTypePage()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        const BindingFlags Declared = BindingFlags.Public | BindingFlags.NonPublic
            | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        var missing = new List<string>();

        foreach (Type type in typeof(GameRuntime).Assembly.GetExportedTypes())
        {
            string page = Path.Combine(api.FullName, type.FullName!.Replace('+', '.') + ".md");
            if (!File.Exists(page))
            {
                // EveryPublicTypeHasAGeneratedPage reports this; do not double-count it.
                continue;
            }

            string text = File.ReadAllText(page);

            // A delegate renders as one signature; its Invoke/BeginInvoke/EndInvoke are generated.
            if (typeof(Delegate).IsAssignableFrom(type))
            {
                continue;
            }

            string typeUid = type.FullName!.Replace('+', '.');

            foreach (MemberInfo member in type.GetMembers(Declared))
            {
                if (!IsPubliclyVisible(member) || IsRenderedIndirectly(member))
                {
                    continue;
                }

                // docfx anchors each member as <a id="Namespace_Type_Member">, suffixing the
                // parameter types when the method takes any, and renders enum members as
                // `Member = value` instead. Matching those exact forms rather than the bare name
                // keeps the check meaningful for members called Id, Name or Value, whose names
                // appear all over an unrelated page.
                bool present;
                if (type.IsEnum)
                {
                    present = text.Contains($"`{member.Name} = ", StringComparison.Ordinal);
                }
                else
                {
                    string anchor = $"<a id=\"{(typeUid + "." + member.Name).Replace('.', '_')}";

                    // The delimiter matters: without it, a missing Get would be satisfied by
                    // GetAsync's anchor.
                    present = text.Contains(anchor + "\"", StringComparison.Ordinal)
                        || text.Contains(anchor + "_", StringComparison.Ordinal);
                }

                if (!present)
                {
                    missing.Add($"{type.FullName}.{member.Name}");
                }
            }
        }

        Assert.True(
            missing.Count == 0,
            $"docs/api is missing {missing.Count} member(s). Run: pwsh eng/generate-docs.ps1"
            + Environment.NewLine
            + string.Join(Environment.NewLine, missing.Take(25)));
    }

    private static bool IsPubliclyVisible(MemberInfo member) => member switch
    {
        MethodBase method => method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly,
        FieldInfo field => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly,
        PropertyInfo property => IsPubliclyVisible(
            property.GetMethod ?? property.SetMethod
            ?? throw new InvalidOperationException($"{property.Name} has no accessor.")),
        EventInfo @event => @event.AddMethod is not null && IsPubliclyVisible(@event.AddMethod),
        Type nested => nested.IsNestedPublic || nested.IsNestedFamily,
        _ => false,
    };

    private static bool IsRenderedIndirectly(MemberInfo member)
    {
        // Unspeakable names (<Clone>$) and anything the compiler emitted for us.
        if (member.Name.Contains('<', StringComparison.Ordinal)
            || member.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false))
        {
            return true;
        }

        // Synthesised record members. docfx hides these, correctly: they are an artefact of
        // `record`, not part of the designed surface, and they carry no doc comment.
        if (member.Name is "PrintMembers" or "EqualityContract")
        {
            return true;
        }

        return member switch
        {
            // Property/event accessors, operators, and the enum backing field.
            MethodBase { IsSpecialName: true } => true,
            FieldInfo { IsSpecialName: true } => true,
            // Constructors render as the type name, which is always present as the page title.
            ConstructorInfo => true,
            // A nested type gets its own page, which EveryPublicTypeHasAGeneratedPage checks.
            Type => true,
            _ => false,
        };
    }
}
