using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using Xunit;

namespace GDK.Net.Tests;

/// <summary>
/// Drift check for the committed API reference under <c>docs/api/</c>.
/// </summary>
/// <remarks>
/// <para>
/// The reference is generated by docfx (<c>eng/generate-docs.ps1</c>) and committed, so it rots
/// the moment a public type is added or removed without regenerating. This test catches exactly
/// that, by comparing the assembly's exported types against the generated pages.
/// </para>
/// <para>
/// It deliberately does *not* shell out to docfx. Running the generator inside the unit test suite
/// would add minutes to every run and would fail on a machine where the local tool has not been
/// restored. Page-level correspondence is the part that actually drifts; the content is a pure
/// function of the doc comments, which the compiler already enforces through
/// <c>GenerateDocumentationFile</c> plus <c>TreatWarningsAsErrors</c>.
/// </para>
/// </remarks>
public class ApiReferenceDriftTests
{
    /// <summary>
    /// docfx emits one page per type, one per namespace, and a table of contents.
    /// <c>eng/api-layout.ps1</c> then moves the pages into one folder per namespace and writes a
    /// <c>README.md</c> index into each folder and the root; those indexes are not type pages.
    /// </summary>
    private const string IndexPage = "README";

    private static DirectoryInfo? FindApiDirectory()
    {
        for (DirectoryInfo? directory = new(AppContext.BaseDirectory);
             directory is not null;
             directory = directory.Parent)
        {
            if (!File.Exists(Path.Combine(directory.FullName, "GDK.Net.slnx")))
            {
                continue;
            }

            var api = new DirectoryInfo(Path.Combine(directory.FullName, "docs", "api"));
            return api.Exists ? api : null;
        }

        return null;
    }

    /// <summary>
    /// The generated pages, keyed by the type or namespace they document. The reference is laid
    /// out one folder per namespace, so the search has to recurse, and the folder indexes are
    /// excluded because they document an area rather than a type.
    /// </summary>
    private static Dictionary<string, FileInfo> GetPages(DirectoryInfo api) => api
        .GetFiles("*.md", SearchOption.AllDirectories)
        .Where(file => !string.Equals(file.Name, IndexPage + ".md", StringComparison.Ordinal))
        .ToDictionary(
            file => Path.GetFileNameWithoutExtension(file.Name),
            file => file,
            StringComparer.Ordinal);

    [Fact]
    public void EveryPublicTypeHasAGeneratedPage()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            // Not running from a source tree (for example a packaged run). Nothing to check.
            return;
        }

        Dictionary<string, FileInfo> pages = GetPages(api);

        string[] undocumented = typeof(GameRuntime).Assembly
            .GetExportedTypes()
            .Select(type => type.FullName!.Replace('+', '.'))
            .Distinct(StringComparer.Ordinal)
            .Where(name => !pages.ContainsKey(name))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            undocumented.Length == 0,
            $"docs/api is missing {undocumented.Length} page(s). Run: pwsh eng/generate-docs.ps1{Environment.NewLine}"
            + string.Join(Environment.NewLine, undocumented.Take(25)));
    }

    [Fact]
    public void NoGeneratedPageSurvivesItsType()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        Type[] exported = typeof(GameRuntime).Assembly.GetExportedTypes();

        HashSet<string> expected = exported
            .Select(type => type.FullName!.Replace('+', '.'))
            .ToHashSet(StringComparer.Ordinal);

        foreach (string? @namespace in exported.Select(type => type.Namespace))
        {
            if (!string.IsNullOrEmpty(@namespace))
            {
                expected.Add(@namespace);
            }
        }

        string[] stale = GetPages(api).Keys
            .Where(page => !expected.Contains(page))
            .OrderBy(page => page, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            stale.Length == 0,
            $"docs/api has {stale.Length} page(s) for types that no longer exist. "
            + $"Run: pwsh eng/generate-docs.ps1{Environment.NewLine}"
            + string.Join(Environment.NewLine, stale.Take(25)));
    }

    /// <summary>
    /// Every namespace folder carries a <c>README.md</c> index, and so does the reference root.
    /// The indexes are what makes the reference navigable now that the pages are split across
    /// folders, so a missing one is drift just as much as a missing page.
    /// </summary>
    [Fact]
    public void EveryNamespaceFolderHasAnIndex()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        var missing = new List<string>();

        if (!File.Exists(Path.Combine(api.FullName, IndexPage + ".md")))
        {
            missing.Add("docs/api/README.md");
        }

        foreach (FileInfo page in GetPages(api).Values)
        {
            string folder = page.DirectoryName!;
            string index = Path.Combine(folder, IndexPage + ".md");
            if (!File.Exists(index) && !missing.Contains(index))
            {
                missing.Add(index);
            }
        }

        Assert.True(
            missing.Count == 0,
            $"docs/api is missing {missing.Count} folder index(es). "
            + $"Run: pwsh eng/generate-docs.ps1{Environment.NewLine}"
            + string.Join(Environment.NewLine, missing.Take(25)));
    }

    /// <summary>
    /// A flat reference directory stops rendering on GitHub once it passes 1,000 entries, which is
    /// why the pages are split by namespace. This guards the split: if one folder ever grows past
    /// the limit, its pages are hidden from anyone browsing the repository on the web.
    /// </summary>
    [Fact]
    public void NoFolderExceedsTheGitHubListingLimit()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        const int GitHubListingLimit = 1000;

        string[] oversized = new[] { api }
            .Concat(api.GetDirectories("*", SearchOption.AllDirectories))
            .Select(folder => (folder, count: folder.GetFiles().Length + folder.GetDirectories().Length))
            .Where(entry => entry.count >= GitHubListingLimit)
            .Select(entry => $"{entry.folder.Name}: {entry.count} entries")
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            oversized.Length == 0,
            $"{oversized.Length} reference folder(s) are at or past GitHub's {GitHubListingLimit}-entry "
            + $"listing limit and would render truncated. Split the namespace in eng/api-areas.json."
            + Environment.NewLine
            + string.Join(Environment.NewLine, oversized));
    }

    /// <summary>
    /// Page-level correspondence alone would not notice a method added to an existing type, which
    /// is the more common edit. docfx is configured with <c>memberLayout: samePage</c>, so every
    /// public member is rendered onto its declaring type's page; this asserts each one is there.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Accessors, operators and constructors are skipped: docfx renders them under the property,
    /// event or type name rather than their metadata name, so matching on the name would be either
    /// vacuous or wrong.
    /// </para>
    /// <para>
    /// This is name-level, not signature-level: a new *overload* of an already documented method
    /// will not trip it, because the existing anchor still matches. <c>generate-docs.ps1 -Check</c>
    /// compares the generated files byte for byte and does catch that; this test exists to give the
    /// fast, tool-free signal in the ordinary test run.
    /// </para>
    /// </remarks>
    [Fact]
    public void EveryPublicMemberAppearsOnItsTypePage()
    {
        DirectoryInfo? api = FindApiDirectory();
        if (api is null)
        {
            return;
        }

        const BindingFlags Declared = BindingFlags.Public | BindingFlags.NonPublic
            | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        Dictionary<string, FileInfo> pages = GetPages(api);
        var missing = new List<string>();

        foreach (Type type in typeof(GameRuntime).Assembly.GetExportedTypes())
        {
            string typeUid = type.FullName!.Replace('+', '.');
            if (!pages.TryGetValue(typeUid, out FileInfo? page))
            {
                // EveryPublicTypeHasAGeneratedPage reports this; do not double-count it.
                continue;
            }

            string text = File.ReadAllText(page.FullName);

            // A delegate renders as one signature; its Invoke/BeginInvoke/EndInvoke are generated.
            if (typeof(Delegate).IsAssignableFrom(type))
            {
                continue;
            }

            foreach (MemberInfo member in type.GetMembers(Declared))
            {
                if (!IsPubliclyVisible(member) || IsRenderedIndirectly(member))
                {
                    continue;
                }

                // docfx anchors each member as <a id="Namespace_Type_Member">, suffixing the
                // parameter types when the method takes any, and renders enum members as
                // `Member = value` instead. Matching those exact forms rather than the bare name
                // keeps the check meaningful for members called Id, Name or Value, whose names
                // appear all over an unrelated page.
                bool present;
                if (type.IsEnum)
                {
                    present = text.Contains($"`{member.Name} = ", StringComparison.Ordinal);
                }
                else
                {
                    string anchor = $"<a id=\"{(typeUid + "." + member.Name).Replace('.', '_')}";

                    // The delimiter matters: without it, a missing Get would be satisfied by
                    // GetAsync's anchor.
                    present = text.Contains(anchor + "\"", StringComparison.Ordinal)
                        || text.Contains(anchor + "_", StringComparison.Ordinal);
                }

                if (!present)
                {
                    missing.Add($"{type.FullName}.{member.Name}");
                }
            }
        }

        Assert.True(
            missing.Count == 0,
            $"docs/api is missing {missing.Count} member(s). Run: pwsh eng/generate-docs.ps1"
            + Environment.NewLine
            + string.Join(Environment.NewLine, missing.Take(25)));
    }

    private static bool IsPubliclyVisible(MemberInfo member) => member switch
    {
        MethodBase method => method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly,
        FieldInfo field => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly,
        PropertyInfo property => IsPubliclyVisible(
            property.GetMethod ?? property.SetMethod
            ?? throw new InvalidOperationException($"{property.Name} has no accessor.")),
        EventInfo @event => @event.AddMethod is not null && IsPubliclyVisible(@event.AddMethod),
        Type nested => nested.IsNestedPublic || nested.IsNestedFamily,
        _ => false,
    };

    private static bool IsRenderedIndirectly(MemberInfo member)
    {
        // Unspeakable names (<Clone>$) and anything the compiler emitted for us.
        if (member.Name.Contains('<', StringComparison.Ordinal)
            || member.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false))
        {
            return true;
        }

        // Synthesised record members. docfx hides these, correctly: they are an artefact of
        // `record`, not part of the designed surface, and they carry no doc comment.
        if (member.Name is "PrintMembers" or "EqualityContract")
        {
            return true;
        }

        return member switch
        {
            // Property/event accessors, operators, and the enum backing field.
            MethodBase { IsSpecialName: true } => true,
            FieldInfo { IsSpecialName: true } => true,
            // Constructors render as the type name, which is always present as the page title.
            ConstructorInfo => true,
            // A nested type gets its own page, which EveryPublicTypeHasAGeneratedPage checks.
            Type => true,
            _ => false,
        };
    }
}
