using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using GDK.Net;
using GDK.Net.PlayFab.Party;
using Xunit;

namespace GDK.Net.Tests;

/// <summary>
/// Guards the PlayFab Party projection.
/// </summary>
/// <remarks>
/// The public Party enums are generated by <c>eng/playfab/emit_party.py</c> and the hand-written
/// layer converts between them and the interop enums with a plain cast, which is only correct
/// while the two agree member for member. Nothing here needs the Party runtime.
/// </remarks>
public class PartyContractTests
{
    private static Assembly Library => typeof(GameRuntime).Assembly;

    [Fact]
    public void EveryPublicPartyEnumMatchesItsInteropEnum()
    {
        var pairs = PartyEnumPairs().ToList();

        // Party and PartyXboxLive together define 41 public enums; a parser regression usually
        // drops a whole header rather than a single member.
        Assert.True(pairs.Count >= 40, $"Only {pairs.Count} Party enums were paired with an interop enum.");

        foreach ((Type projected, Type native) in pairs)
        {
            var expected = Members(native);
            var actual = Members(projected);

            Assert.Equal(
                Enum.GetUnderlyingType(native),
                Enum.GetUnderlyingType(projected));

            Assert.Equal(expected, actual);
        }
    }

    [Fact]
    public void EveryPublicPartyEnumHasAnInteropCounterpart()
    {
        var native = Library
            .GetTypes()
            .Where(t => t.IsEnum && t.Namespace == "GDK.Net.Interop")
            .Select(t => t.Name)
            .ToHashSet(StringComparer.Ordinal);

        var orphans = PublicPartyEnums()
            .Select(t => new { t.Name, Native = ToScreamingSnake(t.Name) })
            .Where(x => !native.Contains(x.Native))
            .Select(x => $"{x.Name} has no interop enum named {x.Native}.")
            .ToList();

        Assert.Empty(orphans);
    }

    [Fact]
    public void StateChangeTypeCoversEveryNativeValue()
    {
        // PartyStateChangeReader switches over this enum, so a value the projection does not know
        // about would be dropped silently on the pump.
        Type native = Library.GetType("GDK.Net.Interop.PARTY_STATE_CHANGE_TYPE", throwOnError: true)!;

        Assert.Equal(
            Enum.GetValues(native).Cast<object>().Select(Convert.ToUInt32).OrderBy(v => v).ToArray(),
            Enum.GetValues(typeof(PartyStateChangeType)).Cast<PartyStateChangeType>().Select(v => (uint)v).OrderBy(v => v).ToArray());
    }

    [Fact]
    public void PartyOperationIdDefaultIsNotValid()
    {
        Assert.Equal(PartyOperationId.None, default);
        Assert.False(PartyOperationId.None.IsValid);
        Assert.False(default(PartyOperationId).IsValid);
    }

    [Fact]
    public void PartyOperationIdComparesByValue()
    {
        PartyOperationId none = PartyOperationId.None;

        Assert.True(none == default(PartyOperationId));
        Assert.False(none != default(PartyOperationId));
        Assert.Equal(none.GetHashCode(), default(PartyOperationId).GetHashCode());
        Assert.False(none.Equals("not an id"));
    }

    [Fact]
    public void PartyExceptionIsAGameRuntimeException()
    {
        // A title should be able to catch every native failure with one catch clause.
        Assert.True(typeof(GameRuntimeException).IsAssignableFrom(typeof(PartyException)));
    }

    [Fact]
    public void PublicPartySurfaceExposesNoInteropTypes()
    {
        var offenders = new List<string>();

        foreach (Type type in PlayFabContractTests.PublicPlayFabTypes()
                     .Where(t => t.Namespace is "GDK.Net.PlayFab.Party" or "GDK.Net.PlayFab.Multiplayer"))
        {
            foreach (MemberInfo member in type.GetMembers(
                BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                foreach ((string what, Type candidate) in PlayFabContractTests.SignatureTypes(member))
                {
                    if (PlayFabContractTests.IsInterop(candidate))
                    {
                        offenders.Add($"{type.FullName}.{member.Name} exposes {what} {candidate.Name}.");
                    }
                }
            }
        }

        Assert.Empty(offenders);
    }

    private static IEnumerable<(Type Projected, Type Native)> PartyEnumPairs()
    {
        var native = Library
            .GetTypes()
            .Where(t => t.IsEnum && t.Namespace == "GDK.Net.Interop")
            .ToDictionary(t => t.Name, StringComparer.Ordinal);

        foreach (Type projected in PublicPartyEnums())
        {
            if (native.TryGetValue(ToScreamingSnake(projected.Name), out Type? counterpart))
            {
                yield return (projected, counterpart);
            }
        }
    }

    private static IEnumerable<Type> PublicPartyEnums() =>
        Library
            .GetExportedTypes()
            .Where(t => t.IsEnum && t.Namespace is "GDK.Net.PlayFab.Party");

    private static SortedDictionary<string, ulong> Members(Type enumType)
    {
        var members = new SortedDictionary<string, ulong>(StringComparer.Ordinal);

        foreach (object value in Enum.GetValues(enumType))
        {
            members[Enum.GetName(enumType, value)!] = Convert.ToUInt64(value);
        }

        return members;
    }

    /// <summary>
    /// Reverses the generator's <c>pascal(SCREAMING_SNAKE)</c> naming, so
    /// <c>PartyXblStateChangeType</c> maps back onto <c>PARTY_XBL_STATE_CHANGE_TYPE</c>.
    /// </summary>
    private static string ToScreamingSnake(string pascal)
    {
        var builder = new StringBuilder(pascal.Length + 8);

        for (int i = 0; i < pascal.Length; i++)
        {
            char c = pascal[i];

            bool boundary = i > 0 && char.IsUpper(c) &&
                (!char.IsUpper(pascal[i - 1]) ||
                 (i + 1 < pascal.Length && char.IsLower(pascal[i + 1])));

            if (boundary)
            {
                builder.Append('_');
            }

            builder.Append(char.ToUpperInvariant(c));
        }

        return builder.ToString();
    }
}
