// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFEntity
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFEntityToken</c>.</summary>
public sealed class EntityToken
{
    /// <summary><c>Token</c>.</summary>
    public string? Token { get; set; }

    /// <summary><c>Expiration</c>.</summary>
    public DateTimeOffset? Expiration { get; set; }

    internal static unsafe EntityToken FromNative(PFEntityToken* source)
    {
        var value = new EntityToken();
        value.Token = Utf8.ToString(source->Token);
        value.Expiration = source->Expiration is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->Expiration);
        return value;
    }

    internal unsafe void WriteTo(PFEntityToken* target, PlayFabArena arena)
    {
        *target = default;
        target->Token = arena.String(Token);
        target->Expiration = arena.Value(Expiration is null ? null : (long?)PlayFabTime.ToUnixTime(Expiration.Value));
    }
}
