// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFEvents
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFEventsEventContents</c>.</summary>
public sealed class EventsEventContents
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>EventNamespace</c>.</summary>
    public string? EventNamespace { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>OriginalId</c>.</summary>
    public string? OriginalId { get; set; }

    /// <summary><c>OriginalTimestamp</c>.</summary>
    public DateTimeOffset? OriginalTimestamp { get; set; }

    /// <summary><c>Payload</c>.</summary>
    public string? Payload { get; set; }

    /// <summary><c>PayloadJSON</c>.</summary>
    public string? PayloadJSON { get; set; }

    internal static unsafe EventsEventContents FromNative(PFEventsEventContents* source)
    {
        var value = new EventsEventContents();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        value.EventNamespace = Utf8.ToString(source->EventNamespace);
        value.Name = Utf8.ToString(source->Name);
        value.OriginalId = Utf8.ToString(source->OriginalId);
        value.OriginalTimestamp = source->OriginalTimestamp is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->OriginalTimestamp);
        value.Payload = Utf8.ToString(source->Payload.StringValue);
        value.PayloadJSON = Utf8.ToString(source->PayloadJSON);
        return value;
    }

    internal unsafe void WriteTo(PFEventsEventContents* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->EventNamespace = arena.String(EventNamespace);
        target->Name = arena.String(Name);
        target->OriginalId = arena.String(OriginalId);
        target->OriginalTimestamp = arena.Value(OriginalTimestamp is null ? null : (long?)PlayFabTime.ToUnixTime(OriginalTimestamp.Value));
        target->Payload.StringValue = arena.String(Payload);
        target->PayloadJSON = arena.String(PayloadJSON);
    }
}

/// <summary>Projects <c>PFEventsWriteEventsRequest</c>.</summary>
public sealed class EventsWriteEventsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Events</c>.</summary>
    public IReadOnlyList<EventsEventContents>? Events { get; set; }

    internal static unsafe EventsWriteEventsRequest FromNative(PFEventsWriteEventsRequest* source)
    {
        var value = new EventsWriteEventsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        if (source->Events is not null && source->EventsCount != 0)
        {
            var list2 = new List<EventsEventContents>((int)source->EventsCount);
            for (uint i2 = 0; i2 < source->EventsCount; i2++)
            {
                list2.Add(EventsEventContents.FromNative(source->Events[i2]));
            }

            value.Events = list2;
        }
        return value;
    }

    internal unsafe void WriteTo(PFEventsWriteEventsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->EventsCount = (uint)(Events is null ? 0 : Events.Count);
        if (Events is not null && Events.Count > 0)
        {
            PFEventsEventContents** array2 = arena.PointerArray<PFEventsEventContents>(Events.Count);
            for (int i2 = 0; i2 < Events.Count; i2++)
            {
                PFEventsEventContents* item2 = arena.Alloc<PFEventsEventContents>(1);
                Events[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->Events = array2;
        }
    }
}

/// <summary>Projects <c>PFEventsWriteEventsResponse</c>.</summary>
public sealed class EventsWriteEventsResponse
{
    /// <summary><c>AssignedEventIds</c>.</summary>
    public IReadOnlyList<string>? AssignedEventIds { get; set; }

    internal static unsafe EventsWriteEventsResponse FromNative(PFEventsWriteEventsResponse* source)
    {
        var value = new EventsWriteEventsResponse();
        if (source->AssignedEventIds is not null && source->AssignedEventIdsCount != 0)
        {
            var list0 = new List<string>((int)source->AssignedEventIdsCount);
            for (uint i0 = 0; i0 < source->AssignedEventIdsCount; i0++)
            {
                list0.Add(Utf8.ToString(source->AssignedEventIds[i0]) ?? string.Empty);
            }

            value.AssignedEventIds = list0;
        }
        return value;
    }

    internal unsafe void WriteTo(PFEventsWriteEventsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->AssignedEventIdsCount = (uint)(AssignedEventIds is null ? 0 : AssignedEventIds.Count);
        target->AssignedEventIds = arena.StringArray(AssignedEventIds);
    }
}
