// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFExperimentation
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFExperimentationGetTreatmentAssignmentRequest</c>.</summary>
public sealed class ExperimentationGetTreatmentAssignmentRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    internal static unsafe ExperimentationGetTreatmentAssignmentRequest FromNative(PFExperimentationGetTreatmentAssignmentRequest* source)
    {
        var value = new ExperimentationGetTreatmentAssignmentRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        return value;
    }

    internal unsafe void WriteTo(PFExperimentationGetTreatmentAssignmentRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
    }
}

/// <summary>Projects <c>PFExperimentationGetTreatmentAssignmentResult</c>.</summary>
public sealed class ExperimentationGetTreatmentAssignmentResult
{
    /// <summary><c>TreatmentAssignment</c>.</summary>
    public TreatmentAssignment? TreatmentAssignment { get; set; }

    internal static unsafe ExperimentationGetTreatmentAssignmentResult FromNative(PFExperimentationGetTreatmentAssignmentResult* source)
    {
        var value = new ExperimentationGetTreatmentAssignmentResult();
        value.TreatmentAssignment = source->TreatmentAssignment is null ? null : TreatmentAssignment.FromNative(source->TreatmentAssignment);
        return value;
    }

    internal unsafe void WriteTo(PFExperimentationGetTreatmentAssignmentResult* target, PlayFabArena arena)
    {
        *target = default;
        if (TreatmentAssignment is not null)
        {
            PFTreatmentAssignment* native0 = arena.Alloc<PFTreatmentAssignment>(1);
            TreatmentAssignment.WriteTo(native0, arena);
            target->TreatmentAssignment = native0;
        }
    }
}
