// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFGameSaveFilesUi
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFGameSaveFilesUiOutOfStorageUserAction</c>.</summary>
public enum GameSaveFilesUiOutOfStorageUserAction : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUiOutOfStorageUserAction::Cancel</c>.</summary>
    Cancel = 0,
    /// <summary>Projects <c>PFGameSaveFilesUiOutOfStorageUserAction::Retry</c>.</summary>
    Retry = 1,
}

/// <summary>Projects <c>PFGameSaveFilesUiConflictUserAction</c>.</summary>
public enum GameSaveFilesUiConflictUserAction : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUiConflictUserAction::Cancel</c>.</summary>
    Cancel = 0,
    /// <summary>Projects <c>PFGameSaveFilesUiConflictUserAction::TakeLocal</c>.</summary>
    TakeLocal = 1,
    /// <summary>Projects <c>PFGameSaveFilesUiConflictUserAction::TakeRemote</c>.</summary>
    TakeRemote = 2,
}

/// <summary>Projects <c>PFGameSaveFilesUiActiveDeviceContentionUserAction</c>.</summary>
public enum GameSaveFilesUiActiveDeviceContentionUserAction : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUiActiveDeviceContentionUserAction::Cancel</c>.</summary>
    Cancel = 0,
    /// <summary>Projects <c>PFGameSaveFilesUiActiveDeviceContentionUserAction::Retry</c>.</summary>
    Retry = 1,
    /// <summary>Projects <c>PFGameSaveFilesUiActiveDeviceContentionUserAction::SyncLastSavedData</c>.</summary>
    SyncLastSavedData = 2,
}

/// <summary>Projects <c>PFGameSaveFilesUiSyncFailedUserAction</c>.</summary>
public enum GameSaveFilesUiSyncFailedUserAction : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUiSyncFailedUserAction::Cancel</c>.</summary>
    Cancel = 0,
    /// <summary>Projects <c>PFGameSaveFilesUiSyncFailedUserAction::Retry</c>.</summary>
    Retry = 1,
    /// <summary>Projects <c>PFGameSaveFilesUiSyncFailedUserAction::UseOffline</c>.</summary>
    UseOffline = 2,
}

/// <summary>Projects <c>PFGameSaveFilesUiProgressUserAction</c>.</summary>
public enum GameSaveFilesUiProgressUserAction : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUiProgressUserAction::Cancel</c>.</summary>
    Cancel = 0,
}
