// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFGameSaveFiles
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFGameSaveFilesUploadOption</c>.</summary>
public enum GameSaveFilesUploadOption : uint
{
    /// <summary>Projects <c>PFGameSaveFilesUploadOption::KeepDeviceActive</c>.</summary>
    KeepDeviceActive = 0,
    /// <summary>Projects <c>PFGameSaveFilesUploadOption::ReleaseDeviceAsActive</c>.</summary>
    ReleaseDeviceAsActive = 1,
}

/// <summary>Projects <c>PFGameSaveFilesSyncState</c>.</summary>
public enum GameSaveFilesSyncState : uint
{
    /// <summary>Projects <c>PFGameSaveFilesSyncState::NotStarted</c>.</summary>
    NotStarted = 0,
    /// <summary>Projects <c>PFGameSaveFilesSyncState::PreparingForDownload</c>.</summary>
    PreparingForDownload = 1,
    /// <summary>Projects <c>PFGameSaveFilesSyncState::Downloading</c>.</summary>
    Downloading = 2,
    /// <summary>Projects <c>PFGameSaveFilesSyncState::PreparingForUpload</c>.</summary>
    PreparingForUpload = 3,
    /// <summary>Projects <c>PFGameSaveFilesSyncState::Uploading</c>.</summary>
    Uploading = 4,
    /// <summary>Projects <c>PFGameSaveFilesSyncState::SyncComplete</c>.</summary>
    SyncComplete = 5,
}

/// <summary>Projects <c>PFGameSaveFilesAddUserOptions</c>.</summary>
[Flags]
public enum GameSaveFilesAddUserOptions : uint
{
    /// <summary>Projects <c>PFGameSaveFilesAddUserOptions::None</c>.</summary>
    None = 0x00,
    /// <summary>Projects <c>PFGameSaveFilesAddUserOptions::RollbackToLastKnownGood</c>.</summary>
    RollbackToLastKnownGood = 0x01,
    /// <summary>Projects <c>PFGameSaveFilesAddUserOptions::RollbackToLastConflict</c>.</summary>
    RollbackToLastConflict = 0x02,
}

/// <summary>Projects <c>PFGameSaveInitOptions</c>.</summary>
[Flags]
public enum GameSaveInitOptions : ulong
{
    /// <summary>Projects <c>PFGameSaveInitOptions::None</c>.</summary>
    None = 0x00,
}

/// <summary>Projects <c>PFGameSaveDescriptor</c>.</summary>
public sealed class GameSaveDescriptor
{
    /// <summary><c>Time</c>.</summary>
    public DateTimeOffset Time { get; set; }

    /// <summary><c>TotalBytes</c>.</summary>
    public ulong TotalBytes { get; set; }

    /// <summary><c>UploadedBytes</c>.</summary>
    public ulong UploadedBytes { get; set; }

    /// <summary><c>DeviceType</c>.</summary>
    public string? DeviceType { get; set; }

    /// <summary><c>DeviceId</c>.</summary>
    public string? DeviceId { get; set; }

    /// <summary><c>DeviceFriendlyName</c>.</summary>
    public string? DeviceFriendlyName { get; set; }

    /// <summary><c>ThumbnailUri</c>.</summary>
    public string? ThumbnailUri { get; set; }

    /// <summary><c>ShortSaveDescription</c>.</summary>
    public string? ShortSaveDescription { get; set; }

    internal static unsafe GameSaveDescriptor FromNative(PFGameSaveDescriptor* source)
    {
        var value = new GameSaveDescriptor();
        value.Time = PlayFabTime.ToDateTimeOffset(source->Time);
        value.TotalBytes = source->TotalBytes;
        value.UploadedBytes = source->UploadedBytes;
        value.DeviceType = Utf8.ToString(source->DeviceType, 256);
        value.DeviceId = Utf8.ToString(source->DeviceId, 256);
        value.DeviceFriendlyName = Utf8.ToString(source->DeviceFriendlyName, 256);
        value.ThumbnailUri = Utf8.ToString(source->ThumbnailUri, 2048);
        value.ShortSaveDescription = Utf8.ToString(source->ShortSaveDescription, 4096);
        return value;
    }

    internal unsafe void WriteTo(PFGameSaveDescriptor* target, PlayFabArena arena)
    {
        *target = default;
        target->Time = PlayFabTime.ToUnixTime(Time);
        target->TotalBytes = TotalBytes;
        target->UploadedBytes = UploadedBytes;
        Utf8.CopyFixed(target->DeviceType, 256, DeviceType);
        Utf8.CopyFixed(target->DeviceId, 256, DeviceId);
        Utf8.CopyFixed(target->DeviceFriendlyName, 256, DeviceFriendlyName);
        Utf8.CopyFixed(target->ThumbnailUri, 2048, ThumbnailUri);
        Utf8.CopyFixed(target->ShortSaveDescription, 4096, ShortSaveDescription);
    }
}
