// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFLeaderboards
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFLeaderboardsLeaderboardSortDirection</c>.</summary>
public enum LeaderboardsLeaderboardSortDirection : uint
{
    /// <summary>Projects <c>PFLeaderboardsLeaderboardSortDirection::Descending</c>.</summary>
    Descending = 0,
    /// <summary>Projects <c>PFLeaderboardsLeaderboardSortDirection::Ascending</c>.</summary>
    Ascending = 1,
}

/// <summary>Projects <c>PFExternalFriendSources</c>.</summary>
[Flags]
public enum ExternalFriendSources : uint
{
    /// <summary>Projects <c>PFExternalFriendSources::None</c>.</summary>
    None = 0x0,
    /// <summary>Projects <c>PFExternalFriendSources::Steam</c>.</summary>
    Steam = 0x1,
    /// <summary>Projects <c>PFExternalFriendSources::Facebook</c>.</summary>
    Facebook = 0x2,
    /// <summary>Projects <c>PFExternalFriendSources::Xbox</c>.</summary>
    Xbox = 0x4,
    /// <summary>Projects <c>PFExternalFriendSources::Psn</c>.</summary>
    Psn = 0x8,
    /// <summary>Projects <c>PFExternalFriendSources::All</c>.</summary>
    All = 0x10,
}

/// <summary>Projects <c>PFLeaderboardsCreateLeaderboardDefinitionRequest</c>.</summary>
public sealed class LeaderboardsCreateLeaderboardDefinitionRequest
{
    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardColumn>? Columns { get; set; }

    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public LeaderboardsLeaderboardEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>SizeLimit</c>.</summary>
    public int SizeLimit { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe LeaderboardsCreateLeaderboardDefinitionRequest FromNative(PFLeaderboardsCreateLeaderboardDefinitionRequest* source)
    {
        var value = new LeaderboardsCreateLeaderboardDefinitionRequest();
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list0 = new List<LeaderboardsLeaderboardColumn>((int)source->ColumnsCount);
            for (uint i0 = 0; i0 < source->ColumnsCount; i0++)
            {
                list0.Add(LeaderboardsLeaderboardColumn.FromNative(source->Columns[i0]));
            }

            value.Columns = list0;
        }
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map2 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i2 = 0; i2 < source->CustomTagsCount; i2++)
            {
                map2[Utf8.ToString(source->CustomTags[i2].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i2].Value) ?? string.Empty;
            }

            value.CustomTags = map2;
        }
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : LeaderboardsLeaderboardEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.Name = Utf8.ToString(source->Name);
        value.SizeLimit = source->SizeLimit;
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsCreateLeaderboardDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFLeaderboardsLeaderboardColumn** array0 = arena.PointerArray<PFLeaderboardsLeaderboardColumn>(Columns.Count);
            for (int i0 = 0; i0 < Columns.Count; i0++)
            {
                PFLeaderboardsLeaderboardColumn* item0 = arena.Alloc<PFLeaderboardsLeaderboardColumn>(1);
                Columns[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->Columns = array0;
        }
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries2 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next2 = 0;
            foreach (KeyValuePair<string, string> pair2 in CustomTags)
            {
                entries2[next2].Key = arena.String(pair2.Key);
                entries2[next2].Value = arena.String(pair2.Value);
                next2++;
            }

            target->CustomTags = entries2;
        }
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFLeaderboardsLeaderboardEventEmissionConfig* native5 = arena.Alloc<PFLeaderboardsLeaderboardEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native5, arena);
            target->EventEmissionConfig = native5;
        }
        target->Name = arena.String(Name);
        target->SizeLimit = SizeLimit;
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native8 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native8, arena);
            target->VersionConfiguration = native8;
        }
    }
}

/// <summary>Projects <c>PFLeaderboardsDeleteLeaderboardDefinitionRequest</c>.</summary>
public sealed class LeaderboardsDeleteLeaderboardDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe LeaderboardsDeleteLeaderboardDefinitionRequest FromNative(PFLeaderboardsDeleteLeaderboardDefinitionRequest* source)
    {
        var value = new LeaderboardsDeleteLeaderboardDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsDeleteLeaderboardDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFLeaderboardsDeleteLeaderboardEntriesRequest</c>.</summary>
public sealed class LeaderboardsDeleteLeaderboardEntriesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EntityIds</c>.</summary>
    public IReadOnlyList<string>? EntityIds { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe LeaderboardsDeleteLeaderboardEntriesRequest FromNative(PFLeaderboardsDeleteLeaderboardEntriesRequest* source)
    {
        var value = new LeaderboardsDeleteLeaderboardEntriesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        if (source->EntityIds is not null && source->EntityIdsCount != 0)
        {
            var list2 = new List<string>((int)source->EntityIdsCount);
            for (uint i2 = 0; i2 < source->EntityIdsCount; i2++)
            {
                list2.Add(Utf8.ToString(source->EntityIds[i2]) ?? string.Empty);
            }

            value.EntityIds = list2;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsDeleteLeaderboardEntriesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->EntityIdsCount = (uint)(EntityIds is null ? 0 : EntityIds.Count);
        target->EntityIds = arena.StringArray(EntityIds);
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFLeaderboardsEntityLeaderboardEntry</c>.</summary>
public sealed class LeaderboardsEntityLeaderboardEntry
{
    /// <summary><c>DisplayName</c>.</summary>
    public string? DisplayName { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>LastUpdated</c>.</summary>
    public DateTimeOffset LastUpdated { get; set; }

    /// <summary><c>Metadata</c>.</summary>
    public string? Metadata { get; set; }

    /// <summary><c>Rank</c>.</summary>
    public int Rank { get; set; }

    /// <summary><c>Scores</c>.</summary>
    public IReadOnlyList<string>? Scores { get; set; }

    internal static unsafe LeaderboardsEntityLeaderboardEntry FromNative(PFLeaderboardsEntityLeaderboardEntry* source)
    {
        var value = new LeaderboardsEntityLeaderboardEntry();
        value.DisplayName = Utf8.ToString(source->DisplayName);
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        value.LastUpdated = PlayFabTime.ToDateTimeOffset(source->LastUpdated);
        value.Metadata = Utf8.ToString(source->Metadata);
        value.Rank = source->Rank;
        if (source->Scores is not null && source->ScoresCount != 0)
        {
            var list5 = new List<string>((int)source->ScoresCount);
            for (uint i5 = 0; i5 < source->ScoresCount; i5++)
            {
                list5.Add(Utf8.ToString(source->Scores[i5]) ?? string.Empty);
            }

            value.Scores = list5;
        }
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsEntityLeaderboardEntry* target, PlayFabArena arena)
    {
        *target = default;
        target->DisplayName = arena.String(DisplayName);
        if (Entity is not null)
        {
            PFEntityKey* native1 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native1, arena);
            target->Entity = native1;
        }
        target->LastUpdated = PlayFabTime.ToUnixTime(LastUpdated);
        target->Metadata = arena.String(Metadata);
        target->Rank = Rank;
        target->ScoresCount = (uint)(Scores is null ? 0 : Scores.Count);
        target->Scores = arena.StringArray(Scores);
    }
}

/// <summary>Projects <c>PFLeaderboardsGetEntityLeaderboardRequest</c>.</summary>
public sealed class LeaderboardsGetEntityLeaderboardRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>LeaderboardName</c>.</summary>
    public string? LeaderboardName { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public uint PageSize { get; set; }

    /// <summary><c>StartingPosition</c>.</summary>
    public uint? StartingPosition { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint? Version { get; set; }

    internal static unsafe LeaderboardsGetEntityLeaderboardRequest FromNative(PFLeaderboardsGetEntityLeaderboardRequest* source)
    {
        var value = new LeaderboardsGetEntityLeaderboardRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.LeaderboardName = Utf8.ToString(source->LeaderboardName);
        value.PageSize = source->PageSize;
        value.StartingPosition = source->StartingPosition is null ? null : (uint?)(*source->StartingPosition);
        value.Version = source->Version is null ? null : (uint?)(*source->Version);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetEntityLeaderboardRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->LeaderboardName = arena.String(LeaderboardName);
        target->PageSize = PageSize;
        target->StartingPosition = arena.Value(StartingPosition);
        target->Version = arena.Value(Version);
    }
}

/// <summary>Projects <c>PFLeaderboardsGetEntityLeaderboardResponse</c>.</summary>
public sealed class LeaderboardsGetEntityLeaderboardResponse
{
    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardColumn>? Columns { get; set; }

    /// <summary><c>EntryCount</c>.</summary>
    public uint EntryCount { get; set; }

    /// <summary><c>NextReset</c>.</summary>
    public DateTimeOffset? NextReset { get; set; }

    /// <summary><c>Rankings</c>.</summary>
    public IReadOnlyList<LeaderboardsEntityLeaderboardEntry>? Rankings { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    internal static unsafe LeaderboardsGetEntityLeaderboardResponse FromNative(PFLeaderboardsGetEntityLeaderboardResponse* source)
    {
        var value = new LeaderboardsGetEntityLeaderboardResponse();
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list0 = new List<LeaderboardsLeaderboardColumn>((int)source->ColumnsCount);
            for (uint i0 = 0; i0 < source->ColumnsCount; i0++)
            {
                list0.Add(LeaderboardsLeaderboardColumn.FromNative(source->Columns[i0]));
            }

            value.Columns = list0;
        }
        value.EntryCount = source->EntryCount;
        value.NextReset = source->NextReset is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->NextReset);
        if (source->Rankings is not null && source->RankingsCount != 0)
        {
            var list4 = new List<LeaderboardsEntityLeaderboardEntry>((int)source->RankingsCount);
            for (uint i4 = 0; i4 < source->RankingsCount; i4++)
            {
                list4.Add(LeaderboardsEntityLeaderboardEntry.FromNative(source->Rankings[i4]));
            }

            value.Rankings = list4;
        }
        value.Version = source->Version;
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetEntityLeaderboardResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFLeaderboardsLeaderboardColumn** array0 = arena.PointerArray<PFLeaderboardsLeaderboardColumn>(Columns.Count);
            for (int i0 = 0; i0 < Columns.Count; i0++)
            {
                PFLeaderboardsLeaderboardColumn* item0 = arena.Alloc<PFLeaderboardsLeaderboardColumn>(1);
                Columns[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->Columns = array0;
        }
        target->EntryCount = EntryCount;
        target->NextReset = arena.Value(NextReset is null ? null : (long?)PlayFabTime.ToUnixTime(NextReset.Value));
        target->RankingsCount = (uint)(Rankings is null ? 0 : Rankings.Count);
        if (Rankings is not null && Rankings.Count > 0)
        {
            PFLeaderboardsEntityLeaderboardEntry** array4 = arena.PointerArray<PFLeaderboardsEntityLeaderboardEntry>(Rankings.Count);
            for (int i4 = 0; i4 < Rankings.Count; i4++)
            {
                PFLeaderboardsEntityLeaderboardEntry* item4 = arena.Alloc<PFLeaderboardsEntityLeaderboardEntry>(1);
                Rankings[i4].WriteTo(item4, arena);
                array4[i4] = item4;
            }

            target->Rankings = array4;
        }
        target->Version = Version;
    }
}

/// <summary>Projects <c>PFLeaderboardsGetFriendLeaderboardForEntityRequest</c>.</summary>
public sealed class LeaderboardsGetFriendLeaderboardForEntityRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>ExternalFriendSources</c>.</summary>
    public ExternalFriendSources? ExternalFriendSources { get; set; }

    /// <summary><c>LeaderboardName</c>.</summary>
    public string? LeaderboardName { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint? Version { get; set; }

    /// <summary><c>XboxToken</c>.</summary>
    public string? XboxToken { get; set; }

    internal static unsafe LeaderboardsGetFriendLeaderboardForEntityRequest FromNative(PFLeaderboardsGetFriendLeaderboardForEntityRequest* source)
    {
        var value = new LeaderboardsGetFriendLeaderboardForEntityRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        value.ExternalFriendSources = source->ExternalFriendSources is null ? null : (ExternalFriendSources?)(*source->ExternalFriendSources);
        value.LeaderboardName = Utf8.ToString(source->LeaderboardName);
        value.Version = source->Version is null ? null : (uint?)(*source->Version);
        value.XboxToken = Utf8.ToString(source->XboxToken);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetFriendLeaderboardForEntityRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->ExternalFriendSources = arena.Value((PFExternalFriendSources?)ExternalFriendSources);
        target->LeaderboardName = arena.String(LeaderboardName);
        target->Version = arena.Value(Version);
        target->XboxToken = arena.String(XboxToken);
    }
}

/// <summary>Projects <c>PFLeaderboardsGetLeaderboardAroundEntityRequest</c>.</summary>
public sealed class LeaderboardsGetLeaderboardAroundEntityRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>LeaderboardName</c>.</summary>
    public string? LeaderboardName { get; set; }

    /// <summary><c>MaxSurroundingEntries</c>.</summary>
    public uint MaxSurroundingEntries { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint? Version { get; set; }

    internal static unsafe LeaderboardsGetLeaderboardAroundEntityRequest FromNative(PFLeaderboardsGetLeaderboardAroundEntityRequest* source)
    {
        var value = new LeaderboardsGetLeaderboardAroundEntityRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        value.LeaderboardName = Utf8.ToString(source->LeaderboardName);
        value.MaxSurroundingEntries = source->MaxSurroundingEntries;
        value.Version = source->Version is null ? null : (uint?)(*source->Version);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetLeaderboardAroundEntityRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->LeaderboardName = arena.String(LeaderboardName);
        target->MaxSurroundingEntries = MaxSurroundingEntries;
        target->Version = arena.Value(Version);
    }
}

/// <summary>Projects <c>PFLeaderboardsGetLeaderboardDefinitionRequest</c>.</summary>
public sealed class LeaderboardsGetLeaderboardDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe LeaderboardsGetLeaderboardDefinitionRequest FromNative(PFLeaderboardsGetLeaderboardDefinitionRequest* source)
    {
        var value = new LeaderboardsGetLeaderboardDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetLeaderboardDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFLeaderboardsGetLeaderboardDefinitionResponse</c>.</summary>
public sealed class LeaderboardsGetLeaderboardDefinitionResponse
{
    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardColumn>? Columns { get; set; }

    /// <summary><c>Created</c>.</summary>
    public DateTimeOffset Created { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public LeaderboardsLeaderboardEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>LastResetTime</c>.</summary>
    public DateTimeOffset? LastResetTime { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>SizeLimit</c>.</summary>
    public int SizeLimit { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe LeaderboardsGetLeaderboardDefinitionResponse FromNative(PFLeaderboardsGetLeaderboardDefinitionResponse* source)
    {
        var value = new LeaderboardsGetLeaderboardDefinitionResponse();
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list0 = new List<LeaderboardsLeaderboardColumn>((int)source->ColumnsCount);
            for (uint i0 = 0; i0 < source->ColumnsCount; i0++)
            {
                list0.Add(LeaderboardsLeaderboardColumn.FromNative(source->Columns[i0]));
            }

            value.Columns = list0;
        }
        value.Created = PlayFabTime.ToDateTimeOffset(source->Created);
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : LeaderboardsLeaderboardEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.LastResetTime = source->LastResetTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->LastResetTime);
        value.Name = Utf8.ToString(source->Name);
        value.SizeLimit = source->SizeLimit;
        value.Version = source->Version;
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetLeaderboardDefinitionResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFLeaderboardsLeaderboardColumn** array0 = arena.PointerArray<PFLeaderboardsLeaderboardColumn>(Columns.Count);
            for (int i0 = 0; i0 < Columns.Count; i0++)
            {
                PFLeaderboardsLeaderboardColumn* item0 = arena.Alloc<PFLeaderboardsLeaderboardColumn>(1);
                Columns[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->Columns = array0;
        }
        target->Created = PlayFabTime.ToUnixTime(Created);
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFLeaderboardsLeaderboardEventEmissionConfig* native4 = arena.Alloc<PFLeaderboardsLeaderboardEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native4, arena);
            target->EventEmissionConfig = native4;
        }
        target->LastResetTime = arena.Value(LastResetTime is null ? null : (long?)PlayFabTime.ToUnixTime(LastResetTime.Value));
        target->Name = arena.String(Name);
        target->SizeLimit = SizeLimit;
        target->Version = Version;
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native9 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native9, arena);
            target->VersionConfiguration = native9;
        }
    }
}

/// <summary>Projects <c>PFLeaderboardsGetLeaderboardForEntitiesRequest</c>.</summary>
public sealed class LeaderboardsGetLeaderboardForEntitiesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EntityIds</c>.</summary>
    public IReadOnlyList<string>? EntityIds { get; set; }

    /// <summary><c>LeaderboardName</c>.</summary>
    public string? LeaderboardName { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint? Version { get; set; }

    internal static unsafe LeaderboardsGetLeaderboardForEntitiesRequest FromNative(PFLeaderboardsGetLeaderboardForEntitiesRequest* source)
    {
        var value = new LeaderboardsGetLeaderboardForEntitiesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        if (source->EntityIds is not null && source->EntityIdsCount != 0)
        {
            var list2 = new List<string>((int)source->EntityIdsCount);
            for (uint i2 = 0; i2 < source->EntityIdsCount; i2++)
            {
                list2.Add(Utf8.ToString(source->EntityIds[i2]) ?? string.Empty);
            }

            value.EntityIds = list2;
        }
        value.LeaderboardName = Utf8.ToString(source->LeaderboardName);
        value.Version = source->Version is null ? null : (uint?)(*source->Version);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsGetLeaderboardForEntitiesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->EntityIdsCount = (uint)(EntityIds is null ? 0 : EntityIds.Count);
        target->EntityIds = arena.StringArray(EntityIds);
        target->LeaderboardName = arena.String(LeaderboardName);
        target->Version = arena.Value(Version);
    }
}

/// <summary>Projects <c>PFLeaderboardsIncrementLeaderboardVersionRequest</c>.</summary>
public sealed class LeaderboardsIncrementLeaderboardVersionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe LeaderboardsIncrementLeaderboardVersionRequest FromNative(PFLeaderboardsIncrementLeaderboardVersionRequest* source)
    {
        var value = new LeaderboardsIncrementLeaderboardVersionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsIncrementLeaderboardVersionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFLeaderboardsIncrementLeaderboardVersionResponse</c>.</summary>
public sealed class LeaderboardsIncrementLeaderboardVersionResponse
{
    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    internal static unsafe LeaderboardsIncrementLeaderboardVersionResponse FromNative(PFLeaderboardsIncrementLeaderboardVersionResponse* source)
    {
        var value = new LeaderboardsIncrementLeaderboardVersionResponse();
        value.Version = source->Version;
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsIncrementLeaderboardVersionResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->Version = Version;
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardColumn</c>.</summary>
public sealed class LeaderboardsLeaderboardColumn
{
    /// <summary><c>LinkedStatisticColumn</c>.</summary>
    public LeaderboardsLinkedStatisticColumn? LinkedStatisticColumn { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>SortDirection</c>.</summary>
    public LeaderboardsLeaderboardSortDirection SortDirection { get; set; }

    internal static unsafe LeaderboardsLeaderboardColumn FromNative(PFLeaderboardsLeaderboardColumn* source)
    {
        var value = new LeaderboardsLeaderboardColumn();
        value.LinkedStatisticColumn = source->LinkedStatisticColumn is null ? null : LeaderboardsLinkedStatisticColumn.FromNative(source->LinkedStatisticColumn);
        value.Name = Utf8.ToString(source->Name);
        value.SortDirection = (LeaderboardsLeaderboardSortDirection)source->SortDirection;
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardColumn* target, PlayFabArena arena)
    {
        *target = default;
        if (LinkedStatisticColumn is not null)
        {
            PFLeaderboardsLinkedStatisticColumn* native0 = arena.Alloc<PFLeaderboardsLinkedStatisticColumn>(1);
            LinkedStatisticColumn.WriteTo(native0, arena);
            target->LinkedStatisticColumn = native0;
        }
        target->Name = arena.String(Name);
        target->SortDirection = (PFLeaderboardsLeaderboardSortDirection)SortDirection;
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardDefinition</c>.</summary>
public sealed class LeaderboardsLeaderboardDefinition
{
    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardColumn>? Columns { get; set; }

    /// <summary><c>Created</c>.</summary>
    public DateTimeOffset Created { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public LeaderboardsLeaderboardEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>LastResetTime</c>.</summary>
    public DateTimeOffset? LastResetTime { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>SizeLimit</c>.</summary>
    public int SizeLimit { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe LeaderboardsLeaderboardDefinition FromNative(PFLeaderboardsLeaderboardDefinition* source)
    {
        var value = new LeaderboardsLeaderboardDefinition();
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list0 = new List<LeaderboardsLeaderboardColumn>((int)source->ColumnsCount);
            for (uint i0 = 0; i0 < source->ColumnsCount; i0++)
            {
                list0.Add(LeaderboardsLeaderboardColumn.FromNative(source->Columns[i0]));
            }

            value.Columns = list0;
        }
        value.Created = PlayFabTime.ToDateTimeOffset(source->Created);
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : LeaderboardsLeaderboardEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.LastResetTime = source->LastResetTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->LastResetTime);
        value.Name = Utf8.ToString(source->Name);
        value.SizeLimit = source->SizeLimit;
        value.Version = source->Version;
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardDefinition* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFLeaderboardsLeaderboardColumn** array0 = arena.PointerArray<PFLeaderboardsLeaderboardColumn>(Columns.Count);
            for (int i0 = 0; i0 < Columns.Count; i0++)
            {
                PFLeaderboardsLeaderboardColumn* item0 = arena.Alloc<PFLeaderboardsLeaderboardColumn>(1);
                Columns[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->Columns = array0;
        }
        target->Created = PlayFabTime.ToUnixTime(Created);
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFLeaderboardsLeaderboardEventEmissionConfig* native4 = arena.Alloc<PFLeaderboardsLeaderboardEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native4, arena);
            target->EventEmissionConfig = native4;
        }
        target->LastResetTime = arena.Value(LastResetTime is null ? null : (long?)PlayFabTime.ToUnixTime(LastResetTime.Value));
        target->Name = arena.String(Name);
        target->SizeLimit = SizeLimit;
        target->Version = Version;
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native9 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native9, arena);
            target->VersionConfiguration = native9;
        }
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardEntityRankOnVersionEndConfig</c>.</summary>
public sealed class LeaderboardsLeaderboardEntityRankOnVersionEndConfig
{
    /// <summary><c>EventType</c>.</summary>
    public EventType EventType { get; set; }

    /// <summary><c>RankLimit</c>.</summary>
    public int RankLimit { get; set; }

    internal static unsafe LeaderboardsLeaderboardEntityRankOnVersionEndConfig FromNative(PFLeaderboardsLeaderboardEntityRankOnVersionEndConfig* source)
    {
        var value = new LeaderboardsLeaderboardEntityRankOnVersionEndConfig();
        value.EventType = (EventType)source->EventType;
        value.RankLimit = source->RankLimit;
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardEntityRankOnVersionEndConfig* target, PlayFabArena arena)
    {
        *target = default;
        target->EventType = (PFEventType)EventType;
        target->RankLimit = RankLimit;
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardEntryUpdate</c>.</summary>
public sealed class LeaderboardsLeaderboardEntryUpdate
{
    /// <summary><c>EntityId</c>.</summary>
    public string? EntityId { get; set; }

    /// <summary><c>Metadata</c>.</summary>
    public string? Metadata { get; set; }

    /// <summary><c>Scores</c>.</summary>
    public IReadOnlyList<string>? Scores { get; set; }

    internal static unsafe LeaderboardsLeaderboardEntryUpdate FromNative(PFLeaderboardsLeaderboardEntryUpdate* source)
    {
        var value = new LeaderboardsLeaderboardEntryUpdate();
        value.EntityId = Utf8.ToString(source->EntityId);
        value.Metadata = Utf8.ToString(source->Metadata);
        if (source->Scores is not null && source->ScoresCount != 0)
        {
            var list2 = new List<string>((int)source->ScoresCount);
            for (uint i2 = 0; i2 < source->ScoresCount; i2++)
            {
                list2.Add(Utf8.ToString(source->Scores[i2]) ?? string.Empty);
            }

            value.Scores = list2;
        }
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardEntryUpdate* target, PlayFabArena arena)
    {
        *target = default;
        target->EntityId = arena.String(EntityId);
        target->Metadata = arena.String(Metadata);
        target->ScoresCount = (uint)(Scores is null ? 0 : Scores.Count);
        target->Scores = arena.StringArray(Scores);
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardEventEmissionConfig</c>.</summary>
public sealed class LeaderboardsLeaderboardEventEmissionConfig
{
    /// <summary><c>EntityRankOnVersionEndConfig</c>.</summary>
    public LeaderboardsLeaderboardEntityRankOnVersionEndConfig? EntityRankOnVersionEndConfig { get; set; }

    /// <summary><c>VersionEndConfig</c>.</summary>
    public LeaderboardsLeaderboardVersionEndConfig? VersionEndConfig { get; set; }

    internal static unsafe LeaderboardsLeaderboardEventEmissionConfig FromNative(PFLeaderboardsLeaderboardEventEmissionConfig* source)
    {
        var value = new LeaderboardsLeaderboardEventEmissionConfig();
        value.EntityRankOnVersionEndConfig = source->EntityRankOnVersionEndConfig is null ? null : LeaderboardsLeaderboardEntityRankOnVersionEndConfig.FromNative(source->EntityRankOnVersionEndConfig);
        value.VersionEndConfig = source->VersionEndConfig is null ? null : LeaderboardsLeaderboardVersionEndConfig.FromNative(source->VersionEndConfig);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardEventEmissionConfig* target, PlayFabArena arena)
    {
        *target = default;
        if (EntityRankOnVersionEndConfig is not null)
        {
            PFLeaderboardsLeaderboardEntityRankOnVersionEndConfig* native0 = arena.Alloc<PFLeaderboardsLeaderboardEntityRankOnVersionEndConfig>(1);
            EntityRankOnVersionEndConfig.WriteTo(native0, arena);
            target->EntityRankOnVersionEndConfig = native0;
        }
        if (VersionEndConfig is not null)
        {
            PFLeaderboardsLeaderboardVersionEndConfig* native1 = arena.Alloc<PFLeaderboardsLeaderboardVersionEndConfig>(1);
            VersionEndConfig.WriteTo(native1, arena);
            target->VersionEndConfig = native1;
        }
    }
}

/// <summary>Projects <c>PFLeaderboardsLeaderboardVersionEndConfig</c>.</summary>
public sealed class LeaderboardsLeaderboardVersionEndConfig
{
    /// <summary><c>EventType</c>.</summary>
    public EventType EventType { get; set; }

    internal static unsafe LeaderboardsLeaderboardVersionEndConfig FromNative(PFLeaderboardsLeaderboardVersionEndConfig* source)
    {
        var value = new LeaderboardsLeaderboardVersionEndConfig();
        value.EventType = (EventType)source->EventType;
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLeaderboardVersionEndConfig* target, PlayFabArena arena)
    {
        *target = default;
        target->EventType = (PFEventType)EventType;
    }
}

/// <summary>Projects <c>PFLeaderboardsLinkedStatisticColumn</c>.</summary>
public sealed class LeaderboardsLinkedStatisticColumn
{
    /// <summary><c>LinkedStatisticColumnName</c>.</summary>
    public string? LinkedStatisticColumnName { get; set; }

    /// <summary><c>LinkedStatisticName</c>.</summary>
    public string? LinkedStatisticName { get; set; }

    internal static unsafe LeaderboardsLinkedStatisticColumn FromNative(PFLeaderboardsLinkedStatisticColumn* source)
    {
        var value = new LeaderboardsLinkedStatisticColumn();
        value.LinkedStatisticColumnName = Utf8.ToString(source->LinkedStatisticColumnName);
        value.LinkedStatisticName = Utf8.ToString(source->LinkedStatisticName);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsLinkedStatisticColumn* target, PlayFabArena arena)
    {
        *target = default;
        target->LinkedStatisticColumnName = arena.String(LinkedStatisticColumnName);
        target->LinkedStatisticName = arena.String(LinkedStatisticName);
    }
}

/// <summary>Projects <c>PFLeaderboardsListLeaderboardDefinitionsRequest</c>.</summary>
public sealed class LeaderboardsListLeaderboardDefinitionsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int? PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe LeaderboardsListLeaderboardDefinitionsRequest FromNative(PFLeaderboardsListLeaderboardDefinitionsRequest* source)
    {
        var value = new LeaderboardsListLeaderboardDefinitionsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.PageSize = source->PageSize is null ? null : (int?)(*source->PageSize);
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsListLeaderboardDefinitionsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->PageSize = arena.Value(PageSize);
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFLeaderboardsListLeaderboardDefinitionsResponse</c>.</summary>
public sealed class LeaderboardsListLeaderboardDefinitionsResponse
{
    /// <summary><c>LeaderboardDefinitions</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardDefinition>? LeaderboardDefinitions { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe LeaderboardsListLeaderboardDefinitionsResponse FromNative(PFLeaderboardsListLeaderboardDefinitionsResponse* source)
    {
        var value = new LeaderboardsListLeaderboardDefinitionsResponse();
        if (source->LeaderboardDefinitions is not null && source->LeaderboardDefinitionsCount != 0)
        {
            var list0 = new List<LeaderboardsLeaderboardDefinition>((int)source->LeaderboardDefinitionsCount);
            for (uint i0 = 0; i0 < source->LeaderboardDefinitionsCount; i0++)
            {
                list0.Add(LeaderboardsLeaderboardDefinition.FromNative(source->LeaderboardDefinitions[i0]));
            }

            value.LeaderboardDefinitions = list0;
        }
        value.PageSize = source->PageSize;
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsListLeaderboardDefinitionsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->LeaderboardDefinitionsCount = (uint)(LeaderboardDefinitions is null ? 0 : LeaderboardDefinitions.Count);
        if (LeaderboardDefinitions is not null && LeaderboardDefinitions.Count > 0)
        {
            PFLeaderboardsLeaderboardDefinition** array0 = arena.PointerArray<PFLeaderboardsLeaderboardDefinition>(LeaderboardDefinitions.Count);
            for (int i0 = 0; i0 < LeaderboardDefinitions.Count; i0++)
            {
                PFLeaderboardsLeaderboardDefinition* item0 = arena.Alloc<PFLeaderboardsLeaderboardDefinition>(1);
                LeaderboardDefinitions[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->LeaderboardDefinitions = array0;
        }
        target->PageSize = PageSize;
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFLeaderboardsUnlinkLeaderboardFromStatisticRequest</c>.</summary>
public sealed class LeaderboardsUnlinkLeaderboardFromStatisticRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>StatisticName</c>.</summary>
    public string? StatisticName { get; set; }

    internal static unsafe LeaderboardsUnlinkLeaderboardFromStatisticRequest FromNative(PFLeaderboardsUnlinkLeaderboardFromStatisticRequest* source)
    {
        var value = new LeaderboardsUnlinkLeaderboardFromStatisticRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        value.StatisticName = Utf8.ToString(source->StatisticName);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsUnlinkLeaderboardFromStatisticRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
        target->StatisticName = arena.String(StatisticName);
    }
}

/// <summary>Projects <c>PFLeaderboardsUpdateLeaderboardDefinitionRequest</c>.</summary>
public sealed class LeaderboardsUpdateLeaderboardDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public LeaderboardsLeaderboardEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>SizeLimit</c>.</summary>
    public int? SizeLimit { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe LeaderboardsUpdateLeaderboardDefinitionRequest FromNative(PFLeaderboardsUpdateLeaderboardDefinitionRequest* source)
    {
        var value = new LeaderboardsUpdateLeaderboardDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : LeaderboardsLeaderboardEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.Name = Utf8.ToString(source->Name);
        value.SizeLimit = source->SizeLimit is null ? null : (int?)(*source->SizeLimit);
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsUpdateLeaderboardDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (EventEmissionConfig is not null)
        {
            PFLeaderboardsLeaderboardEventEmissionConfig* native2 = arena.Alloc<PFLeaderboardsLeaderboardEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native2, arena);
            target->EventEmissionConfig = native2;
        }
        target->Name = arena.String(Name);
        target->SizeLimit = arena.Value(SizeLimit);
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native5 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native5, arena);
            target->VersionConfiguration = native5;
        }
    }
}

/// <summary>Projects <c>PFLeaderboardsUpdateLeaderboardEntriesRequest</c>.</summary>
public sealed class LeaderboardsUpdateLeaderboardEntriesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entries</c>.</summary>
    public IReadOnlyList<LeaderboardsLeaderboardEntryUpdate>? Entries { get; set; }

    /// <summary><c>LeaderboardName</c>.</summary>
    public string? LeaderboardName { get; set; }

    internal static unsafe LeaderboardsUpdateLeaderboardEntriesRequest FromNative(PFLeaderboardsUpdateLeaderboardEntriesRequest* source)
    {
        var value = new LeaderboardsUpdateLeaderboardEntriesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        if (source->Entries is not null && source->EntriesCount != 0)
        {
            var list2 = new List<LeaderboardsLeaderboardEntryUpdate>((int)source->EntriesCount);
            for (uint i2 = 0; i2 < source->EntriesCount; i2++)
            {
                list2.Add(LeaderboardsLeaderboardEntryUpdate.FromNative(source->Entries[i2]));
            }

            value.Entries = list2;
        }
        value.LeaderboardName = Utf8.ToString(source->LeaderboardName);
        return value;
    }

    internal unsafe void WriteTo(PFLeaderboardsUpdateLeaderboardEntriesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->EntriesCount = (uint)(Entries is null ? 0 : Entries.Count);
        if (Entries is not null && Entries.Count > 0)
        {
            PFLeaderboardsLeaderboardEntryUpdate** array2 = arena.PointerArray<PFLeaderboardsLeaderboardEntryUpdate>(Entries.Count);
            for (int i2 = 0; i2 < Entries.Count; i2++)
            {
                PFLeaderboardsLeaderboardEntryUpdate* item2 = arena.Alloc<PFLeaderboardsLeaderboardEntryUpdate>(1);
                Entries[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->Entries = array2;
        }
        target->LeaderboardName = arena.String(LeaderboardName);
    }
}
