// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFLocalization
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFLocalizationGetLanguageListRequest</c>.</summary>
public sealed class LocalizationGetLanguageListRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    internal static unsafe LocalizationGetLanguageListRequest FromNative(PFLocalizationGetLanguageListRequest* source)
    {
        var value = new LocalizationGetLanguageListRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        return value;
    }

    internal unsafe void WriteTo(PFLocalizationGetLanguageListRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
    }
}

/// <summary>Projects <c>PFLocalizationGetLanguageListResponse</c>.</summary>
public sealed class LocalizationGetLanguageListResponse
{
    /// <summary><c>LanguageList</c>.</summary>
    public IReadOnlyList<string>? LanguageList { get; set; }

    internal static unsafe LocalizationGetLanguageListResponse FromNative(PFLocalizationGetLanguageListResponse* source)
    {
        var value = new LocalizationGetLanguageListResponse();
        if (source->LanguageList is not null && source->LanguageListCount != 0)
        {
            var list0 = new List<string>((int)source->LanguageListCount);
            for (uint i0 = 0; i0 < source->LanguageListCount; i0++)
            {
                list0.Add(Utf8.ToString(source->LanguageList[i0]) ?? string.Empty);
            }

            value.LanguageList = list0;
        }
        return value;
    }

    internal unsafe void WriteTo(PFLocalizationGetLanguageListResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->LanguageListCount = (uint)(LanguageList is null ? 0 : LanguageList.Count);
        target->LanguageList = arena.StringArray(LanguageList);
    }
}
