// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFMultiplayerServer
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFMultiplayerServerProtocolType</c>.</summary>
public enum MultiplayerServerProtocolType : uint
{
    /// <summary>Projects <c>PFMultiplayerServerProtocolType::TCP</c>.</summary>
    Tcp = 0,
    /// <summary>Projects <c>PFMultiplayerServerProtocolType::UDP</c>.</summary>
    Udp = 1,
}

/// <summary>Projects <c>PFMultiplayerServerAzureVmSize</c>.</summary>
public enum MultiplayerServerAzureVmSize : uint
{
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A1</c>.</summary>
    StandardA1 = 0,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A2</c>.</summary>
    StandardA2 = 1,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A3</c>.</summary>
    StandardA3 = 2,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A4</c>.</summary>
    StandardA4 = 3,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A1_v2</c>.</summary>
    StandardA1V2 = 4,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A2_v2</c>.</summary>
    StandardA2V2 = 5,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A4_v2</c>.</summary>
    StandardA4V2 = 6,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_A8_v2</c>.</summary>
    StandardA8V2 = 7,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D1_v2</c>.</summary>
    StandardD1V2 = 8,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2_v2</c>.</summary>
    StandardD2V2 = 9,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D3_v2</c>.</summary>
    StandardD3V2 = 10,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4_v2</c>.</summary>
    StandardD4V2 = 11,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D5_v2</c>.</summary>
    StandardD5V2 = 12,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2_v3</c>.</summary>
    StandardD2V3 = 13,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4_v3</c>.</summary>
    StandardD4V3 = 14,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8_v3</c>.</summary>
    StandardD8V3 = 15,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16_v3</c>.</summary>
    StandardD16V3 = 16,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F1</c>.</summary>
    StandardF1 = 17,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F2</c>.</summary>
    StandardF2 = 18,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F4</c>.</summary>
    StandardF4 = 19,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F8</c>.</summary>
    StandardF8 = 20,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F16</c>.</summary>
    StandardF16 = 21,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F2s_v2</c>.</summary>
    StandardF2sV2 = 22,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F4s_v2</c>.</summary>
    StandardF4sV2 = 23,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F8s_v2</c>.</summary>
    StandardF8sV2 = 24,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_F16s_v2</c>.</summary>
    StandardF16sV2 = 25,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2as_v4</c>.</summary>
    StandardD2asV4 = 26,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4as_v4</c>.</summary>
    StandardD4asV4 = 27,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8as_v4</c>.</summary>
    StandardD8asV4 = 28,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16as_v4</c>.</summary>
    StandardD16asV4 = 29,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2a_v4</c>.</summary>
    StandardD2aV4 = 30,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4a_v4</c>.</summary>
    StandardD4aV4 = 31,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8a_v4</c>.</summary>
    StandardD8aV4 = 32,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16a_v4</c>.</summary>
    StandardD16aV4 = 33,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2ads_v5</c>.</summary>
    StandardD2adsV5 = 34,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4ads_v5</c>.</summary>
    StandardD4adsV5 = 35,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8ads_v5</c>.</summary>
    StandardD8adsV5 = 36,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16ads_v5</c>.</summary>
    StandardD16adsV5 = 37,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2ads_v6</c>.</summary>
    StandardD2adsV6 = 38,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4ads_v6</c>.</summary>
    StandardD4adsV6 = 39,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8ads_v6</c>.</summary>
    StandardD8adsV6 = 40,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16ads_v6</c>.</summary>
    StandardD16adsV6 = 41,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E2a_v4</c>.</summary>
    StandardE2aV4 = 42,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E4a_v4</c>.</summary>
    StandardE4aV4 = 43,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E8a_v4</c>.</summary>
    StandardE8aV4 = 44,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E16a_v4</c>.</summary>
    StandardE16aV4 = 45,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E2as_v4</c>.</summary>
    StandardE2asV4 = 46,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E4as_v4</c>.</summary>
    StandardE4asV4 = 47,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E8as_v4</c>.</summary>
    StandardE8asV4 = 48,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_E16as_v4</c>.</summary>
    StandardE16asV4 = 49,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2s_v3</c>.</summary>
    StandardD2sV3 = 50,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4s_v3</c>.</summary>
    StandardD4sV3 = 51,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8s_v3</c>.</summary>
    StandardD8sV3 = 52,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16s_v3</c>.</summary>
    StandardD16sV3 = 53,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_DS1_v2</c>.</summary>
    StandardDs1V2 = 54,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_DS2_v2</c>.</summary>
    StandardDs2V2 = 55,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_DS3_v2</c>.</summary>
    StandardDs3V2 = 56,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_DS4_v2</c>.</summary>
    StandardDs4V2 = 57,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_DS5_v2</c>.</summary>
    StandardDs5V2 = 58,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_NC4as_T4_v3</c>.</summary>
    StandardNc4asT4V3 = 59,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2d_v4</c>.</summary>
    StandardD2dV4 = 60,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4d_v4</c>.</summary>
    StandardD4dV4 = 61,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8d_v4</c>.</summary>
    StandardD8dV4 = 62,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16d_v4</c>.</summary>
    StandardD16dV4 = 63,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2ds_v4</c>.</summary>
    StandardD2dsV4 = 64,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4ds_v4</c>.</summary>
    StandardD4dsV4 = 65,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8ds_v4</c>.</summary>
    StandardD8dsV4 = 66,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16ds_v4</c>.</summary>
    StandardD16dsV4 = 67,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_HB120_16rs_v3</c>.</summary>
    StandardHb12016rsV3 = 68,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_HB120_32rs_v3</c>.</summary>
    StandardHb12032rsV3 = 69,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_HB120_64rs_v3</c>.</summary>
    StandardHb12064rsV3 = 70,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_HB120_96rs_v3</c>.</summary>
    StandardHb12096rsV3 = 71,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_HB120rs_v3</c>.</summary>
    StandardHb120rsV3 = 72,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2d_v5</c>.</summary>
    StandardD2dV5 = 73,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4d_v5</c>.</summary>
    StandardD4dV5 = 74,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8d_v5</c>.</summary>
    StandardD8dV5 = 75,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16d_v5</c>.</summary>
    StandardD16dV5 = 76,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D32d_v5</c>.</summary>
    StandardD32dV5 = 77,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2ds_v5</c>.</summary>
    StandardD2dsV5 = 78,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4ds_v5</c>.</summary>
    StandardD4dsV5 = 79,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8ds_v5</c>.</summary>
    StandardD8dsV5 = 80,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16ds_v5</c>.</summary>
    StandardD16dsV5 = 81,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D32ds_v5</c>.</summary>
    StandardD32dsV5 = 82,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D2ds_v6</c>.</summary>
    StandardD2dsV6 = 83,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D4ds_v6</c>.</summary>
    StandardD4dsV6 = 84,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D8ds_v6</c>.</summary>
    StandardD8dsV6 = 85,
    /// <summary>Projects <c>PFMultiplayerServerAzureVmSize::Standard_D16ds_v6</c>.</summary>
    StandardD16dsV6 = 86,
}

/// <summary>Projects <c>PFMultiplayerServerBuildAliasDetailsResponse</c>.</summary>
public sealed class MultiplayerServerBuildAliasDetailsResponse
{
    /// <summary><c>AliasId</c>.</summary>
    public string? AliasId { get; set; }

    /// <summary><c>AliasName</c>.</summary>
    public string? AliasName { get; set; }

    /// <summary><c>BuildSelectionCriteria</c>.</summary>
    public IReadOnlyList<MultiplayerServerBuildSelectionCriterion>? BuildSelectionCriteria { get; set; }

    internal static unsafe MultiplayerServerBuildAliasDetailsResponse FromNative(PFMultiplayerServerBuildAliasDetailsResponse* source)
    {
        var value = new MultiplayerServerBuildAliasDetailsResponse();
        value.AliasId = Utf8.ToString(source->AliasId);
        value.AliasName = Utf8.ToString(source->AliasName);
        if (source->BuildSelectionCriteria is not null && source->BuildSelectionCriteriaCount != 0)
        {
            var list2 = new List<MultiplayerServerBuildSelectionCriterion>((int)source->BuildSelectionCriteriaCount);
            for (uint i2 = 0; i2 < source->BuildSelectionCriteriaCount; i2++)
            {
                list2.Add(MultiplayerServerBuildSelectionCriterion.FromNative(source->BuildSelectionCriteria[i2]));
            }

            value.BuildSelectionCriteria = list2;
        }
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerBuildAliasDetailsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->AliasId = arena.String(AliasId);
        target->AliasName = arena.String(AliasName);
        target->BuildSelectionCriteriaCount = (uint)(BuildSelectionCriteria is null ? 0 : BuildSelectionCriteria.Count);
        if (BuildSelectionCriteria is not null && BuildSelectionCriteria.Count > 0)
        {
            PFMultiplayerServerBuildSelectionCriterion** array2 = arena.PointerArray<PFMultiplayerServerBuildSelectionCriterion>(BuildSelectionCriteria.Count);
            for (int i2 = 0; i2 < BuildSelectionCriteria.Count; i2++)
            {
                PFMultiplayerServerBuildSelectionCriterion* item2 = arena.Alloc<PFMultiplayerServerBuildSelectionCriterion>(1);
                BuildSelectionCriteria[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->BuildSelectionCriteria = array2;
        }
    }
}

/// <summary>Projects <c>PFMultiplayerServerBuildAliasParams</c>.</summary>
public sealed class MultiplayerServerBuildAliasParams
{
    /// <summary><c>AliasId</c>.</summary>
    public string? AliasId { get; set; }

    internal static unsafe MultiplayerServerBuildAliasParams FromNative(PFMultiplayerServerBuildAliasParams* source)
    {
        var value = new MultiplayerServerBuildAliasParams();
        value.AliasId = Utf8.ToString(source->AliasId);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerBuildAliasParams* target, PlayFabArena arena)
    {
        *target = default;
        target->AliasId = arena.String(AliasId);
    }
}

/// <summary>Projects <c>PFMultiplayerServerBuildRegion</c>.</summary>
public sealed class MultiplayerServerBuildRegion
{
    /// <summary><c>CurrentServerStats</c>.</summary>
    public MultiplayerServerCurrentServerStats? CurrentServerStats { get; set; }

    /// <summary><c>DynamicStandbySettings</c>.</summary>
    public MultiplayerServerDynamicStandbySettings? DynamicStandbySettings { get; set; }

    /// <summary><c>IsAssetReplicationComplete</c>.</summary>
    public bool IsAssetReplicationComplete { get; set; }

    /// <summary><c>MaxServers</c>.</summary>
    public int MaxServers { get; set; }

    /// <summary><c>MultiplayerServerCountPerVm</c>.</summary>
    public int? MultiplayerServerCountPerVm { get; set; }

    /// <summary><c>Region</c>.</summary>
    public string? Region { get; set; }

    /// <summary><c>ScheduledStandbySettings</c>.</summary>
    public MultiplayerServerScheduledStandbySettings? ScheduledStandbySettings { get; set; }

    /// <summary><c>StandbyServers</c>.</summary>
    public int StandbyServers { get; set; }

    /// <summary><c>Status</c>.</summary>
    public string? Status { get; set; }

    /// <summary><c>VmSize</c>.</summary>
    public MultiplayerServerAzureVmSize? VmSize { get; set; }

    internal static unsafe MultiplayerServerBuildRegion FromNative(PFMultiplayerServerBuildRegion* source)
    {
        var value = new MultiplayerServerBuildRegion();
        value.CurrentServerStats = source->CurrentServerStats is null ? null : MultiplayerServerCurrentServerStats.FromNative(source->CurrentServerStats);
        value.DynamicStandbySettings = source->DynamicStandbySettings is null ? null : MultiplayerServerDynamicStandbySettings.FromNative(source->DynamicStandbySettings);
        value.IsAssetReplicationComplete = source->IsAssetReplicationComplete != 0;
        value.MaxServers = source->MaxServers;
        value.MultiplayerServerCountPerVm = source->MultiplayerServerCountPerVm is null ? null : (int?)(*source->MultiplayerServerCountPerVm);
        value.Region = Utf8.ToString(source->Region);
        value.ScheduledStandbySettings = source->ScheduledStandbySettings is null ? null : MultiplayerServerScheduledStandbySettings.FromNative(source->ScheduledStandbySettings);
        value.StandbyServers = source->StandbyServers;
        value.Status = Utf8.ToString(source->Status);
        value.VmSize = source->VmSize is null ? null : (MultiplayerServerAzureVmSize?)(*source->VmSize);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerBuildRegion* target, PlayFabArena arena)
    {
        *target = default;
        if (CurrentServerStats is not null)
        {
            PFMultiplayerServerCurrentServerStats* native0 = arena.Alloc<PFMultiplayerServerCurrentServerStats>(1);
            CurrentServerStats.WriteTo(native0, arena);
            target->CurrentServerStats = native0;
        }
        if (DynamicStandbySettings is not null)
        {
            PFMultiplayerServerDynamicStandbySettings* native1 = arena.Alloc<PFMultiplayerServerDynamicStandbySettings>(1);
            DynamicStandbySettings.WriteTo(native1, arena);
            target->DynamicStandbySettings = native1;
        }
        target->IsAssetReplicationComplete = IsAssetReplicationComplete ? (byte)1 : (byte)0;
        target->MaxServers = MaxServers;
        target->MultiplayerServerCountPerVm = arena.Value(MultiplayerServerCountPerVm);
        target->Region = arena.String(Region);
        if (ScheduledStandbySettings is not null)
        {
            PFMultiplayerServerScheduledStandbySettings* native6 = arena.Alloc<PFMultiplayerServerScheduledStandbySettings>(1);
            ScheduledStandbySettings.WriteTo(native6, arena);
            target->ScheduledStandbySettings = native6;
        }
        target->StandbyServers = StandbyServers;
        target->Status = arena.String(Status);
        target->VmSize = arena.Value((PFMultiplayerServerAzureVmSize?)VmSize);
    }
}

/// <summary>Projects <c>PFMultiplayerServerBuildSelectionCriterion</c>.</summary>
public sealed class MultiplayerServerBuildSelectionCriterion
{
    /// <summary><c>BuildWeightDistribution</c>.</summary>
    public IReadOnlyDictionary<string, uint>? BuildWeightDistribution { get; set; }

    internal static unsafe MultiplayerServerBuildSelectionCriterion FromNative(PFMultiplayerServerBuildSelectionCriterion* source)
    {
        var value = new MultiplayerServerBuildSelectionCriterion();
        if (source->BuildWeightDistribution is not null && source->BuildWeightDistributionCount != 0)
        {
            var map0 = new Dictionary<string, uint>((int)source->BuildWeightDistributionCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->BuildWeightDistributionCount; i0++)
            {
                map0[Utf8.ToString(source->BuildWeightDistribution[i0].Key) ?? string.Empty] = source->BuildWeightDistribution[i0].Value;
            }

            value.BuildWeightDistribution = map0;
        }
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerBuildSelectionCriterion* target, PlayFabArena arena)
    {
        *target = default;
        target->BuildWeightDistributionCount = (uint)(BuildWeightDistribution is null ? 0 : BuildWeightDistribution.Count);
        if (BuildWeightDistribution is not null && BuildWeightDistribution.Count > 0)
        {
            PFUint32DictionaryEntry* entries0 = arena.Alloc<PFUint32DictionaryEntry>(BuildWeightDistribution.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, uint> pair0 in BuildWeightDistribution)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = pair0.Value;
                next0++;
            }

            target->BuildWeightDistribution = entries0;
        }
    }
}

/// <summary>Projects <c>PFMultiplayerServerBuildSummary</c>.</summary>
public sealed class MultiplayerServerBuildSummary
{
    /// <summary><c>BuildId</c>.</summary>
    public string? BuildId { get; set; }

    /// <summary><c>BuildName</c>.</summary>
    public string? BuildName { get; set; }

    /// <summary><c>CreationTime</c>.</summary>
    public DateTimeOffset? CreationTime { get; set; }

    /// <summary><c>Metadata</c>.</summary>
    public IReadOnlyDictionary<string, string>? Metadata { get; set; }

    /// <summary><c>RegionConfigurations</c>.</summary>
    public IReadOnlyList<MultiplayerServerBuildRegion>? RegionConfigurations { get; set; }

    internal static unsafe MultiplayerServerBuildSummary FromNative(PFMultiplayerServerBuildSummary* source)
    {
        var value = new MultiplayerServerBuildSummary();
        value.BuildId = Utf8.ToString(source->BuildId);
        value.BuildName = Utf8.ToString(source->BuildName);
        value.CreationTime = source->CreationTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->CreationTime);
        if (source->Metadata is not null && source->MetadataCount != 0)
        {
            var map3 = new Dictionary<string, string>((int)source->MetadataCount, StringComparer.Ordinal);
            for (uint i3 = 0; i3 < source->MetadataCount; i3++)
            {
                map3[Utf8.ToString(source->Metadata[i3].Key) ?? string.Empty] = Utf8.ToString(source->Metadata[i3].Value) ?? string.Empty;
            }

            value.Metadata = map3;
        }
        if (source->RegionConfigurations is not null && source->RegionConfigurationsCount != 0)
        {
            var list5 = new List<MultiplayerServerBuildRegion>((int)source->RegionConfigurationsCount);
            for (uint i5 = 0; i5 < source->RegionConfigurationsCount; i5++)
            {
                list5.Add(MultiplayerServerBuildRegion.FromNative(source->RegionConfigurations[i5]));
            }

            value.RegionConfigurations = list5;
        }
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerBuildSummary* target, PlayFabArena arena)
    {
        *target = default;
        target->BuildId = arena.String(BuildId);
        target->BuildName = arena.String(BuildName);
        target->CreationTime = arena.Value(CreationTime is null ? null : (long?)PlayFabTime.ToUnixTime(CreationTime.Value));
        target->MetadataCount = (uint)(Metadata is null ? 0 : Metadata.Count);
        if (Metadata is not null && Metadata.Count > 0)
        {
            PFStringDictionaryEntry* entries3 = arena.Alloc<PFStringDictionaryEntry>(Metadata.Count);
            int next3 = 0;
            foreach (KeyValuePair<string, string> pair3 in Metadata)
            {
                entries3[next3].Key = arena.String(pair3.Key);
                entries3[next3].Value = arena.String(pair3.Value);
                next3++;
            }

            target->Metadata = entries3;
        }
        target->RegionConfigurationsCount = (uint)(RegionConfigurations is null ? 0 : RegionConfigurations.Count);
        if (RegionConfigurations is not null && RegionConfigurations.Count > 0)
        {
            PFMultiplayerServerBuildRegion** array5 = arena.PointerArray<PFMultiplayerServerBuildRegion>(RegionConfigurations.Count);
            for (int i5 = 0; i5 < RegionConfigurations.Count; i5++)
            {
                PFMultiplayerServerBuildRegion* item5 = arena.Alloc<PFMultiplayerServerBuildRegion>(1);
                RegionConfigurations[i5].WriteTo(item5, arena);
                array5[i5] = item5;
            }

            target->RegionConfigurations = array5;
        }
    }
}

/// <summary>Projects <c>PFMultiplayerServerConnectedPlayer</c>.</summary>
public sealed class MultiplayerServerConnectedPlayer
{
    /// <summary><c>PlayerId</c>.</summary>
    public string? PlayerId { get; set; }

    internal static unsafe MultiplayerServerConnectedPlayer FromNative(PFMultiplayerServerConnectedPlayer* source)
    {
        var value = new MultiplayerServerConnectedPlayer();
        value.PlayerId = Utf8.ToString(source->PlayerId);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerConnectedPlayer* target, PlayFabArena arena)
    {
        *target = default;
        target->PlayerId = arena.String(PlayerId);
    }
}

/// <summary>Projects <c>PFMultiplayerServerCurrentServerStats</c>.</summary>
public sealed class MultiplayerServerCurrentServerStats
{
    /// <summary><c>Active</c>.</summary>
    public int Active { get; set; }

    /// <summary><c>Propping</c>.</summary>
    public int Propping { get; set; }

    /// <summary><c>StandingBy</c>.</summary>
    public int StandingBy { get; set; }

    /// <summary><c>Total</c>.</summary>
    public int Total { get; set; }

    internal static unsafe MultiplayerServerCurrentServerStats FromNative(PFMultiplayerServerCurrentServerStats* source)
    {
        var value = new MultiplayerServerCurrentServerStats();
        value.Active = source->Active;
        value.Propping = source->Propping;
        value.StandingBy = source->StandingBy;
        value.Total = source->Total;
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerCurrentServerStats* target, PlayFabArena arena)
    {
        *target = default;
        target->Active = Active;
        target->Propping = Propping;
        target->StandingBy = StandingBy;
        target->Total = Total;
    }
}

/// <summary>Projects <c>PFMultiplayerServerDynamicStandbySettings</c>.</summary>
public sealed class MultiplayerServerDynamicStandbySettings
{
    /// <summary><c>DynamicFloorMultiplierThresholds</c>.</summary>
    public IReadOnlyList<MultiplayerServerDynamicStandbyThreshold>? DynamicFloorMultiplierThresholds { get; set; }

    /// <summary><c>IsEnabled</c>.</summary>
    public bool IsEnabled { get; set; }

    /// <summary><c>RampDownSeconds</c>.</summary>
    public int? RampDownSeconds { get; set; }

    internal static unsafe MultiplayerServerDynamicStandbySettings FromNative(PFMultiplayerServerDynamicStandbySettings* source)
    {
        var value = new MultiplayerServerDynamicStandbySettings();
        if (source->DynamicFloorMultiplierThresholds is not null && source->DynamicFloorMultiplierThresholdsCount != 0)
        {
            var list0 = new List<MultiplayerServerDynamicStandbyThreshold>((int)source->DynamicFloorMultiplierThresholdsCount);
            for (uint i0 = 0; i0 < source->DynamicFloorMultiplierThresholdsCount; i0++)
            {
                list0.Add(MultiplayerServerDynamicStandbyThreshold.FromNative(source->DynamicFloorMultiplierThresholds[i0]));
            }

            value.DynamicFloorMultiplierThresholds = list0;
        }
        value.IsEnabled = source->IsEnabled != 0;
        value.RampDownSeconds = source->RampDownSeconds is null ? null : (int?)(*source->RampDownSeconds);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerDynamicStandbySettings* target, PlayFabArena arena)
    {
        *target = default;
        target->DynamicFloorMultiplierThresholdsCount = (uint)(DynamicFloorMultiplierThresholds is null ? 0 : DynamicFloorMultiplierThresholds.Count);
        if (DynamicFloorMultiplierThresholds is not null && DynamicFloorMultiplierThresholds.Count > 0)
        {
            PFMultiplayerServerDynamicStandbyThreshold** array0 = arena.PointerArray<PFMultiplayerServerDynamicStandbyThreshold>(DynamicFloorMultiplierThresholds.Count);
            for (int i0 = 0; i0 < DynamicFloorMultiplierThresholds.Count; i0++)
            {
                PFMultiplayerServerDynamicStandbyThreshold* item0 = arena.Alloc<PFMultiplayerServerDynamicStandbyThreshold>(1);
                DynamicFloorMultiplierThresholds[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->DynamicFloorMultiplierThresholds = array0;
        }
        target->IsEnabled = IsEnabled ? (byte)1 : (byte)0;
        target->RampDownSeconds = arena.Value(RampDownSeconds);
    }
}

/// <summary>Projects <c>PFMultiplayerServerDynamicStandbyThreshold</c>.</summary>
public sealed class MultiplayerServerDynamicStandbyThreshold
{
    /// <summary><c>Multiplier</c>.</summary>
    public double Multiplier { get; set; }

    /// <summary><c>TriggerThresholdPercentage</c>.</summary>
    public double TriggerThresholdPercentage { get; set; }

    internal static unsafe MultiplayerServerDynamicStandbyThreshold FromNative(PFMultiplayerServerDynamicStandbyThreshold* source)
    {
        var value = new MultiplayerServerDynamicStandbyThreshold();
        value.Multiplier = source->Multiplier;
        value.TriggerThresholdPercentage = source->TriggerThresholdPercentage;
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerDynamicStandbyThreshold* target, PlayFabArena arena)
    {
        *target = default;
        target->Multiplier = Multiplier;
        target->TriggerThresholdPercentage = TriggerThresholdPercentage;
    }
}

/// <summary>Projects <c>PFMultiplayerServerListBuildAliasesRequest</c>.</summary>
public sealed class MultiplayerServerListBuildAliasesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int? PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe MultiplayerServerListBuildAliasesRequest FromNative(PFMultiplayerServerListBuildAliasesRequest* source)
    {
        var value = new MultiplayerServerListBuildAliasesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.PageSize = source->PageSize is null ? null : (int?)(*source->PageSize);
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListBuildAliasesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->PageSize = arena.Value(PageSize);
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFMultiplayerServerListBuildAliasesResponse</c>.</summary>
public sealed class MultiplayerServerListBuildAliasesResponse
{
    /// <summary><c>BuildAliases</c>.</summary>
    public IReadOnlyList<MultiplayerServerBuildAliasDetailsResponse>? BuildAliases { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe MultiplayerServerListBuildAliasesResponse FromNative(PFMultiplayerServerListBuildAliasesResponse* source)
    {
        var value = new MultiplayerServerListBuildAliasesResponse();
        if (source->BuildAliases is not null && source->BuildAliasesCount != 0)
        {
            var list0 = new List<MultiplayerServerBuildAliasDetailsResponse>((int)source->BuildAliasesCount);
            for (uint i0 = 0; i0 < source->BuildAliasesCount; i0++)
            {
                list0.Add(MultiplayerServerBuildAliasDetailsResponse.FromNative(source->BuildAliases[i0]));
            }

            value.BuildAliases = list0;
        }
        value.PageSize = source->PageSize;
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListBuildAliasesResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->BuildAliasesCount = (uint)(BuildAliases is null ? 0 : BuildAliases.Count);
        if (BuildAliases is not null && BuildAliases.Count > 0)
        {
            PFMultiplayerServerBuildAliasDetailsResponse** array0 = arena.PointerArray<PFMultiplayerServerBuildAliasDetailsResponse>(BuildAliases.Count);
            for (int i0 = 0; i0 < BuildAliases.Count; i0++)
            {
                PFMultiplayerServerBuildAliasDetailsResponse* item0 = arena.Alloc<PFMultiplayerServerBuildAliasDetailsResponse>(1);
                BuildAliases[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->BuildAliases = array0;
        }
        target->PageSize = PageSize;
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFMultiplayerServerListBuildSummariesRequest</c>.</summary>
public sealed class MultiplayerServerListBuildSummariesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int? PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe MultiplayerServerListBuildSummariesRequest FromNative(PFMultiplayerServerListBuildSummariesRequest* source)
    {
        var value = new MultiplayerServerListBuildSummariesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.PageSize = source->PageSize is null ? null : (int?)(*source->PageSize);
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListBuildSummariesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->PageSize = arena.Value(PageSize);
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFMultiplayerServerListBuildSummariesResponse</c>.</summary>
public sealed class MultiplayerServerListBuildSummariesResponse
{
    /// <summary><c>BuildSummaries</c>.</summary>
    public IReadOnlyList<MultiplayerServerBuildSummary>? BuildSummaries { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe MultiplayerServerListBuildSummariesResponse FromNative(PFMultiplayerServerListBuildSummariesResponse* source)
    {
        var value = new MultiplayerServerListBuildSummariesResponse();
        if (source->BuildSummaries is not null && source->BuildSummariesCount != 0)
        {
            var list0 = new List<MultiplayerServerBuildSummary>((int)source->BuildSummariesCount);
            for (uint i0 = 0; i0 < source->BuildSummariesCount; i0++)
            {
                list0.Add(MultiplayerServerBuildSummary.FromNative(source->BuildSummaries[i0]));
            }

            value.BuildSummaries = list0;
        }
        value.PageSize = source->PageSize;
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListBuildSummariesResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->BuildSummariesCount = (uint)(BuildSummaries is null ? 0 : BuildSummaries.Count);
        if (BuildSummaries is not null && BuildSummaries.Count > 0)
        {
            PFMultiplayerServerBuildSummary** array0 = arena.PointerArray<PFMultiplayerServerBuildSummary>(BuildSummaries.Count);
            for (int i0 = 0; i0 < BuildSummaries.Count; i0++)
            {
                PFMultiplayerServerBuildSummary* item0 = arena.Alloc<PFMultiplayerServerBuildSummary>(1);
                BuildSummaries[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->BuildSummaries = array0;
        }
        target->PageSize = PageSize;
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFMultiplayerServerListQosServersForTitleRequest</c>.</summary>
public sealed class MultiplayerServerListQosServersForTitleRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>IncludeAllRegions</c>.</summary>
    public bool? IncludeAllRegions { get; set; }

    /// <summary><c>RoutingPreference</c>.</summary>
    public string? RoutingPreference { get; set; }

    internal static unsafe MultiplayerServerListQosServersForTitleRequest FromNative(PFMultiplayerServerListQosServersForTitleRequest* source)
    {
        var value = new MultiplayerServerListQosServersForTitleRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.IncludeAllRegions = source->IncludeAllRegions is null ? null : (bool?)(*source->IncludeAllRegions != 0);
        value.RoutingPreference = Utf8.ToString(source->RoutingPreference);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListQosServersForTitleRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->IncludeAllRegions = arena.Value(IncludeAllRegions is null ? null : (IncludeAllRegions.Value ? (byte?)1 : (byte?)0));
        target->RoutingPreference = arena.String(RoutingPreference);
    }
}

/// <summary>Projects <c>PFMultiplayerServerListQosServersForTitleResponse</c>.</summary>
public sealed class MultiplayerServerListQosServersForTitleResponse
{
    /// <summary><c>PageSize</c>.</summary>
    public int PageSize { get; set; }

    /// <summary><c>QosServers</c>.</summary>
    public IReadOnlyList<MultiplayerServerQosServer>? QosServers { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe MultiplayerServerListQosServersForTitleResponse FromNative(PFMultiplayerServerListQosServersForTitleResponse* source)
    {
        var value = new MultiplayerServerListQosServersForTitleResponse();
        value.PageSize = source->PageSize;
        if (source->QosServers is not null && source->QosServersCount != 0)
        {
            var list1 = new List<MultiplayerServerQosServer>((int)source->QosServersCount);
            for (uint i1 = 0; i1 < source->QosServersCount; i1++)
            {
                list1.Add(MultiplayerServerQosServer.FromNative(source->QosServers[i1]));
            }

            value.QosServers = list1;
        }
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerListQosServersForTitleResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->PageSize = PageSize;
        target->QosServersCount = (uint)(QosServers is null ? 0 : QosServers.Count);
        if (QosServers is not null && QosServers.Count > 0)
        {
            PFMultiplayerServerQosServer** array1 = arena.PointerArray<PFMultiplayerServerQosServer>(QosServers.Count);
            for (int i1 = 0; i1 < QosServers.Count; i1++)
            {
                PFMultiplayerServerQosServer* item1 = arena.Alloc<PFMultiplayerServerQosServer>(1);
                QosServers[i1].WriteTo(item1, arena);
                array1[i1] = item1;
            }

            target->QosServers = array1;
        }
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFMultiplayerServerPort</c>.</summary>
public sealed class MultiplayerServerPort
{
    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>Num</c>.</summary>
    public int Num { get; set; }

    /// <summary><c>Protocol</c>.</summary>
    public MultiplayerServerProtocolType Protocol { get; set; }

    internal static unsafe MultiplayerServerPort FromNative(PFMultiplayerServerPort* source)
    {
        var value = new MultiplayerServerPort();
        value.Name = Utf8.ToString(source->Name);
        value.Num = source->Num;
        value.Protocol = (MultiplayerServerProtocolType)source->Protocol;
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerPort* target, PlayFabArena arena)
    {
        *target = default;
        target->Name = arena.String(Name);
        target->Num = Num;
        target->Protocol = (PFMultiplayerServerProtocolType)Protocol;
    }
}

/// <summary>Projects <c>PFMultiplayerServerPublicIpAddress</c>.</summary>
public sealed class MultiplayerServerPublicIpAddress
{
    /// <summary><c>FQDN</c>.</summary>
    public string? FQDN { get; set; }

    /// <summary><c>IpAddress</c>.</summary>
    public string? IpAddress { get; set; }

    /// <summary><c>RoutingType</c>.</summary>
    public string? RoutingType { get; set; }

    internal static unsafe MultiplayerServerPublicIpAddress FromNative(PFMultiplayerServerPublicIpAddress* source)
    {
        var value = new MultiplayerServerPublicIpAddress();
        value.FQDN = Utf8.ToString(source->FQDN);
        value.IpAddress = Utf8.ToString(source->IpAddress);
        value.RoutingType = Utf8.ToString(source->RoutingType);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerPublicIpAddress* target, PlayFabArena arena)
    {
        *target = default;
        target->FQDN = arena.String(FQDN);
        target->IpAddress = arena.String(IpAddress);
        target->RoutingType = arena.String(RoutingType);
    }
}

/// <summary>Projects <c>PFMultiplayerServerQosServer</c>.</summary>
public sealed class MultiplayerServerQosServer
{
    /// <summary><c>Region</c>.</summary>
    public string? Region { get; set; }

    /// <summary><c>ServerUrl</c>.</summary>
    public string? ServerUrl { get; set; }

    internal static unsafe MultiplayerServerQosServer FromNative(PFMultiplayerServerQosServer* source)
    {
        var value = new MultiplayerServerQosServer();
        value.Region = Utf8.ToString(source->Region);
        value.ServerUrl = Utf8.ToString(source->ServerUrl);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerQosServer* target, PlayFabArena arena)
    {
        *target = default;
        target->Region = arena.String(Region);
        target->ServerUrl = arena.String(ServerUrl);
    }
}

/// <summary>Projects <c>PFMultiplayerServerRequestMultiplayerServerRequest</c>.</summary>
public sealed class MultiplayerServerRequestMultiplayerServerRequest
{
    /// <summary><c>BuildAliasParams</c>.</summary>
    public MultiplayerServerBuildAliasParams? BuildAliasParams { get; set; }

    /// <summary><c>BuildId</c>.</summary>
    public string? BuildId { get; set; }

    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>InitialPlayers</c>.</summary>
    public IReadOnlyList<string>? InitialPlayers { get; set; }

    /// <summary><c>PreferredRegions</c>.</summary>
    public IReadOnlyList<string>? PreferredRegions { get; set; }

    /// <summary><c>SessionCookie</c>.</summary>
    public string? SessionCookie { get; set; }

    /// <summary><c>SessionId</c>.</summary>
    public string? SessionId { get; set; }

    internal static unsafe MultiplayerServerRequestMultiplayerServerRequest FromNative(PFMultiplayerServerRequestMultiplayerServerRequest* source)
    {
        var value = new MultiplayerServerRequestMultiplayerServerRequest();
        value.BuildAliasParams = source->BuildAliasParams is null ? null : MultiplayerServerBuildAliasParams.FromNative(source->BuildAliasParams);
        value.BuildId = Utf8.ToString(source->BuildId);
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map2 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i2 = 0; i2 < source->CustomTagsCount; i2++)
            {
                map2[Utf8.ToString(source->CustomTags[i2].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i2].Value) ?? string.Empty;
            }

            value.CustomTags = map2;
        }
        if (source->InitialPlayers is not null && source->InitialPlayersCount != 0)
        {
            var list4 = new List<string>((int)source->InitialPlayersCount);
            for (uint i4 = 0; i4 < source->InitialPlayersCount; i4++)
            {
                list4.Add(Utf8.ToString(source->InitialPlayers[i4]) ?? string.Empty);
            }

            value.InitialPlayers = list4;
        }
        if (source->PreferredRegions is not null && source->PreferredRegionsCount != 0)
        {
            var list6 = new List<string>((int)source->PreferredRegionsCount);
            for (uint i6 = 0; i6 < source->PreferredRegionsCount; i6++)
            {
                list6.Add(Utf8.ToString(source->PreferredRegions[i6]) ?? string.Empty);
            }

            value.PreferredRegions = list6;
        }
        value.SessionCookie = Utf8.ToString(source->SessionCookie);
        value.SessionId = Utf8.ToString(source->SessionId);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerRequestMultiplayerServerRequest* target, PlayFabArena arena)
    {
        *target = default;
        if (BuildAliasParams is not null)
        {
            PFMultiplayerServerBuildAliasParams* native0 = arena.Alloc<PFMultiplayerServerBuildAliasParams>(1);
            BuildAliasParams.WriteTo(native0, arena);
            target->BuildAliasParams = native0;
        }
        target->BuildId = arena.String(BuildId);
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries2 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next2 = 0;
            foreach (KeyValuePair<string, string> pair2 in CustomTags)
            {
                entries2[next2].Key = arena.String(pair2.Key);
                entries2[next2].Value = arena.String(pair2.Value);
                next2++;
            }

            target->CustomTags = entries2;
        }
        target->InitialPlayersCount = (uint)(InitialPlayers is null ? 0 : InitialPlayers.Count);
        target->InitialPlayers = arena.StringArray(InitialPlayers);
        target->PreferredRegionsCount = (uint)(PreferredRegions is null ? 0 : PreferredRegions.Count);
        target->PreferredRegions = arena.StringArray(PreferredRegions);
        target->SessionCookie = arena.String(SessionCookie);
        target->SessionId = arena.String(SessionId);
    }
}

/// <summary>Projects <c>PFMultiplayerServerRequestMultiplayerServerResponse</c>.</summary>
public sealed class MultiplayerServerRequestMultiplayerServerResponse
{
    /// <summary><c>BuildId</c>.</summary>
    public string? BuildId { get; set; }

    /// <summary><c>ConnectedPlayers</c>.</summary>
    public IReadOnlyList<MultiplayerServerConnectedPlayer>? ConnectedPlayers { get; set; }

    /// <summary><c>FQDN</c>.</summary>
    public string? FQDN { get; set; }

    /// <summary><c>IPV4Address</c>.</summary>
    public string? IPV4Address { get; set; }

    /// <summary><c>LastStateTransitionTime</c>.</summary>
    public DateTimeOffset? LastStateTransitionTime { get; set; }

    /// <summary><c>Ports</c>.</summary>
    public IReadOnlyList<MultiplayerServerPort>? Ports { get; set; }

    /// <summary><c>PublicIPV4Addresses</c>.</summary>
    public IReadOnlyList<MultiplayerServerPublicIpAddress>? PublicIPV4Addresses { get; set; }

    /// <summary><c>Region</c>.</summary>
    public string? Region { get; set; }

    /// <summary><c>ServerId</c>.</summary>
    public string? ServerId { get; set; }

    /// <summary><c>SessionId</c>.</summary>
    public string? SessionId { get; set; }

    /// <summary><c>State</c>.</summary>
    public string? State { get; set; }

    /// <summary><c>VmId</c>.</summary>
    public string? VmId { get; set; }

    internal static unsafe MultiplayerServerRequestMultiplayerServerResponse FromNative(PFMultiplayerServerRequestMultiplayerServerResponse* source)
    {
        var value = new MultiplayerServerRequestMultiplayerServerResponse();
        value.BuildId = Utf8.ToString(source->BuildId);
        if (source->ConnectedPlayers is not null && source->ConnectedPlayersCount != 0)
        {
            var list1 = new List<MultiplayerServerConnectedPlayer>((int)source->ConnectedPlayersCount);
            for (uint i1 = 0; i1 < source->ConnectedPlayersCount; i1++)
            {
                list1.Add(MultiplayerServerConnectedPlayer.FromNative(source->ConnectedPlayers[i1]));
            }

            value.ConnectedPlayers = list1;
        }
        value.FQDN = Utf8.ToString(source->FQDN);
        value.IPV4Address = Utf8.ToString(source->IPV4Address);
        value.LastStateTransitionTime = source->LastStateTransitionTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->LastStateTransitionTime);
        if (source->Ports is not null && source->PortsCount != 0)
        {
            var list6 = new List<MultiplayerServerPort>((int)source->PortsCount);
            for (uint i6 = 0; i6 < source->PortsCount; i6++)
            {
                list6.Add(MultiplayerServerPort.FromNative(source->Ports[i6]));
            }

            value.Ports = list6;
        }
        if (source->PublicIPV4Addresses is not null && source->PublicIPV4AddressesCount != 0)
        {
            var list8 = new List<MultiplayerServerPublicIpAddress>((int)source->PublicIPV4AddressesCount);
            for (uint i8 = 0; i8 < source->PublicIPV4AddressesCount; i8++)
            {
                list8.Add(MultiplayerServerPublicIpAddress.FromNative(source->PublicIPV4Addresses[i8]));
            }

            value.PublicIPV4Addresses = list8;
        }
        value.Region = Utf8.ToString(source->Region);
        value.ServerId = Utf8.ToString(source->ServerId);
        value.SessionId = Utf8.ToString(source->SessionId);
        value.State = Utf8.ToString(source->State);
        value.VmId = Utf8.ToString(source->VmId);
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerRequestMultiplayerServerResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->BuildId = arena.String(BuildId);
        target->ConnectedPlayersCount = (uint)(ConnectedPlayers is null ? 0 : ConnectedPlayers.Count);
        if (ConnectedPlayers is not null && ConnectedPlayers.Count > 0)
        {
            PFMultiplayerServerConnectedPlayer** array1 = arena.PointerArray<PFMultiplayerServerConnectedPlayer>(ConnectedPlayers.Count);
            for (int i1 = 0; i1 < ConnectedPlayers.Count; i1++)
            {
                PFMultiplayerServerConnectedPlayer* item1 = arena.Alloc<PFMultiplayerServerConnectedPlayer>(1);
                ConnectedPlayers[i1].WriteTo(item1, arena);
                array1[i1] = item1;
            }

            target->ConnectedPlayers = array1;
        }
        target->FQDN = arena.String(FQDN);
        target->IPV4Address = arena.String(IPV4Address);
        target->LastStateTransitionTime = arena.Value(LastStateTransitionTime is null ? null : (long?)PlayFabTime.ToUnixTime(LastStateTransitionTime.Value));
        target->PortsCount = (uint)(Ports is null ? 0 : Ports.Count);
        if (Ports is not null && Ports.Count > 0)
        {
            PFMultiplayerServerPort** array6 = arena.PointerArray<PFMultiplayerServerPort>(Ports.Count);
            for (int i6 = 0; i6 < Ports.Count; i6++)
            {
                PFMultiplayerServerPort* item6 = arena.Alloc<PFMultiplayerServerPort>(1);
                Ports[i6].WriteTo(item6, arena);
                array6[i6] = item6;
            }

            target->Ports = array6;
        }
        target->PublicIPV4AddressesCount = (uint)(PublicIPV4Addresses is null ? 0 : PublicIPV4Addresses.Count);
        if (PublicIPV4Addresses is not null && PublicIPV4Addresses.Count > 0)
        {
            PFMultiplayerServerPublicIpAddress** array8 = arena.PointerArray<PFMultiplayerServerPublicIpAddress>(PublicIPV4Addresses.Count);
            for (int i8 = 0; i8 < PublicIPV4Addresses.Count; i8++)
            {
                PFMultiplayerServerPublicIpAddress* item8 = arena.Alloc<PFMultiplayerServerPublicIpAddress>(1);
                PublicIPV4Addresses[i8].WriteTo(item8, arena);
                array8[i8] = item8;
            }

            target->PublicIPV4Addresses = array8;
        }
        target->Region = arena.String(Region);
        target->ServerId = arena.String(ServerId);
        target->SessionId = arena.String(SessionId);
        target->State = arena.String(State);
        target->VmId = arena.String(VmId);
    }
}

/// <summary>Projects <c>PFMultiplayerServerSchedule</c>.</summary>
public sealed class MultiplayerServerSchedule
{
    /// <summary><c>Description</c>.</summary>
    public string? Description { get; set; }

    /// <summary><c>EndTime</c>.</summary>
    public DateTimeOffset EndTime { get; set; }

    /// <summary><c>IsDisabled</c>.</summary>
    public bool IsDisabled { get; set; }

    /// <summary><c>IsRecurringWeekly</c>.</summary>
    public bool IsRecurringWeekly { get; set; }

    /// <summary><c>StartTime</c>.</summary>
    public DateTimeOffset StartTime { get; set; }

    /// <summary><c>TargetStandby</c>.</summary>
    public int TargetStandby { get; set; }

    internal static unsafe MultiplayerServerSchedule FromNative(PFMultiplayerServerSchedule* source)
    {
        var value = new MultiplayerServerSchedule();
        value.Description = Utf8.ToString(source->Description);
        value.EndTime = PlayFabTime.ToDateTimeOffset(source->EndTime);
        value.IsDisabled = source->IsDisabled != 0;
        value.IsRecurringWeekly = source->IsRecurringWeekly != 0;
        value.StartTime = PlayFabTime.ToDateTimeOffset(source->StartTime);
        value.TargetStandby = source->TargetStandby;
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerSchedule* target, PlayFabArena arena)
    {
        *target = default;
        target->Description = arena.String(Description);
        target->EndTime = PlayFabTime.ToUnixTime(EndTime);
        target->IsDisabled = IsDisabled ? (byte)1 : (byte)0;
        target->IsRecurringWeekly = IsRecurringWeekly ? (byte)1 : (byte)0;
        target->StartTime = PlayFabTime.ToUnixTime(StartTime);
        target->TargetStandby = TargetStandby;
    }
}

/// <summary>Projects <c>PFMultiplayerServerScheduledStandbySettings</c>.</summary>
public sealed class MultiplayerServerScheduledStandbySettings
{
    /// <summary><c>IsEnabled</c>.</summary>
    public bool IsEnabled { get; set; }

    /// <summary><c>ScheduleList</c>.</summary>
    public IReadOnlyList<MultiplayerServerSchedule>? ScheduleList { get; set; }

    internal static unsafe MultiplayerServerScheduledStandbySettings FromNative(PFMultiplayerServerScheduledStandbySettings* source)
    {
        var value = new MultiplayerServerScheduledStandbySettings();
        value.IsEnabled = source->IsEnabled != 0;
        if (source->ScheduleList is not null && source->ScheduleListCount != 0)
        {
            var list1 = new List<MultiplayerServerSchedule>((int)source->ScheduleListCount);
            for (uint i1 = 0; i1 < source->ScheduleListCount; i1++)
            {
                list1.Add(MultiplayerServerSchedule.FromNative(source->ScheduleList[i1]));
            }

            value.ScheduleList = list1;
        }
        return value;
    }

    internal unsafe void WriteTo(PFMultiplayerServerScheduledStandbySettings* target, PlayFabArena arena)
    {
        *target = default;
        target->IsEnabled = IsEnabled ? (byte)1 : (byte)0;
        target->ScheduleListCount = (uint)(ScheduleList is null ? 0 : ScheduleList.Count);
        if (ScheduleList is not null && ScheduleList.Count > 0)
        {
            PFMultiplayerServerSchedule** array1 = arena.PointerArray<PFMultiplayerServerSchedule>(ScheduleList.Count);
            for (int i1 = 0; i1 < ScheduleList.Count; i1++)
            {
                PFMultiplayerServerSchedule* item1 = arena.Alloc<PFMultiplayerServerSchedule>(1);
                ScheduleList[i1].WriteTo(item1, arena);
                array1[i1] = item1;
            }

            target->ScheduleList = array1;
        }
    }
}
