// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFStatistics
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>Projects <c>PFStatisticsStatisticAggregationMethod</c>.</summary>
public enum StatisticsStatisticAggregationMethod : uint
{
    /// <summary>Projects <c>PFStatisticsStatisticAggregationMethod::Last</c>.</summary>
    Last = 0,
    /// <summary>Projects <c>PFStatisticsStatisticAggregationMethod::Min</c>.</summary>
    Min = 1,
    /// <summary>Projects <c>PFStatisticsStatisticAggregationMethod::Max</c>.</summary>
    Max = 2,
    /// <summary>Projects <c>PFStatisticsStatisticAggregationMethod::Sum</c>.</summary>
    Sum = 3,
}

/// <summary>Projects <c>PFStatisticsCreateStatisticDefinitionRequest</c>.</summary>
public sealed class StatisticsCreateStatisticDefinitionRequest
{
    /// <summary><c>AggregationSources</c>.</summary>
    public IReadOnlyList<string>? AggregationSources { get; set; }

    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<StatisticsStatisticColumn>? Columns { get; set; }

    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public StatisticsStatisticsEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe StatisticsCreateStatisticDefinitionRequest FromNative(PFStatisticsCreateStatisticDefinitionRequest* source)
    {
        var value = new StatisticsCreateStatisticDefinitionRequest();
        if (source->AggregationSources is not null && source->AggregationSourcesCount != 0)
        {
            var list0 = new List<string>((int)source->AggregationSourcesCount);
            for (uint i0 = 0; i0 < source->AggregationSourcesCount; i0++)
            {
                list0.Add(Utf8.ToString(source->AggregationSources[i0]) ?? string.Empty);
            }

            value.AggregationSources = list0;
        }
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list2 = new List<StatisticsStatisticColumn>((int)source->ColumnsCount);
            for (uint i2 = 0; i2 < source->ColumnsCount; i2++)
            {
                list2.Add(StatisticsStatisticColumn.FromNative(source->Columns[i2]));
            }

            value.Columns = list2;
        }
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map4 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i4 = 0; i4 < source->CustomTagsCount; i4++)
            {
                map4[Utf8.ToString(source->CustomTags[i4].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i4].Value) ?? string.Empty;
            }

            value.CustomTags = map4;
        }
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : StatisticsStatisticsEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.Name = Utf8.ToString(source->Name);
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsCreateStatisticDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->AggregationSourcesCount = (uint)(AggregationSources is null ? 0 : AggregationSources.Count);
        target->AggregationSources = arena.StringArray(AggregationSources);
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFStatisticsStatisticColumn** array2 = arena.PointerArray<PFStatisticsStatisticColumn>(Columns.Count);
            for (int i2 = 0; i2 < Columns.Count; i2++)
            {
                PFStatisticsStatisticColumn* item2 = arena.Alloc<PFStatisticsStatisticColumn>(1);
                Columns[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->Columns = array2;
        }
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries4 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next4 = 0;
            foreach (KeyValuePair<string, string> pair4 in CustomTags)
            {
                entries4[next4].Key = arena.String(pair4.Key);
                entries4[next4].Value = arena.String(pair4.Value);
                next4++;
            }

            target->CustomTags = entries4;
        }
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFStatisticsStatisticsEventEmissionConfig* native7 = arena.Alloc<PFStatisticsStatisticsEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native7, arena);
            target->EventEmissionConfig = native7;
        }
        target->Name = arena.String(Name);
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native9 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native9, arena);
            target->VersionConfiguration = native9;
        }
    }
}

/// <summary>Projects <c>PFStatisticsDeleteStatisticDefinitionRequest</c>.</summary>
public sealed class StatisticsDeleteStatisticDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe StatisticsDeleteStatisticDefinitionRequest FromNative(PFStatisticsDeleteStatisticDefinitionRequest* source)
    {
        var value = new StatisticsDeleteStatisticDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsDeleteStatisticDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFStatisticsDeleteStatisticsRequest</c>.</summary>
public sealed class StatisticsDeleteStatisticsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>Statistics</c>.</summary>
    public IReadOnlyList<StatisticsStatisticDelete>? Statistics { get; set; }

    internal static unsafe StatisticsDeleteStatisticsRequest FromNative(PFStatisticsDeleteStatisticsRequest* source)
    {
        var value = new StatisticsDeleteStatisticsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        if (source->Statistics is not null && source->StatisticsCount != 0)
        {
            var list3 = new List<StatisticsStatisticDelete>((int)source->StatisticsCount);
            for (uint i3 = 0; i3 < source->StatisticsCount; i3++)
            {
                list3.Add(StatisticsStatisticDelete.FromNative(source->Statistics[i3]));
            }

            value.Statistics = list3;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsDeleteStatisticsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->StatisticsCount = (uint)(Statistics is null ? 0 : Statistics.Count);
        if (Statistics is not null && Statistics.Count > 0)
        {
            PFStatisticsStatisticDelete** array3 = arena.PointerArray<PFStatisticsStatisticDelete>(Statistics.Count);
            for (int i3 = 0; i3 < Statistics.Count; i3++)
            {
                PFStatisticsStatisticDelete* item3 = arena.Alloc<PFStatisticsStatisticDelete>(1);
                Statistics[i3].WriteTo(item3, arena);
                array3[i3] = item3;
            }

            target->Statistics = array3;
        }
    }
}

/// <summary>Projects <c>PFStatisticsDeleteStatisticsResponse</c>.</summary>
public sealed class StatisticsDeleteStatisticsResponse
{
    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    internal static unsafe StatisticsDeleteStatisticsResponse FromNative(PFStatisticsDeleteStatisticsResponse* source)
    {
        var value = new StatisticsDeleteStatisticsResponse();
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsDeleteStatisticsResponse* target, PlayFabArena arena)
    {
        *target = default;
        if (Entity is not null)
        {
            PFEntityKey* native0 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native0, arena);
            target->Entity = native0;
        }
    }
}

/// <summary>Projects <c>PFStatisticsEntityStatisticValue</c>.</summary>
public sealed class StatisticsEntityStatisticValue
{
    /// <summary><c>Metadata</c>.</summary>
    public string? Metadata { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>Scores</c>.</summary>
    public IReadOnlyList<string>? Scores { get; set; }

    /// <summary><c>Version</c>.</summary>
    public int Version { get; set; }

    internal static unsafe StatisticsEntityStatisticValue FromNative(PFStatisticsEntityStatisticValue* source)
    {
        var value = new StatisticsEntityStatisticValue();
        value.Metadata = Utf8.ToString(source->Metadata);
        value.Name = Utf8.ToString(source->Name);
        if (source->Scores is not null && source->ScoresCount != 0)
        {
            var list2 = new List<string>((int)source->ScoresCount);
            for (uint i2 = 0; i2 < source->ScoresCount; i2++)
            {
                list2.Add(Utf8.ToString(source->Scores[i2]) ?? string.Empty);
            }

            value.Scores = list2;
        }
        value.Version = source->Version;
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsEntityStatisticValue* target, PlayFabArena arena)
    {
        *target = default;
        target->Metadata = arena.String(Metadata);
        target->Name = arena.String(Name);
        target->ScoresCount = (uint)(Scores is null ? 0 : Scores.Count);
        target->Scores = arena.StringArray(Scores);
        target->Version = Version;
    }
}

/// <summary>Projects <c>PFStatisticsEntityStatistics</c>.</summary>
public sealed class StatisticsEntityStatistics
{
    /// <summary><c>EntityKey</c>.</summary>
    public EntityKey? EntityKey { get; set; }

    /// <summary><c>Statistics</c>.</summary>
    public IReadOnlyList<StatisticsEntityStatisticValue>? Statistics { get; set; }

    internal static unsafe StatisticsEntityStatistics FromNative(PFStatisticsEntityStatistics* source)
    {
        var value = new StatisticsEntityStatistics();
        value.EntityKey = source->EntityKey is null ? null : EntityKey.FromNative(source->EntityKey);
        if (source->Statistics is not null && source->StatisticsCount != 0)
        {
            var list1 = new List<StatisticsEntityStatisticValue>((int)source->StatisticsCount);
            for (uint i1 = 0; i1 < source->StatisticsCount; i1++)
            {
                list1.Add(StatisticsEntityStatisticValue.FromNative(source->Statistics[i1]));
            }

            value.Statistics = list1;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsEntityStatistics* target, PlayFabArena arena)
    {
        *target = default;
        if (EntityKey is not null)
        {
            PFEntityKey* native0 = arena.Alloc<PFEntityKey>(1);
            EntityKey.WriteTo(native0, arena);
            target->EntityKey = native0;
        }
        target->StatisticsCount = (uint)(Statistics is null ? 0 : Statistics.Count);
        if (Statistics is not null && Statistics.Count > 0)
        {
            PFStatisticsEntityStatisticValue** array1 = arena.PointerArray<PFStatisticsEntityStatisticValue>(Statistics.Count);
            for (int i1 = 0; i1 < Statistics.Count; i1++)
            {
                PFStatisticsEntityStatisticValue* item1 = arena.Alloc<PFStatisticsEntityStatisticValue>(1);
                Statistics[i1].WriteTo(item1, arena);
                array1[i1] = item1;
            }

            target->Statistics = array1;
        }
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticDefinitionRequest</c>.</summary>
public sealed class StatisticsGetStatisticDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe StatisticsGetStatisticDefinitionRequest FromNative(PFStatisticsGetStatisticDefinitionRequest* source)
    {
        var value = new StatisticsGetStatisticDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticDefinitionResponse</c>.</summary>
public sealed class StatisticsGetStatisticDefinitionResponse
{
    /// <summary><c>AggregationDestinations</c>.</summary>
    public IReadOnlyList<string>? AggregationDestinations { get; set; }

    /// <summary><c>AggregationSources</c>.</summary>
    public IReadOnlyList<string>? AggregationSources { get; set; }

    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<StatisticsStatisticColumn>? Columns { get; set; }

    /// <summary><c>Created</c>.</summary>
    public DateTimeOffset Created { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public StatisticsStatisticsEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>LastResetTime</c>.</summary>
    public DateTimeOffset? LastResetTime { get; set; }

    /// <summary><c>LinkedLeaderboardNames</c>.</summary>
    public IReadOnlyList<string>? LinkedLeaderboardNames { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe StatisticsGetStatisticDefinitionResponse FromNative(PFStatisticsGetStatisticDefinitionResponse* source)
    {
        var value = new StatisticsGetStatisticDefinitionResponse();
        if (source->AggregationDestinations is not null && source->AggregationDestinationsCount != 0)
        {
            var list0 = new List<string>((int)source->AggregationDestinationsCount);
            for (uint i0 = 0; i0 < source->AggregationDestinationsCount; i0++)
            {
                list0.Add(Utf8.ToString(source->AggregationDestinations[i0]) ?? string.Empty);
            }

            value.AggregationDestinations = list0;
        }
        if (source->AggregationSources is not null && source->AggregationSourcesCount != 0)
        {
            var list2 = new List<string>((int)source->AggregationSourcesCount);
            for (uint i2 = 0; i2 < source->AggregationSourcesCount; i2++)
            {
                list2.Add(Utf8.ToString(source->AggregationSources[i2]) ?? string.Empty);
            }

            value.AggregationSources = list2;
        }
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list4 = new List<StatisticsStatisticColumn>((int)source->ColumnsCount);
            for (uint i4 = 0; i4 < source->ColumnsCount; i4++)
            {
                list4.Add(StatisticsStatisticColumn.FromNative(source->Columns[i4]));
            }

            value.Columns = list4;
        }
        value.Created = PlayFabTime.ToDateTimeOffset(source->Created);
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : StatisticsStatisticsEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.LastResetTime = source->LastResetTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->LastResetTime);
        if (source->LinkedLeaderboardNames is not null && source->LinkedLeaderboardNamesCount != 0)
        {
            var list10 = new List<string>((int)source->LinkedLeaderboardNamesCount);
            for (uint i10 = 0; i10 < source->LinkedLeaderboardNamesCount; i10++)
            {
                list10.Add(Utf8.ToString(source->LinkedLeaderboardNames[i10]) ?? string.Empty);
            }

            value.LinkedLeaderboardNames = list10;
        }
        value.Name = Utf8.ToString(source->Name);
        value.Version = source->Version;
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticDefinitionResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->AggregationDestinationsCount = (uint)(AggregationDestinations is null ? 0 : AggregationDestinations.Count);
        target->AggregationDestinations = arena.StringArray(AggregationDestinations);
        target->AggregationSourcesCount = (uint)(AggregationSources is null ? 0 : AggregationSources.Count);
        target->AggregationSources = arena.StringArray(AggregationSources);
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFStatisticsStatisticColumn** array4 = arena.PointerArray<PFStatisticsStatisticColumn>(Columns.Count);
            for (int i4 = 0; i4 < Columns.Count; i4++)
            {
                PFStatisticsStatisticColumn* item4 = arena.Alloc<PFStatisticsStatisticColumn>(1);
                Columns[i4].WriteTo(item4, arena);
                array4[i4] = item4;
            }

            target->Columns = array4;
        }
        target->Created = PlayFabTime.ToUnixTime(Created);
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFStatisticsStatisticsEventEmissionConfig* native8 = arena.Alloc<PFStatisticsStatisticsEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native8, arena);
            target->EventEmissionConfig = native8;
        }
        target->LastResetTime = arena.Value(LastResetTime is null ? null : (long?)PlayFabTime.ToUnixTime(LastResetTime.Value));
        target->LinkedLeaderboardNamesCount = (uint)(LinkedLeaderboardNames is null ? 0 : LinkedLeaderboardNames.Count);
        target->LinkedLeaderboardNames = arena.StringArray(LinkedLeaderboardNames);
        target->Name = arena.String(Name);
        target->Version = Version;
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native14 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native14, arena);
            target->VersionConfiguration = native14;
        }
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticsForEntitiesRequest</c>.</summary>
public sealed class StatisticsGetStatisticsForEntitiesRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entities</c>.</summary>
    public IReadOnlyList<EntityKey>? Entities { get; set; }

    /// <summary><c>StatisticNames</c>.</summary>
    public IReadOnlyList<string>? StatisticNames { get; set; }

    internal static unsafe StatisticsGetStatisticsForEntitiesRequest FromNative(PFStatisticsGetStatisticsForEntitiesRequest* source)
    {
        var value = new StatisticsGetStatisticsForEntitiesRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        if (source->Entities is not null && source->EntitiesCount != 0)
        {
            var list2 = new List<EntityKey>((int)source->EntitiesCount);
            for (uint i2 = 0; i2 < source->EntitiesCount; i2++)
            {
                list2.Add(EntityKey.FromNative(source->Entities[i2]));
            }

            value.Entities = list2;
        }
        if (source->StatisticNames is not null && source->StatisticNamesCount != 0)
        {
            var list4 = new List<string>((int)source->StatisticNamesCount);
            for (uint i4 = 0; i4 < source->StatisticNamesCount; i4++)
            {
                list4.Add(Utf8.ToString(source->StatisticNames[i4]) ?? string.Empty);
            }

            value.StatisticNames = list4;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticsForEntitiesRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->EntitiesCount = (uint)(Entities is null ? 0 : Entities.Count);
        if (Entities is not null && Entities.Count > 0)
        {
            PFEntityKey** array2 = arena.PointerArray<PFEntityKey>(Entities.Count);
            for (int i2 = 0; i2 < Entities.Count; i2++)
            {
                PFEntityKey* item2 = arena.Alloc<PFEntityKey>(1);
                Entities[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->Entities = array2;
        }
        target->StatisticNamesCount = (uint)(StatisticNames is null ? 0 : StatisticNames.Count);
        target->StatisticNames = arena.StringArray(StatisticNames);
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticsForEntitiesResponse</c>.</summary>
public sealed class StatisticsGetStatisticsForEntitiesResponse
{
    /// <summary><c>ColumnDetails</c>.</summary>
    public IReadOnlyDictionary<string, StatisticsStatisticColumnCollection>? ColumnDetails { get; set; }

    /// <summary><c>EntitiesStatistics</c>.</summary>
    public IReadOnlyList<StatisticsEntityStatistics>? EntitiesStatistics { get; set; }

    internal static unsafe StatisticsGetStatisticsForEntitiesResponse FromNative(PFStatisticsGetStatisticsForEntitiesResponse* source)
    {
        var value = new StatisticsGetStatisticsForEntitiesResponse();
        if (source->ColumnDetails is not null && source->ColumnDetailsCount != 0)
        {
            var map0 = new Dictionary<string, StatisticsStatisticColumnCollection>((int)source->ColumnDetailsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->ColumnDetailsCount; i0++)
            {
                map0[Utf8.ToString(source->ColumnDetails[i0].Key) ?? string.Empty] = StatisticsStatisticColumnCollection.FromNative(source->ColumnDetails[i0].Value);
            }

            value.ColumnDetails = map0;
        }
        if (source->EntitiesStatistics is not null && source->EntitiesStatisticsCount != 0)
        {
            var list2 = new List<StatisticsEntityStatistics>((int)source->EntitiesStatisticsCount);
            for (uint i2 = 0; i2 < source->EntitiesStatisticsCount; i2++)
            {
                list2.Add(StatisticsEntityStatistics.FromNative(source->EntitiesStatistics[i2]));
            }

            value.EntitiesStatistics = list2;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticsForEntitiesResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnDetailsCount = (uint)(ColumnDetails is null ? 0 : ColumnDetails.Count);
        if (ColumnDetails is not null && ColumnDetails.Count > 0)
        {
            PFStatisticsStatisticColumnCollectionDictionaryEntry* entries0 = arena.Alloc<PFStatisticsStatisticColumnCollectionDictionaryEntry>(ColumnDetails.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, StatisticsStatisticColumnCollection> pair0 in ColumnDetails)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                if (pair0.Value is not null)
                {
                    PFStatisticsStatisticColumnCollection* item0 = arena.Alloc<PFStatisticsStatisticColumnCollection>(1);
                    pair0.Value.WriteTo(item0, arena);
                    entries0[next0].Value = item0;
                }
                next0++;
            }

            target->ColumnDetails = entries0;
        }
        target->EntitiesStatisticsCount = (uint)(EntitiesStatistics is null ? 0 : EntitiesStatistics.Count);
        if (EntitiesStatistics is not null && EntitiesStatistics.Count > 0)
        {
            PFStatisticsEntityStatistics** array2 = arena.PointerArray<PFStatisticsEntityStatistics>(EntitiesStatistics.Count);
            for (int i2 = 0; i2 < EntitiesStatistics.Count; i2++)
            {
                PFStatisticsEntityStatistics* item2 = arena.Alloc<PFStatisticsEntityStatistics>(1);
                EntitiesStatistics[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->EntitiesStatistics = array2;
        }
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticsRequest</c>.</summary>
public sealed class StatisticsGetStatisticsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>StatisticNames</c>.</summary>
    public IReadOnlyList<string>? StatisticNames { get; set; }

    internal static unsafe StatisticsGetStatisticsRequest FromNative(PFStatisticsGetStatisticsRequest* source)
    {
        var value = new StatisticsGetStatisticsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        if (source->StatisticNames is not null && source->StatisticNamesCount != 0)
        {
            var list3 = new List<string>((int)source->StatisticNamesCount);
            for (uint i3 = 0; i3 < source->StatisticNamesCount; i3++)
            {
                list3.Add(Utf8.ToString(source->StatisticNames[i3]) ?? string.Empty);
            }

            value.StatisticNames = list3;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->StatisticNamesCount = (uint)(StatisticNames is null ? 0 : StatisticNames.Count);
        target->StatisticNames = arena.StringArray(StatisticNames);
    }
}

/// <summary>Projects <c>PFStatisticsGetStatisticsResponse</c>.</summary>
public sealed class StatisticsGetStatisticsResponse
{
    /// <summary><c>ColumnDetails</c>.</summary>
    public IReadOnlyDictionary<string, StatisticsStatisticColumnCollection>? ColumnDetails { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>Statistics</c>.</summary>
    public IReadOnlyDictionary<string, StatisticsEntityStatisticValue>? Statistics { get; set; }

    internal static unsafe StatisticsGetStatisticsResponse FromNative(PFStatisticsGetStatisticsResponse* source)
    {
        var value = new StatisticsGetStatisticsResponse();
        if (source->ColumnDetails is not null && source->ColumnDetailsCount != 0)
        {
            var map0 = new Dictionary<string, StatisticsStatisticColumnCollection>((int)source->ColumnDetailsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->ColumnDetailsCount; i0++)
            {
                map0[Utf8.ToString(source->ColumnDetails[i0].Key) ?? string.Empty] = StatisticsStatisticColumnCollection.FromNative(source->ColumnDetails[i0].Value);
            }

            value.ColumnDetails = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        if (source->Statistics is not null && source->StatisticsCount != 0)
        {
            var map3 = new Dictionary<string, StatisticsEntityStatisticValue>((int)source->StatisticsCount, StringComparer.Ordinal);
            for (uint i3 = 0; i3 < source->StatisticsCount; i3++)
            {
                map3[Utf8.ToString(source->Statistics[i3].Key) ?? string.Empty] = StatisticsEntityStatisticValue.FromNative(source->Statistics[i3].Value);
            }

            value.Statistics = map3;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsGetStatisticsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnDetailsCount = (uint)(ColumnDetails is null ? 0 : ColumnDetails.Count);
        if (ColumnDetails is not null && ColumnDetails.Count > 0)
        {
            PFStatisticsStatisticColumnCollectionDictionaryEntry* entries0 = arena.Alloc<PFStatisticsStatisticColumnCollectionDictionaryEntry>(ColumnDetails.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, StatisticsStatisticColumnCollection> pair0 in ColumnDetails)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                if (pair0.Value is not null)
                {
                    PFStatisticsStatisticColumnCollection* item0 = arena.Alloc<PFStatisticsStatisticColumnCollection>(1);
                    pair0.Value.WriteTo(item0, arena);
                    entries0[next0].Value = item0;
                }
                next0++;
            }

            target->ColumnDetails = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->StatisticsCount = (uint)(Statistics is null ? 0 : Statistics.Count);
        if (Statistics is not null && Statistics.Count > 0)
        {
            PFStatisticsEntityStatisticValueDictionaryEntry* entries3 = arena.Alloc<PFStatisticsEntityStatisticValueDictionaryEntry>(Statistics.Count);
            int next3 = 0;
            foreach (KeyValuePair<string, StatisticsEntityStatisticValue> pair3 in Statistics)
            {
                entries3[next3].Key = arena.String(pair3.Key);
                if (pair3.Value is not null)
                {
                    PFStatisticsEntityStatisticValue* item3 = arena.Alloc<PFStatisticsEntityStatisticValue>(1);
                    pair3.Value.WriteTo(item3, arena);
                    entries3[next3].Value = item3;
                }
                next3++;
            }

            target->Statistics = entries3;
        }
    }
}

/// <summary>Projects <c>PFStatisticsIncrementStatisticVersionRequest</c>.</summary>
public sealed class StatisticsIncrementStatisticVersionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe StatisticsIncrementStatisticVersionRequest FromNative(PFStatisticsIncrementStatisticVersionRequest* source)
    {
        var value = new StatisticsIncrementStatisticVersionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsIncrementStatisticVersionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFStatisticsIncrementStatisticVersionResponse</c>.</summary>
public sealed class StatisticsIncrementStatisticVersionResponse
{
    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    internal static unsafe StatisticsIncrementStatisticVersionResponse FromNative(PFStatisticsIncrementStatisticVersionResponse* source)
    {
        var value = new StatisticsIncrementStatisticVersionResponse();
        value.Version = source->Version;
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsIncrementStatisticVersionResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->Version = Version;
    }
}

/// <summary>Projects <c>PFStatisticsListStatisticDefinitionsRequest</c>.</summary>
public sealed class StatisticsListStatisticDefinitionsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>PageSize</c>.</summary>
    public int? PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    internal static unsafe StatisticsListStatisticDefinitionsRequest FromNative(PFStatisticsListStatisticDefinitionsRequest* source)
    {
        var value = new StatisticsListStatisticDefinitionsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.PageSize = source->PageSize is null ? null : (int?)(*source->PageSize);
        value.SkipToken = Utf8.ToString(source->SkipToken);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsListStatisticDefinitionsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        target->PageSize = arena.Value(PageSize);
        target->SkipToken = arena.String(SkipToken);
    }
}

/// <summary>Projects <c>PFStatisticsListStatisticDefinitionsResponse</c>.</summary>
public sealed class StatisticsListStatisticDefinitionsResponse
{
    /// <summary><c>PageSize</c>.</summary>
    public int PageSize { get; set; }

    /// <summary><c>SkipToken</c>.</summary>
    public string? SkipToken { get; set; }

    /// <summary><c>StatisticDefinitions</c>.</summary>
    public IReadOnlyList<StatisticsStatisticDefinition>? StatisticDefinitions { get; set; }

    internal static unsafe StatisticsListStatisticDefinitionsResponse FromNative(PFStatisticsListStatisticDefinitionsResponse* source)
    {
        var value = new StatisticsListStatisticDefinitionsResponse();
        value.PageSize = source->PageSize;
        value.SkipToken = Utf8.ToString(source->SkipToken);
        if (source->StatisticDefinitions is not null && source->StatisticDefinitionsCount != 0)
        {
            var list2 = new List<StatisticsStatisticDefinition>((int)source->StatisticDefinitionsCount);
            for (uint i2 = 0; i2 < source->StatisticDefinitionsCount; i2++)
            {
                list2.Add(StatisticsStatisticDefinition.FromNative(source->StatisticDefinitions[i2]));
            }

            value.StatisticDefinitions = list2;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsListStatisticDefinitionsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->PageSize = PageSize;
        target->SkipToken = arena.String(SkipToken);
        target->StatisticDefinitionsCount = (uint)(StatisticDefinitions is null ? 0 : StatisticDefinitions.Count);
        if (StatisticDefinitions is not null && StatisticDefinitions.Count > 0)
        {
            PFStatisticsStatisticDefinition** array2 = arena.PointerArray<PFStatisticsStatisticDefinition>(StatisticDefinitions.Count);
            for (int i2 = 0; i2 < StatisticDefinitions.Count; i2++)
            {
                PFStatisticsStatisticDefinition* item2 = arena.Alloc<PFStatisticsStatisticDefinition>(1);
                StatisticDefinitions[i2].WriteTo(item2, arena);
                array2[i2] = item2;
            }

            target->StatisticDefinitions = array2;
        }
    }
}

/// <summary>Projects <c>PFStatisticsStatisticColumn</c>.</summary>
public sealed class StatisticsStatisticColumn
{
    /// <summary><c>AggregationMethod</c>.</summary>
    public StatisticsStatisticAggregationMethod AggregationMethod { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe StatisticsStatisticColumn FromNative(PFStatisticsStatisticColumn* source)
    {
        var value = new StatisticsStatisticColumn();
        value.AggregationMethod = (StatisticsStatisticAggregationMethod)source->AggregationMethod;
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticColumn* target, PlayFabArena arena)
    {
        *target = default;
        target->AggregationMethod = (PFStatisticsStatisticAggregationMethod)AggregationMethod;
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFStatisticsStatisticColumnCollection</c>.</summary>
public sealed class StatisticsStatisticColumnCollection
{
    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<StatisticsStatisticColumn>? Columns { get; set; }

    internal static unsafe StatisticsStatisticColumnCollection FromNative(PFStatisticsStatisticColumnCollection* source)
    {
        var value = new StatisticsStatisticColumnCollection();
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list0 = new List<StatisticsStatisticColumn>((int)source->ColumnsCount);
            for (uint i0 = 0; i0 < source->ColumnsCount; i0++)
            {
                list0.Add(StatisticsStatisticColumn.FromNative(source->Columns[i0]));
            }

            value.Columns = list0;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticColumnCollection* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFStatisticsStatisticColumn** array0 = arena.PointerArray<PFStatisticsStatisticColumn>(Columns.Count);
            for (int i0 = 0; i0 < Columns.Count; i0++)
            {
                PFStatisticsStatisticColumn* item0 = arena.Alloc<PFStatisticsStatisticColumn>(1);
                Columns[i0].WriteTo(item0, arena);
                array0[i0] = item0;
            }

            target->Columns = array0;
        }
    }
}

/// <summary>Projects <c>PFStatisticsStatisticDefinition</c>.</summary>
public sealed class StatisticsStatisticDefinition
{
    /// <summary><c>AggregationDestinations</c>.</summary>
    public IReadOnlyList<string>? AggregationDestinations { get; set; }

    /// <summary><c>AggregationSources</c>.</summary>
    public IReadOnlyList<string>? AggregationSources { get; set; }

    /// <summary><c>Columns</c>.</summary>
    public IReadOnlyList<StatisticsStatisticColumn>? Columns { get; set; }

    /// <summary><c>Created</c>.</summary>
    public DateTimeOffset Created { get; set; }

    /// <summary><c>EntityType</c>.</summary>
    public string? EntityType { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public StatisticsStatisticsEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>LastResetTime</c>.</summary>
    public DateTimeOffset? LastResetTime { get; set; }

    /// <summary><c>LinkedLeaderboardNames</c>.</summary>
    public IReadOnlyList<string>? LinkedLeaderboardNames { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint Version { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe StatisticsStatisticDefinition FromNative(PFStatisticsStatisticDefinition* source)
    {
        var value = new StatisticsStatisticDefinition();
        if (source->AggregationDestinations is not null && source->AggregationDestinationsCount != 0)
        {
            var list0 = new List<string>((int)source->AggregationDestinationsCount);
            for (uint i0 = 0; i0 < source->AggregationDestinationsCount; i0++)
            {
                list0.Add(Utf8.ToString(source->AggregationDestinations[i0]) ?? string.Empty);
            }

            value.AggregationDestinations = list0;
        }
        if (source->AggregationSources is not null && source->AggregationSourcesCount != 0)
        {
            var list2 = new List<string>((int)source->AggregationSourcesCount);
            for (uint i2 = 0; i2 < source->AggregationSourcesCount; i2++)
            {
                list2.Add(Utf8.ToString(source->AggregationSources[i2]) ?? string.Empty);
            }

            value.AggregationSources = list2;
        }
        if (source->Columns is not null && source->ColumnsCount != 0)
        {
            var list4 = new List<StatisticsStatisticColumn>((int)source->ColumnsCount);
            for (uint i4 = 0; i4 < source->ColumnsCount; i4++)
            {
                list4.Add(StatisticsStatisticColumn.FromNative(source->Columns[i4]));
            }

            value.Columns = list4;
        }
        value.Created = PlayFabTime.ToDateTimeOffset(source->Created);
        value.EntityType = Utf8.ToString(source->EntityType);
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : StatisticsStatisticsEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.LastResetTime = source->LastResetTime is null ? null : (DateTimeOffset?)PlayFabTime.ToDateTimeOffset(*source->LastResetTime);
        if (source->LinkedLeaderboardNames is not null && source->LinkedLeaderboardNamesCount != 0)
        {
            var list10 = new List<string>((int)source->LinkedLeaderboardNamesCount);
            for (uint i10 = 0; i10 < source->LinkedLeaderboardNamesCount; i10++)
            {
                list10.Add(Utf8.ToString(source->LinkedLeaderboardNames[i10]) ?? string.Empty);
            }

            value.LinkedLeaderboardNames = list10;
        }
        value.Name = Utf8.ToString(source->Name);
        value.Version = source->Version;
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticDefinition* target, PlayFabArena arena)
    {
        *target = default;
        target->AggregationDestinationsCount = (uint)(AggregationDestinations is null ? 0 : AggregationDestinations.Count);
        target->AggregationDestinations = arena.StringArray(AggregationDestinations);
        target->AggregationSourcesCount = (uint)(AggregationSources is null ? 0 : AggregationSources.Count);
        target->AggregationSources = arena.StringArray(AggregationSources);
        target->ColumnsCount = (uint)(Columns is null ? 0 : Columns.Count);
        if (Columns is not null && Columns.Count > 0)
        {
            PFStatisticsStatisticColumn** array4 = arena.PointerArray<PFStatisticsStatisticColumn>(Columns.Count);
            for (int i4 = 0; i4 < Columns.Count; i4++)
            {
                PFStatisticsStatisticColumn* item4 = arena.Alloc<PFStatisticsStatisticColumn>(1);
                Columns[i4].WriteTo(item4, arena);
                array4[i4] = item4;
            }

            target->Columns = array4;
        }
        target->Created = PlayFabTime.ToUnixTime(Created);
        target->EntityType = arena.String(EntityType);
        if (EventEmissionConfig is not null)
        {
            PFStatisticsStatisticsEventEmissionConfig* native8 = arena.Alloc<PFStatisticsStatisticsEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native8, arena);
            target->EventEmissionConfig = native8;
        }
        target->LastResetTime = arena.Value(LastResetTime is null ? null : (long?)PlayFabTime.ToUnixTime(LastResetTime.Value));
        target->LinkedLeaderboardNamesCount = (uint)(LinkedLeaderboardNames is null ? 0 : LinkedLeaderboardNames.Count);
        target->LinkedLeaderboardNames = arena.StringArray(LinkedLeaderboardNames);
        target->Name = arena.String(Name);
        target->Version = Version;
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native14 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native14, arena);
            target->VersionConfiguration = native14;
        }
    }
}

/// <summary>Projects <c>PFStatisticsStatisticDelete</c>.</summary>
public sealed class StatisticsStatisticDelete
{
    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    internal static unsafe StatisticsStatisticDelete FromNative(PFStatisticsStatisticDelete* source)
    {
        var value = new StatisticsStatisticDelete();
        value.Name = Utf8.ToString(source->Name);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticDelete* target, PlayFabArena arena)
    {
        *target = default;
        target->Name = arena.String(Name);
    }
}

/// <summary>Projects <c>PFStatisticsStatisticUpdate</c>.</summary>
public sealed class StatisticsStatisticUpdate
{
    /// <summary><c>Metadata</c>.</summary>
    public string? Metadata { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>Scores</c>.</summary>
    public IReadOnlyList<string>? Scores { get; set; }

    /// <summary><c>Version</c>.</summary>
    public uint? Version { get; set; }

    internal static unsafe StatisticsStatisticUpdate FromNative(PFStatisticsStatisticUpdate* source)
    {
        var value = new StatisticsStatisticUpdate();
        value.Metadata = Utf8.ToString(source->Metadata);
        value.Name = Utf8.ToString(source->Name);
        if (source->Scores is not null && source->ScoresCount != 0)
        {
            var list2 = new List<string>((int)source->ScoresCount);
            for (uint i2 = 0; i2 < source->ScoresCount; i2++)
            {
                list2.Add(Utf8.ToString(source->Scores[i2]) ?? string.Empty);
            }

            value.Scores = list2;
        }
        value.Version = source->Version is null ? null : (uint?)(*source->Version);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticUpdate* target, PlayFabArena arena)
    {
        *target = default;
        target->Metadata = arena.String(Metadata);
        target->Name = arena.String(Name);
        target->ScoresCount = (uint)(Scores is null ? 0 : Scores.Count);
        target->Scores = arena.StringArray(Scores);
        target->Version = arena.Value(Version);
    }
}

/// <summary>Projects <c>PFStatisticsStatisticsEventEmissionConfig</c>.</summary>
public sealed class StatisticsStatisticsEventEmissionConfig
{
    /// <summary><c>UpdateEventConfig</c>.</summary>
    public StatisticsStatisticsUpdateEventConfig? UpdateEventConfig { get; set; }

    internal static unsafe StatisticsStatisticsEventEmissionConfig FromNative(PFStatisticsStatisticsEventEmissionConfig* source)
    {
        var value = new StatisticsStatisticsEventEmissionConfig();
        value.UpdateEventConfig = source->UpdateEventConfig is null ? null : StatisticsStatisticsUpdateEventConfig.FromNative(source->UpdateEventConfig);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticsEventEmissionConfig* target, PlayFabArena arena)
    {
        *target = default;
        if (UpdateEventConfig is not null)
        {
            PFStatisticsStatisticsUpdateEventConfig* native0 = arena.Alloc<PFStatisticsStatisticsUpdateEventConfig>(1);
            UpdateEventConfig.WriteTo(native0, arena);
            target->UpdateEventConfig = native0;
        }
    }
}

/// <summary>Projects <c>PFStatisticsStatisticsUpdateEventConfig</c>.</summary>
public sealed class StatisticsStatisticsUpdateEventConfig
{
    /// <summary><c>EventType</c>.</summary>
    public EventType EventType { get; set; }

    internal static unsafe StatisticsStatisticsUpdateEventConfig FromNative(PFStatisticsStatisticsUpdateEventConfig* source)
    {
        var value = new StatisticsStatisticsUpdateEventConfig();
        value.EventType = (EventType)source->EventType;
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsStatisticsUpdateEventConfig* target, PlayFabArena arena)
    {
        *target = default;
        target->EventType = (PFEventType)EventType;
    }
}

/// <summary>Projects <c>PFStatisticsUpdateStatisticDefinitionRequest</c>.</summary>
public sealed class StatisticsUpdateStatisticDefinitionRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>EventEmissionConfig</c>.</summary>
    public StatisticsStatisticsEventEmissionConfig? EventEmissionConfig { get; set; }

    /// <summary><c>Name</c>.</summary>
    public string? Name { get; set; }

    /// <summary><c>VersionConfiguration</c>.</summary>
    public VersionConfiguration? VersionConfiguration { get; set; }

    internal static unsafe StatisticsUpdateStatisticDefinitionRequest FromNative(PFStatisticsUpdateStatisticDefinitionRequest* source)
    {
        var value = new StatisticsUpdateStatisticDefinitionRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.EventEmissionConfig = source->EventEmissionConfig is null ? null : StatisticsStatisticsEventEmissionConfig.FromNative(source->EventEmissionConfig);
        value.Name = Utf8.ToString(source->Name);
        value.VersionConfiguration = source->VersionConfiguration is null ? null : VersionConfiguration.FromNative(source->VersionConfiguration);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsUpdateStatisticDefinitionRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (EventEmissionConfig is not null)
        {
            PFStatisticsStatisticsEventEmissionConfig* native2 = arena.Alloc<PFStatisticsStatisticsEventEmissionConfig>(1);
            EventEmissionConfig.WriteTo(native2, arena);
            target->EventEmissionConfig = native2;
        }
        target->Name = arena.String(Name);
        if (VersionConfiguration is not null)
        {
            PFVersionConfiguration* native4 = arena.Alloc<PFVersionConfiguration>(1);
            VersionConfiguration.WriteTo(native4, arena);
            target->VersionConfiguration = native4;
        }
    }
}

/// <summary>Projects <c>PFStatisticsUpdateStatisticsRequest</c>.</summary>
public sealed class StatisticsUpdateStatisticsRequest
{
    /// <summary><c>CustomTags</c>.</summary>
    public IReadOnlyDictionary<string, string>? CustomTags { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>Statistics</c>.</summary>
    public IReadOnlyList<StatisticsStatisticUpdate>? Statistics { get; set; }

    /// <summary><c>TransactionId</c>.</summary>
    public string? TransactionId { get; set; }

    internal static unsafe StatisticsUpdateStatisticsRequest FromNative(PFStatisticsUpdateStatisticsRequest* source)
    {
        var value = new StatisticsUpdateStatisticsRequest();
        if (source->CustomTags is not null && source->CustomTagsCount != 0)
        {
            var map0 = new Dictionary<string, string>((int)source->CustomTagsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->CustomTagsCount; i0++)
            {
                map0[Utf8.ToString(source->CustomTags[i0].Key) ?? string.Empty] = Utf8.ToString(source->CustomTags[i0].Value) ?? string.Empty;
            }

            value.CustomTags = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        if (source->Statistics is not null && source->StatisticsCount != 0)
        {
            var list3 = new List<StatisticsStatisticUpdate>((int)source->StatisticsCount);
            for (uint i3 = 0; i3 < source->StatisticsCount; i3++)
            {
                list3.Add(StatisticsStatisticUpdate.FromNative(source->Statistics[i3]));
            }

            value.Statistics = list3;
        }
        value.TransactionId = Utf8.ToString(source->TransactionId);
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsUpdateStatisticsRequest* target, PlayFabArena arena)
    {
        *target = default;
        target->CustomTagsCount = (uint)(CustomTags is null ? 0 : CustomTags.Count);
        if (CustomTags is not null && CustomTags.Count > 0)
        {
            PFStringDictionaryEntry* entries0 = arena.Alloc<PFStringDictionaryEntry>(CustomTags.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, string> pair0 in CustomTags)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                entries0[next0].Value = arena.String(pair0.Value);
                next0++;
            }

            target->CustomTags = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->StatisticsCount = (uint)(Statistics is null ? 0 : Statistics.Count);
        if (Statistics is not null && Statistics.Count > 0)
        {
            PFStatisticsStatisticUpdate** array3 = arena.PointerArray<PFStatisticsStatisticUpdate>(Statistics.Count);
            for (int i3 = 0; i3 < Statistics.Count; i3++)
            {
                PFStatisticsStatisticUpdate* item3 = arena.Alloc<PFStatisticsStatisticUpdate>(1);
                Statistics[i3].WriteTo(item3, arena);
                array3[i3] = item3;
            }

            target->Statistics = array3;
        }
        target->TransactionId = arena.String(TransactionId);
    }
}

/// <summary>Projects <c>PFStatisticsUpdateStatisticsResponse</c>.</summary>
public sealed class StatisticsUpdateStatisticsResponse
{
    /// <summary><c>ColumnDetails</c>.</summary>
    public IReadOnlyDictionary<string, StatisticsStatisticColumnCollection>? ColumnDetails { get; set; }

    /// <summary><c>Entity</c>.</summary>
    public EntityKey? Entity { get; set; }

    /// <summary><c>Statistics</c>.</summary>
    public IReadOnlyDictionary<string, StatisticsEntityStatisticValue>? Statistics { get; set; }

    internal static unsafe StatisticsUpdateStatisticsResponse FromNative(PFStatisticsUpdateStatisticsResponse* source)
    {
        var value = new StatisticsUpdateStatisticsResponse();
        if (source->ColumnDetails is not null && source->ColumnDetailsCount != 0)
        {
            var map0 = new Dictionary<string, StatisticsStatisticColumnCollection>((int)source->ColumnDetailsCount, StringComparer.Ordinal);
            for (uint i0 = 0; i0 < source->ColumnDetailsCount; i0++)
            {
                map0[Utf8.ToString(source->ColumnDetails[i0].Key) ?? string.Empty] = StatisticsStatisticColumnCollection.FromNative(source->ColumnDetails[i0].Value);
            }

            value.ColumnDetails = map0;
        }
        value.Entity = source->Entity is null ? null : EntityKey.FromNative(source->Entity);
        if (source->Statistics is not null && source->StatisticsCount != 0)
        {
            var map3 = new Dictionary<string, StatisticsEntityStatisticValue>((int)source->StatisticsCount, StringComparer.Ordinal);
            for (uint i3 = 0; i3 < source->StatisticsCount; i3++)
            {
                map3[Utf8.ToString(source->Statistics[i3].Key) ?? string.Empty] = StatisticsEntityStatisticValue.FromNative(source->Statistics[i3].Value);
            }

            value.Statistics = map3;
        }
        return value;
    }

    internal unsafe void WriteTo(PFStatisticsUpdateStatisticsResponse* target, PlayFabArena arena)
    {
        *target = default;
        target->ColumnDetailsCount = (uint)(ColumnDetails is null ? 0 : ColumnDetails.Count);
        if (ColumnDetails is not null && ColumnDetails.Count > 0)
        {
            PFStatisticsStatisticColumnCollectionDictionaryEntry* entries0 = arena.Alloc<PFStatisticsStatisticColumnCollectionDictionaryEntry>(ColumnDetails.Count);
            int next0 = 0;
            foreach (KeyValuePair<string, StatisticsStatisticColumnCollection> pair0 in ColumnDetails)
            {
                entries0[next0].Key = arena.String(pair0.Key);
                if (pair0.Value is not null)
                {
                    PFStatisticsStatisticColumnCollection* item0 = arena.Alloc<PFStatisticsStatisticColumnCollection>(1);
                    pair0.Value.WriteTo(item0, arena);
                    entries0[next0].Value = item0;
                }
                next0++;
            }

            target->ColumnDetails = entries0;
        }
        if (Entity is not null)
        {
            PFEntityKey* native2 = arena.Alloc<PFEntityKey>(1);
            Entity.WriteTo(native2, arena);
            target->Entity = native2;
        }
        target->StatisticsCount = (uint)(Statistics is null ? 0 : Statistics.Count);
        if (Statistics is not null && Statistics.Count > 0)
        {
            PFStatisticsEntityStatisticValueDictionaryEntry* entries3 = arena.Alloc<PFStatisticsEntityStatisticValueDictionaryEntry>(Statistics.Count);
            int next3 = 0;
            foreach (KeyValuePair<string, StatisticsEntityStatisticValue> pair3 in Statistics)
            {
                entries3[next3].Key = arena.String(pair3.Key);
                if (pair3.Value is not null)
                {
                    PFStatisticsEntityStatisticValue* item3 = arena.Alloc<PFStatisticsEntityStatisticValue>(1);
                    pair3.Value.WriteTo(item3, arena);
                    entries3[next3].Value = item3;
                }
                next3++;
            }

            target->Statistics = entries3;
        }
    }
}
