<#
.SYNOPSIS
    Refreshes eng/gdk-learn-index.json from the published GDK table of contents.

.DESCRIPTION
    The area indexes under docs/api/ link each projected type to the GDK reference page for the
    native symbol its doc comment names. That mapping comes from the table of contents Microsoft
    Learn publishes for the GDK, which is downloaded here and reduced to three things:

      families   - API family name          -> the family's contents page
      symbols    - native function/type name -> that symbol's reference page
      restricted - the symbols whose pages are permissioned, so a public reader gets a sign-in
                   wall rather than the documentation

    The result is committed so that generating the reference works offline and produces the same
    output on every machine. Re-run this when the pinned GDK edition moves, then regenerate the
    reference and commit both.

.PARAMETER View
    The documentation moniker to index. Defaults to the pinned edition's moniker.

.PARAMETER OutFile
    Where to write the index. Defaults to eng/gdk-learn-index.json.
#>
[CmdletBinding()]
param(
    [string] $View = 'gdk-2604',
    [string] $OutFile
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot 'gdk-learn-index.json' }

$base = 'https://learn.microsoft.com/en-us/gaming/gdk/'
$tocUrl = "${base}toc.json?view=$View"

Write-Host "Downloading $tocUrl"
$toc = Invoke-RestMethod -Uri $tocUrl -MaximumRedirection 5

$families = [ordered]@{}
$symbols = [ordered]@{}
$restricted = [System.Collections.Generic.List[string]]::new()

function Read-TocNode {
    param($Node, [string[]] $Path)

    $title = if ($Node.PSObject.Properties['toc_title']) { $Node.toc_title } else { '' }
    $trail = $Path + $title
    $href = if ($Node.PSObject.Properties['href']) { $Node.href } else { $null }
    $private = $Node.PSObject.Properties['permissioned-type'] -and $Node.'permissioned-type' -eq 'private'

    if ($href -and -not $href.StartsWith('/') -and -not $href.StartsWith('http')) {
        # A family's contents page is named <family>_members, except for XSAPI and libHttpClient,
        # whose contents pages use the atoc- prefix.
        if ($href -like '*_members' -or $href -like 'docs/reference/live/xsapi-c/atoc*' -or
            $href -like 'docs/reference/live/httpclient/atoc*') {
            $family = if ($trail.Count -ge 2) { $trail[-2] } else { $title }
            if (-not $families.Contains($family)) { $families[$family] = $href }
        }

        # Symbol pages are titled with the bare identifier.
        if ($title -match '^[A-Za-z_][A-Za-z0-9_]*$' -and
            $title -match '^(Xbl|PF|X|Party|Chat|GameInput|HC|DStorage|Lamp)' -and
            -not $symbols.Contains($title)) {
            $symbols[$title] = $href
            if ($private) { $restricted.Add($title) }
        }
    }

    if ($Node.PSObject.Properties['children']) {
        foreach ($child in $Node.children) { Read-TocNode -Node $child -Path $trail }
    }
}

foreach ($item in $toc.items) { Read-TocNode -Node $item -Path @() }

$index = [ordered]@{
    '$comment'  = 'Generated by eng/update-learn-index.ps1 from the published GDK table of contents. Do not hand-edit.'
    'base'      = $base
    'view'      = $View
    'families'  = [ordered]@{}
    'symbols'   = [ordered]@{}
    'restricted' = @($restricted | Sort-Object -Unique)
}

foreach ($key in $families.Keys | Sort-Object) { $index.families[$key] = $families[$key] }
foreach ($key in $symbols.Keys | Sort-Object) { $index.symbols[$key] = $symbols[$key] }

$json = $index | ConvertTo-Json -Depth 5
[System.IO.File]::WriteAllText($OutFile, ($json -replace "`r`n", "`n") + "`n", [System.Text.UTF8Encoding]::new($false))

Write-Host "$OutFile : $($index.families.Count) families, $($index.symbols.Count) symbols, $($index.restricted.Count) restricted."
