// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFCatalog
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>The PlayFab Catalog service (<c>PFCatalog.h</c>).</summary>
public static unsafe class Catalog
{
    /// <summary>Calls <c>PFCatalogCreateDraftItemAsync</c>.</summary>
    public static Task<CatalogCreateDraftItemResponse> CreateDraftItemAsync(
        PlayFabEntity entity,
        CatalogCreateDraftItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogCreateDraftItemRequest* nativeRequest = arena.Alloc<PFCatalogCreateDraftItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogCreateDraftItemAsync(context, (PFCatalogCreateDraftItemRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogCreateDraftItemResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogCreateDraftItemGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogCreateDraftItemResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogCreateDraftItemGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogCreateDraftItemResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogCreateUploadUrlsAsync</c>.</summary>
    public static Task<CatalogCreateUploadUrlsResponse> CreateUploadUrlsAsync(
        PlayFabEntity entity,
        CatalogCreateUploadUrlsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogCreateUploadUrlsRequest* nativeRequest = arena.Alloc<PFCatalogCreateUploadUrlsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogCreateUploadUrlsAsync(context, (PFCatalogCreateUploadUrlsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogCreateUploadUrlsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogCreateUploadUrlsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogCreateUploadUrlsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogCreateUploadUrlsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogCreateUploadUrlsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogDeleteEntityItemReviewsAsync</c>.</summary>
    public static Task DeleteEntityItemReviewsAsync(
        PlayFabEntity entity,
        CatalogDeleteEntityItemReviewsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogDeleteEntityItemReviewsRequest* nativeRequest = arena.Alloc<PFCatalogDeleteEntityItemReviewsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogDeleteEntityItemReviewsAsync(context, (PFCatalogDeleteEntityItemReviewsRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogDeleteItemAsync</c>.</summary>
    public static Task DeleteItemAsync(
        PlayFabEntity entity,
        CatalogDeleteItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogDeleteItemRequest* nativeRequest = arena.Alloc<PFCatalogDeleteItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogDeleteItemAsync(context, (PFCatalogDeleteItemRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetCatalogConfigAsync</c>.</summary>
    public static Task<CatalogGetCatalogConfigResponse> GetCatalogConfigAsync(
        PlayFabEntity entity,
        CatalogGetCatalogConfigRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetCatalogConfigRequest* nativeRequest = arena.Alloc<PFCatalogGetCatalogConfigRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetCatalogConfigAsync(context, (PFCatalogGetCatalogConfigRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetCatalogConfigResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetCatalogConfigGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetCatalogConfigResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetCatalogConfigGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetCatalogConfigResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetDraftItemAsync</c>.</summary>
    public static Task<CatalogGetDraftItemResponse> GetDraftItemAsync(
        PlayFabEntity entity,
        CatalogGetDraftItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetDraftItemRequest* nativeRequest = arena.Alloc<PFCatalogGetDraftItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetDraftItemAsync(context, (PFCatalogGetDraftItemRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetDraftItemResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetDraftItemGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetDraftItemResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetDraftItemGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetDraftItemResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetDraftItemsAsync</c>.</summary>
    public static Task<CatalogGetDraftItemsResponse> GetDraftItemsAsync(
        PlayFabEntity entity,
        CatalogGetDraftItemsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetDraftItemsRequest* nativeRequest = arena.Alloc<PFCatalogGetDraftItemsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetDraftItemsAsync(context, (PFCatalogGetDraftItemsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetDraftItemsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetDraftItemsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetDraftItemsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetDraftItemsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetDraftItemsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetEntityDraftItemsAsync</c>.</summary>
    public static Task<CatalogGetEntityDraftItemsResponse> GetEntityDraftItemsAsync(
        PlayFabEntity entity,
        CatalogGetEntityDraftItemsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetEntityDraftItemsRequest* nativeRequest = arena.Alloc<PFCatalogGetEntityDraftItemsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetEntityDraftItemsAsync(context, (PFCatalogGetEntityDraftItemsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetEntityDraftItemsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetEntityDraftItemsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetEntityDraftItemsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetEntityDraftItemsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetEntityDraftItemsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetEntityItemReviewAsync</c>.</summary>
    public static Task<CatalogGetEntityItemReviewResponse> GetEntityItemReviewAsync(
        PlayFabEntity entity,
        CatalogGetEntityItemReviewRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetEntityItemReviewRequest* nativeRequest = arena.Alloc<PFCatalogGetEntityItemReviewRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetEntityItemReviewAsync(context, (PFCatalogGetEntityItemReviewRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetEntityItemReviewResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetEntityItemReviewGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetEntityItemReviewResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetEntityItemReviewGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetEntityItemReviewResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemAsync</c>.</summary>
    public static Task<CatalogGetItemResponse> GetItemAsync(
        PlayFabEntity entity,
        CatalogGetItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemRequest* nativeRequest = arena.Alloc<PFCatalogGetItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemAsync(context, (PFCatalogGetItemRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemContainersAsync</c>.</summary>
    public static Task<CatalogGetItemContainersResponse> GetItemContainersAsync(
        PlayFabEntity entity,
        CatalogGetItemContainersRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemContainersRequest* nativeRequest = arena.Alloc<PFCatalogGetItemContainersRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemContainersAsync(context, (PFCatalogGetItemContainersRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemContainersResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemContainersGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemContainersResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemContainersGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemContainersResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemModerationStateAsync</c>.</summary>
    public static Task<CatalogGetItemModerationStateResponse> GetItemModerationStateAsync(
        PlayFabEntity entity,
        CatalogGetItemModerationStateRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemModerationStateRequest* nativeRequest = arena.Alloc<PFCatalogGetItemModerationStateRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemModerationStateAsync(context, (PFCatalogGetItemModerationStateRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemModerationStateResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemModerationStateGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemModerationStateResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemModerationStateGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemModerationStateResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemPublishStatusAsync</c>.</summary>
    public static Task<CatalogGetItemPublishStatusResponse> GetItemPublishStatusAsync(
        PlayFabEntity entity,
        CatalogGetItemPublishStatusRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemPublishStatusRequest* nativeRequest = arena.Alloc<PFCatalogGetItemPublishStatusRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemPublishStatusAsync(context, (PFCatalogGetItemPublishStatusRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemPublishStatusResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemPublishStatusGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemPublishStatusResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemPublishStatusGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemPublishStatusResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemReviewSummaryAsync</c>.</summary>
    public static Task<CatalogGetItemReviewSummaryResponse> GetItemReviewSummaryAsync(
        PlayFabEntity entity,
        CatalogGetItemReviewSummaryRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemReviewSummaryRequest* nativeRequest = arena.Alloc<PFCatalogGetItemReviewSummaryRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemReviewSummaryAsync(context, (PFCatalogGetItemReviewSummaryRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemReviewSummaryResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemReviewSummaryGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemReviewSummaryResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemReviewSummaryGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemReviewSummaryResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemReviewsAsync</c>.</summary>
    public static Task<CatalogGetItemReviewsResponse> GetItemReviewsAsync(
        PlayFabEntity entity,
        CatalogGetItemReviewsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemReviewsRequest* nativeRequest = arena.Alloc<PFCatalogGetItemReviewsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemReviewsAsync(context, (PFCatalogGetItemReviewsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemReviewsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemReviewsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemReviewsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemReviewsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemReviewsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogGetItemsAsync</c>.</summary>
    public static Task<CatalogGetItemsResponse> GetItemsAsync(
        PlayFabEntity entity,
        CatalogGetItemsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogGetItemsRequest* nativeRequest = arena.Alloc<PFCatalogGetItemsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogGetItemsAsync(context, (PFCatalogGetItemsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogGetItemsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogGetItemsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogGetItemsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogGetItemsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogGetItemsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogPublishDraftItemAsync</c>.</summary>
    public static Task PublishDraftItemAsync(
        PlayFabEntity entity,
        CatalogPublishDraftItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogPublishDraftItemRequest* nativeRequest = arena.Alloc<PFCatalogPublishDraftItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogPublishDraftItemAsync(context, (PFCatalogPublishDraftItemRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogReportItemAsync</c>.</summary>
    public static Task ReportItemAsync(
        PlayFabEntity entity,
        CatalogReportItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogReportItemRequest* nativeRequest = arena.Alloc<PFCatalogReportItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogReportItemAsync(context, (PFCatalogReportItemRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogReportItemReviewAsync</c>.</summary>
    public static Task ReportItemReviewAsync(
        PlayFabEntity entity,
        CatalogReportItemReviewRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogReportItemReviewRequest* nativeRequest = arena.Alloc<PFCatalogReportItemReviewRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogReportItemReviewAsync(context, (PFCatalogReportItemReviewRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogReviewItemAsync</c>.</summary>
    public static Task ReviewItemAsync(
        PlayFabEntity entity,
        CatalogReviewItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogReviewItemRequest* nativeRequest = arena.Alloc<PFCatalogReviewItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogReviewItemAsync(context, (PFCatalogReviewItemRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogSearchItemsAsync</c>.</summary>
    public static Task<CatalogSearchItemsResponse> SearchItemsAsync(
        PlayFabEntity entity,
        CatalogSearchItemsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogSearchItemsRequest* nativeRequest = arena.Alloc<PFCatalogSearchItemsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogSearchItemsAsync(context, (PFCatalogSearchItemsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogSearchItemsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogSearchItemsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogSearchItemsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogSearchItemsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogSearchItemsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogSetItemModerationStateAsync</c>.</summary>
    public static Task SetItemModerationStateAsync(
        PlayFabEntity entity,
        CatalogSetItemModerationStateRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogSetItemModerationStateRequest* nativeRequest = arena.Alloc<PFCatalogSetItemModerationStateRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogSetItemModerationStateAsync(context, (PFCatalogSetItemModerationStateRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogSubmitItemReviewVoteAsync</c>.</summary>
    public static Task SubmitItemReviewVoteAsync(
        PlayFabEntity entity,
        CatalogSubmitItemReviewVoteRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogSubmitItemReviewVoteRequest* nativeRequest = arena.Alloc<PFCatalogSubmitItemReviewVoteRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogSubmitItemReviewVoteAsync(context, (PFCatalogSubmitItemReviewVoteRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogTakedownItemReviewsAsync</c>.</summary>
    public static Task TakedownItemReviewsAsync(
        PlayFabEntity entity,
        CatalogTakedownItemReviewsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogTakedownItemReviewsRequest* nativeRequest = arena.Alloc<PFCatalogTakedownItemReviewsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogTakedownItemReviewsAsync(context, (PFCatalogTakedownItemReviewsRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogUpdateCatalogConfigAsync</c>.</summary>
    public static Task UpdateCatalogConfigAsync(
        PlayFabEntity entity,
        CatalogUpdateCatalogConfigRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogUpdateCatalogConfigRequest* nativeRequest = arena.Alloc<PFCatalogUpdateCatalogConfigRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogUpdateCatalogConfigAsync(context, (PFCatalogUpdateCatalogConfigRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFCatalogUpdateDraftItemAsync</c>.</summary>
    public static Task<CatalogUpdateDraftItemResponse> UpdateDraftItemAsync(
        PlayFabEntity entity,
        CatalogUpdateDraftItemRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFCatalogUpdateDraftItemRequest* nativeRequest = arena.Alloc<PFCatalogUpdateDraftItemRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFCatalogUpdateDraftItemAsync(context, (PFCatalogUpdateDraftItemRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out CatalogUpdateDraftItemResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFCatalogUpdateDraftItemGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFCatalogUpdateDraftItemResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFCatalogUpdateDraftItemGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = CatalogUpdateDraftItemResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }
}
