// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFLeaderboards
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>The PlayFab Leaderboards service (<c>PFLeaderboards.h</c>).</summary>
public static unsafe class Leaderboards
{
    /// <summary>Calls <c>PFLeaderboardsCreateLeaderboardDefinitionAsync</c>.</summary>
    public static Task CreateLeaderboardDefinitionAsync(
        PlayFabEntity entity,
        LeaderboardsCreateLeaderboardDefinitionRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsCreateLeaderboardDefinitionRequest* nativeRequest = arena.Alloc<PFLeaderboardsCreateLeaderboardDefinitionRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsCreateLeaderboardDefinitionAsync(context, (PFLeaderboardsCreateLeaderboardDefinitionRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsDeleteLeaderboardDefinitionAsync</c>.</summary>
    public static Task DeleteLeaderboardDefinitionAsync(
        PlayFabEntity entity,
        LeaderboardsDeleteLeaderboardDefinitionRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsDeleteLeaderboardDefinitionRequest* nativeRequest = arena.Alloc<PFLeaderboardsDeleteLeaderboardDefinitionRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsDeleteLeaderboardDefinitionAsync(context, (PFLeaderboardsDeleteLeaderboardDefinitionRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsDeleteLeaderboardEntriesAsync</c>.</summary>
    public static Task DeleteLeaderboardEntriesAsync(
        PlayFabEntity entity,
        LeaderboardsDeleteLeaderboardEntriesRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsDeleteLeaderboardEntriesRequest* nativeRequest = arena.Alloc<PFLeaderboardsDeleteLeaderboardEntriesRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsDeleteLeaderboardEntriesAsync(context, (PFLeaderboardsDeleteLeaderboardEntriesRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsGetFriendLeaderboardForEntityAsync</c>.</summary>
    public static Task<LeaderboardsGetEntityLeaderboardResponse> GetFriendLeaderboardForEntityAsync(
        PlayFabEntity entity,
        LeaderboardsGetFriendLeaderboardForEntityRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsGetFriendLeaderboardForEntityRequest* nativeRequest = arena.Alloc<PFLeaderboardsGetFriendLeaderboardForEntityRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsGetFriendLeaderboardForEntityAsync(context, (PFLeaderboardsGetFriendLeaderboardForEntityRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsGetEntityLeaderboardResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsGetFriendLeaderboardForEntityGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsGetEntityLeaderboardResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsGetFriendLeaderboardForEntityGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsGetEntityLeaderboardResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsGetLeaderboardAroundEntityAsync</c>.</summary>
    public static Task<LeaderboardsGetEntityLeaderboardResponse> GetLeaderboardAroundEntityAsync(
        PlayFabEntity entity,
        LeaderboardsGetLeaderboardAroundEntityRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsGetLeaderboardAroundEntityRequest* nativeRequest = arena.Alloc<PFLeaderboardsGetLeaderboardAroundEntityRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsGetLeaderboardAroundEntityAsync(context, (PFLeaderboardsGetLeaderboardAroundEntityRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsGetEntityLeaderboardResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsGetLeaderboardAroundEntityGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsGetEntityLeaderboardResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsGetLeaderboardAroundEntityGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsGetEntityLeaderboardResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsGetLeaderboardAsync</c>.</summary>
    public static Task<LeaderboardsGetEntityLeaderboardResponse> GetLeaderboardAsync(
        PlayFabEntity entity,
        LeaderboardsGetEntityLeaderboardRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsGetEntityLeaderboardRequest* nativeRequest = arena.Alloc<PFLeaderboardsGetEntityLeaderboardRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsGetLeaderboardAsync(context, (PFLeaderboardsGetEntityLeaderboardRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsGetEntityLeaderboardResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsGetLeaderboardGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsGetEntityLeaderboardResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsGetLeaderboardGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsGetEntityLeaderboardResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsGetLeaderboardDefinitionAsync</c>.</summary>
    public static Task<LeaderboardsGetLeaderboardDefinitionResponse> GetLeaderboardDefinitionAsync(
        PlayFabEntity entity,
        LeaderboardsGetLeaderboardDefinitionRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsGetLeaderboardDefinitionRequest* nativeRequest = arena.Alloc<PFLeaderboardsGetLeaderboardDefinitionRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsGetLeaderboardDefinitionAsync(context, (PFLeaderboardsGetLeaderboardDefinitionRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsGetLeaderboardDefinitionResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsGetLeaderboardDefinitionGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsGetLeaderboardDefinitionResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsGetLeaderboardDefinitionGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsGetLeaderboardDefinitionResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsGetLeaderboardForEntitiesAsync</c>.</summary>
    public static Task<LeaderboardsGetEntityLeaderboardResponse> GetLeaderboardForEntitiesAsync(
        PlayFabEntity entity,
        LeaderboardsGetLeaderboardForEntitiesRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsGetLeaderboardForEntitiesRequest* nativeRequest = arena.Alloc<PFLeaderboardsGetLeaderboardForEntitiesRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsGetLeaderboardForEntitiesAsync(context, (PFLeaderboardsGetLeaderboardForEntitiesRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsGetEntityLeaderboardResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsGetLeaderboardForEntitiesGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsGetEntityLeaderboardResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsGetLeaderboardForEntitiesGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsGetEntityLeaderboardResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsIncrementLeaderboardVersionAsync</c>.</summary>
    public static Task<LeaderboardsIncrementLeaderboardVersionResponse> IncrementLeaderboardVersionAsync(
        PlayFabEntity entity,
        LeaderboardsIncrementLeaderboardVersionRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsIncrementLeaderboardVersionRequest* nativeRequest = arena.Alloc<PFLeaderboardsIncrementLeaderboardVersionRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsIncrementLeaderboardVersionAsync(context, (PFLeaderboardsIncrementLeaderboardVersionRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsIncrementLeaderboardVersionResponse value) =>
                {
                    value = null!;
                    PFLeaderboardsIncrementLeaderboardVersionResponse native = default;
                    int hr = NativePlayFab.PFLeaderboardsIncrementLeaderboardVersionGetResult((XAsyncBlock*)block, &native);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    value = LeaderboardsIncrementLeaderboardVersionResponse.FromNative(&native);
                    return HResult.SOk;
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsListLeaderboardDefinitionsAsync</c>.</summary>
    public static Task<LeaderboardsListLeaderboardDefinitionsResponse> ListLeaderboardDefinitionsAsync(
        PlayFabEntity entity,
        LeaderboardsListLeaderboardDefinitionsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsListLeaderboardDefinitionsRequest* nativeRequest = arena.Alloc<PFLeaderboardsListLeaderboardDefinitionsRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsListLeaderboardDefinitionsAsync(context, (PFLeaderboardsListLeaderboardDefinitionsRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LeaderboardsListLeaderboardDefinitionsResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLeaderboardsListLeaderboardDefinitionsGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLeaderboardsListLeaderboardDefinitionsResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLeaderboardsListLeaderboardDefinitionsGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LeaderboardsListLeaderboardDefinitionsResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsUnlinkLeaderboardFromStatisticAsync</c>.</summary>
    public static Task UnlinkLeaderboardFromStatisticAsync(
        PlayFabEntity entity,
        LeaderboardsUnlinkLeaderboardFromStatisticRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsUnlinkLeaderboardFromStatisticRequest* nativeRequest = arena.Alloc<PFLeaderboardsUnlinkLeaderboardFromStatisticRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsUnlinkLeaderboardFromStatisticAsync(context, (PFLeaderboardsUnlinkLeaderboardFromStatisticRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsUpdateLeaderboardDefinitionAsync</c>.</summary>
    public static Task UpdateLeaderboardDefinitionAsync(
        PlayFabEntity entity,
        LeaderboardsUpdateLeaderboardDefinitionRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsUpdateLeaderboardDefinitionRequest* nativeRequest = arena.Alloc<PFLeaderboardsUpdateLeaderboardDefinitionRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsUpdateLeaderboardDefinitionAsync(context, (PFLeaderboardsUpdateLeaderboardDefinitionRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFLeaderboardsUpdateLeaderboardEntriesAsync</c>.</summary>
    public static Task UpdateLeaderboardEntriesAsync(
        PlayFabEntity entity,
        LeaderboardsUpdateLeaderboardEntriesRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLeaderboardsUpdateLeaderboardEntriesRequest* nativeRequest = arena.Alloc<PFLeaderboardsUpdateLeaderboardEntriesRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLeaderboardsUpdateLeaderboardEntriesAsync(context, (PFLeaderboardsUpdateLeaderboardEntriesRequest*)requestPointer, (XAsyncBlock*)block),
                static block => Native.XAsyncGetStatus((XAsyncBlock*)block, 0),
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }
}
