// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFLocalization
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>The PlayFab Localization service (<c>PFLocalization.h</c>).</summary>
public static unsafe class Localization
{
    /// <summary>Calls <c>PFLocalizationGetLanguageListAsync</c>.</summary>
    public static Task<LocalizationGetLanguageListResponse> GetLanguageListAsync(
        PlayFabEntity entity,
        LocalizationGetLanguageListRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFLocalizationGetLanguageListRequest* nativeRequest = arena.Alloc<PFLocalizationGetLanguageListRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFLocalizationGetLanguageListAsync(context, (PFLocalizationGetLanguageListRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out LocalizationGetLanguageListResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFLocalizationGetLanguageListGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFLocalizationGetLanguageListResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFLocalizationGetLanguageListGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = LocalizationGetLanguageListResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }
}
