// <auto-generated>
//   Generated by eng/playfab/emit_services.py from the Microsoft GDK 260404 PlayFab headers.
//   Source header family: PFMultiplayerServer
//   Do not edit by hand: re-run `pwsh -NoProfile -File eng/generate-playfab.ps1`.
// </auto-generated>


#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using GDK.Net.Interop;
using GDK.Net.Users;

namespace GDK.Net.PlayFab;

/// <summary>The PlayFab MultiplayerServer service (<c>PFMultiplayerServer.h</c>).</summary>
public static unsafe class MultiplayerServer
{
    /// <summary>Calls <c>PFMultiplayerServerListBuildAliasesAsync</c>.</summary>
    public static Task<MultiplayerServerListBuildAliasesResponse> ListBuildAliasesAsync(
        PlayFabEntity entity,
        MultiplayerServerListBuildAliasesRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFMultiplayerServerListBuildAliasesRequest* nativeRequest = arena.Alloc<PFMultiplayerServerListBuildAliasesRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFMultiplayerServerListBuildAliasesAsync(context, (PFMultiplayerServerListBuildAliasesRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out MultiplayerServerListBuildAliasesResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFMultiplayerServerListBuildAliasesGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFMultiplayerServerListBuildAliasesResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFMultiplayerServerListBuildAliasesGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = MultiplayerServerListBuildAliasesResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFMultiplayerServerListBuildSummariesV2Async</c>.</summary>
    public static Task<MultiplayerServerListBuildSummariesResponse> ListBuildSummariesV2Async(
        PlayFabEntity entity,
        MultiplayerServerListBuildSummariesRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFMultiplayerServerListBuildSummariesRequest* nativeRequest = arena.Alloc<PFMultiplayerServerListBuildSummariesRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFMultiplayerServerListBuildSummariesV2Async(context, (PFMultiplayerServerListBuildSummariesRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out MultiplayerServerListBuildSummariesResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFMultiplayerServerListBuildSummariesV2GetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFMultiplayerServerListBuildSummariesResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFMultiplayerServerListBuildSummariesV2GetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = MultiplayerServerListBuildSummariesResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFMultiplayerServerListQosServersForTitleAsync</c>.</summary>
    public static Task<MultiplayerServerListQosServersForTitleResponse> ListQosServersForTitleAsync(
        PlayFabEntity entity,
        MultiplayerServerListQosServersForTitleRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFMultiplayerServerListQosServersForTitleRequest* nativeRequest = arena.Alloc<PFMultiplayerServerListQosServersForTitleRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFMultiplayerServerListQosServersForTitleAsync(context, (PFMultiplayerServerListQosServersForTitleRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out MultiplayerServerListQosServersForTitleResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFMultiplayerServerListQosServersForTitleGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFMultiplayerServerListQosServersForTitleResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFMultiplayerServerListQosServersForTitleGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = MultiplayerServerListQosServersForTitleResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }

    /// <summary>Calls <c>PFMultiplayerServerRequestMultiplayerServerAsync</c>.</summary>
    public static Task<MultiplayerServerRequestMultiplayerServerResponse> RequestMultiplayerServerAsync(
        PlayFabEntity entity,
        MultiplayerServerRequestMultiplayerServerRequest request,
        CancellationToken cancellationToken = default)
    {
        if (entity is null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        if (request is null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        IntPtr context = entity.Handle;
        var arena = new PlayFabArena();
        try
        {
            PFMultiplayerServerRequestMultiplayerServerRequest* nativeRequest = arena.Alloc<PFMultiplayerServerRequestMultiplayerServerRequest>(1);
            request.WriteTo(nativeRequest, arena);
            IntPtr requestPointer = (IntPtr)nativeRequest;

            return PlayFabCall.InvokeAsync(
                arena,
                block => NativePlayFab.PFMultiplayerServerRequestMultiplayerServerAsync(context, (PFMultiplayerServerRequestMultiplayerServerRequest*)requestPointer, (XAsyncBlock*)block),
                static (IntPtr block, out MultiplayerServerRequestMultiplayerServerResponse value) =>
                {
                    value = null!;
                    nuint size;
                    int hr = NativePlayFab.PFMultiplayerServerRequestMultiplayerServerGetResultSize((XAsyncBlock*)block, &size);
                    if (HResult.Failed(hr))
                    {
                        return hr;
                    }

                    IntPtr buffer = Marshal.AllocHGlobal(checked((int)size));
                    try
                    {
                        PFMultiplayerServerRequestMultiplayerServerResponse* result;
                        nuint used;
                        hr = NativePlayFab.PFMultiplayerServerRequestMultiplayerServerGetResult((XAsyncBlock*)block, size, (void*)buffer, &result, &used);
                        if (HResult.Failed(hr))
                        {
                            return hr;
                        }

                        value = MultiplayerServerRequestMultiplayerServerResponse.FromNative(result);
                        return HResult.SOk;
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(buffer);
                    }
                },
                cancellationToken);
        }
        catch
        {
            arena.Dispose();
            throw;
        }
    }
}
