using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using GDK.Net.SystemInfo;
using GDK.Net.Users;

namespace GDK.Net.LiveHarness;

/// <summary>
/// Gaming Runtime lifetime and the <c>XUser</c> family.
/// </summary>
/// <remarks>
/// Almost everything else in the harness depends on <c>runtime.initialize</c> and most of the Xbox
/// Live surface on <c>users.add</c>, so these two ids are the ones most often named in a
/// <see cref="LiveCheck.Requires"/> list.
/// </remarks>
internal static class RuntimeChecks
{
    public static IEnumerable<LiveCheck> All()
    {
        // Recorded first so a failure further down can be read in the right context: Xbox consoles
        // require NativeAOT, where P/Invoke stubs are generated by ILC at build time rather than by
        // the runtime marshaller.
        yield return LiveCheck.Sync("runtime.compilation", _ =>
        {
            string mode = RuntimeFeature.IsDynamicCodeSupported ? "JIT" : "NativeAOT";
            return $"Running {mode}-compiled ({RuntimeInformation.ProcessArchitecture})";
        });

        yield return LiveCheck.Sync("runtime.initialize", ctx =>
        {
            ctx.Runtime = GameRuntime.Initialize();
            return "Gaming Runtime initialized; operations name no task queue, so they resolve the process default";
        });

        yield return LiveCheck.Sync("runtime.feature-gate", ctx =>
            ctx.RequireRuntime.IsFeatureAvailable(GameRuntimeFeature.User)
                ? "XUser feature is available"
                : throw new InvalidOperationException("XGameRuntimeIsFeatureAvailable(XUser) returned false."),
            "runtime.initialize");

        yield return LiveCheck.Sync("runtime.title-id", ctx =>
        {
            uint titleId = GameLauncher.GetXboxTitleId();
            ctx.State["xbl.titleId"] = titleId;

            if (ctx.Options.Scid is not null)
            {
                return $"XGameGetXboxTitleId = {titleId} (0x{titleId:X8}); using the SCID passed on " +
                       $"the command line ('{ctx.Options.Scid}')";
            }

            ctx.Scid = DeriveScid(titleId);
            return $"XGameGetXboxTitleId = {titleId} (0x{titleId:X8}); derived SCID '{ctx.Scid}'";
        }, "runtime.initialize");

        foreach (LiveCheck check in UserFamily())
        {
            yield return check;
        }
    }

    private static IEnumerable<LiveCheck> UserFamily()
    {
        yield return LiveCheck.Sync("users.subscribe-changed", ctx =>
        {
            var changes = new List<string>();
            ctx.State["user.changes"] = changes;
            ctx.RequireRuntime.Users.UserChanged += (_, e) =>
                changes.Add($"{e.Change} localId={e.LocalId} resolved={(e.User is null ? "no" : "yes")}");
            return "Subscribed to XUserRegisterForChangeEvent";
        }, "runtime.initialize");

        yield return LiveCheck.Async("users.add", async ctx =>
        {
            ctx.User = await AddUserAsync(ctx).ConfigureAwait(false);
            return $"Added user 0x{ctx.User.Id:X16} localId={ctx.User.LocalId}";
        }, "runtime.initialize");

        yield return LiveCheck.Sync("user.id", ctx => $"XUserGetId = 0x{ctx.RequireUser.Id:X16}", "users.add");
        yield return LiveCheck.Sync("user.local-id", ctx => $"XUserGetLocalId = {ctx.RequireUser.LocalId}", "users.add");
        yield return LiveCheck.Sync("user.state", ctx => $"XUserGetState = {ctx.RequireUser.State}", "users.add");
        yield return LiveCheck.Sync("user.age-group", ctx => $"XUserGetAgeGroup = {ctx.RequireUser.AgeGroup}", "users.add");
        yield return LiveCheck.Sync("user.is-guest", ctx => $"XUserGetIsGuest = {ctx.RequireUser.IsGuest}", "users.add");

        foreach (GamertagComponent component in Enum.GetValues<GamertagComponent>())
        {
            GamertagComponent captured = component;
            yield return LiveCheck.Sync($"user.gamertag.{captured}", ctx =>
            {
                string tag = ctx.RequireUser.GetGamertag(captured);
                return $"XUserGetGamertag({captured}) = '{tag}' ({tag.Length} chars)";
            }, "users.add");
        }

        UserPrivilege[] privileges =
        [
            UserPrivilege.Communications,
            UserPrivilege.Multiplayer,
            UserPrivilege.CrossPlay,
        ];

        foreach (UserPrivilege privilege in privileges)
        {
            UserPrivilege captured = privilege;
            yield return LiveCheck.Sync($"user.privilege.{captured}", ctx =>
            {
                bool granted = ctx.RequireUser.CheckPrivilege(captured, out UserPrivilegeDenyReason reason);
                return $"XUserCheckPrivilege({captured}) granted={granted} denyReason={reason}";
            }, "users.add");
        }

        yield return LiveCheck.Sync("user.equality", ctx =>
        {
            using User duplicate = ctx.RequireUser.Duplicate();
            bool equal = duplicate == ctx.RequireUser;
            bool sameHash = duplicate.GetHashCode() == ctx.RequireUser.GetHashCode();

            return equal && sameHash
                ? "XUserDuplicateHandle round-trips: XUserCompare equal and hashes match"
                : throw new InvalidOperationException(
                    $"Duplicate handle mismatch: equal={equal} sameHash={sameHash}");
        }, "users.add");

        yield return LiveCheck.Async("user.gamer-picture", async ctx =>
        {
            byte[] bytes = await ctx.RequireUser
                .GetGamerPictureAsync(GamerPictureSize.Small).ConfigureAwait(false);
            if (bytes.Length == 0)
            {
                throw new InvalidOperationException("XUserGetGamerPictureAsync returned an empty buffer.");
            }

            string path = Path.Combine(ctx.Options.OutputDirectory, "gamerpicture-small.png");
            File.WriteAllBytes(path, bytes);
            return $"XUserGetGamerPictureAsync returned {bytes.Length} bytes; written to {path}";
        }, "users.add");

        yield return LiveCheck.Async("user.cancellation", async ctx =>
        {
            using var cts = new CancellationTokenSource();
            Task<byte[]> pending = ctx.RequireUser.GetGamerPictureAsync(GamerPictureSize.ExtraLarge, cts.Token);
            cts.Cancel();

            try
            {
                byte[] bytes = await pending.ConfigureAwait(false);
                return $"Completed before XAsyncCancel took effect ({bytes.Length} bytes); cancellation is best-effort.";
            }
            catch (OperationCanceledException)
            {
                return "XAsyncCancel produced E_ABORT and surfaced as OperationCanceledException.";
            }
        }, "users.add");

        yield return LiveCheck.Sync("user.is-sign-out-present", _ =>
            $"XUserIsSignOutPresent through the shim returned {User.IsSignOutPresent()}");

        yield return LiveCheck.Sync("users.changed-events", ctx =>
        {
            Thread.Sleep(TimeSpan.FromMilliseconds(50));
            var changes = ctx.Get<List<string>>("user.changes");
            return changes.Count == 0
                ? "No XUser change events observed (expected unless the account changed during the run)"
                : $"Observed {changes.Count}: {string.Join("; ", changes)}";
        }, "users.subscribe-changed");
    }

    /// <summary>
    /// Teardown for the user family. Runs after every other family, because signing out invalidates
    /// the handle that the rest of the harness is built on.
    /// </summary>
    /// <remarks>
    /// <c>users.sign-out</c> signs the account out of the machine for real, so the next run has no
    /// default user and <c>users.add</c> falls back to the account picker. That cost is accepted
    /// deliberately: <c>XUserSignOutAsync</c> cannot be proven any other way, and a harness that
    /// only calls the non-destructive half of the API is not testing the half most likely to break.
    /// </remarks>
    public static IEnumerable<LiveCheck> Teardown()
    {
        yield return LiveCheck.Async("users.sign-out", async ctx =>
        {
            // Sign-out is a console affordance: on PC the account is owned by the Xbox app and the
            // GDK reports E_NOINTERFACE rather than implementing it.
            DeviceGate.RequireConsole("XUserSignOutAsync");

            await ctx.RequireUser.SignOutAsync().ConfigureAwait(false);
            return "XUserSignOutAsync completed; the account is signed out of this machine";
        }, "users.add");

        yield return LiveCheck.Sync("users.dispose", ctx =>
        {
            ctx.RequireUser.Dispose();
            ctx.User = null;
            return "XUserCloseHandle";
        }, "users.add");
    }

    /// <summary>
    /// Builds the title's Service Configuration ID from its title id.
    /// </summary>
    /// <remarks>
    /// A title's SCID is the null GUID with the 32-bit title id occupying the last eight hex digits
    /// of the final group, lower case. That makes <c>--scid</c> an override for the unusual case —
    /// a title whose SCID was assigned separately in Partner Center — rather than something every
    /// run has to be told.
    /// </remarks>
    private static string DeriveScid(uint titleId) => $"00000000-0000-0000-0000-0000{titleId:x8}";

    private static async Task<User> AddUserAsync(CheckContext ctx)
    {
        try
        {
            return await ctx.RequireRuntime.Users
                .AddAsync(UserAddOptions.AddDefaultUserSilently).ConfigureAwait(false);
        }
        catch (UserException)
        {
            // A silent add fails when there is no default user; the UI path needs a foreground window.
            return await ctx.RequireRuntime.Users
                .AddAsync(UserAddOptions.AddDefaultUserAllowingUI).ConfigureAwait(false);
        }
    }
}
